### ISSUE TITLE
Data Conflict when syncing with git source built

### ISSUE THREAD

**Issue by rodrigoccurvo** [baumgarr/nixnote2#105]
I made some changes in my tags using a version built from the latest source on github, including using nested tags. When I tried syncing, I kept receiving the error "Data Conflict" but with no message. 

I tried debugging the code, but I don't understand Evernote's API calls to easily figure out what was happening.

Then I tried using the beta5 version to sync (same config/db) and it worked. When I came back to the source version, everything was fine. 

I couldn't replicate the error, even tried creating some tags and nesting them, but it didn't happen again (before fixing it with beta5, it happened every time I tried syncing). Here's the last log I got:

```
 INFO 2015-11-25 22:31:01.916 ( nixnote.cpp @ 1765 ) "Beginning Sync" 
ERROR 2015-11-25 22:43:17.604 ( communication/communicationmanager.cpp @ 388 ) EDAMUserException: 10 

ERROR 2015-11-25 22:43:17.604 ( communication/communicationmanager.cpp @ 389 )  Tag name:  "math" 

DEBUG 2015-11-25 22:43:17.604 ( utilities/debugtool.cpp @ 33 ) *** Dumping Tag *** 
DEBUG 2015-11-25 22:43:17.604 ( utilities/debugtool.cpp @ 215 ) "guid" : "1e25dad1-2c8d-4117-abbe-3fc477531ac5" : 
DEBUG 2015-11-25 22:43:17.604 ( utilities/debugtool.cpp @ 215 ) "name" : "math" : 
DEBUG 2015-11-25 22:43:17.604 ( utilities/debugtool.cpp @ 215 ) "parent" : "f8323b0d-0a0e-43ca-90f6-1294699f8a28" : 
DEBUG 2015-11-25 22:43:17.604 ( utilities/debugtool.cpp @ 245 ) "USN" : 0 : 
DEBUG 2015-11-25 22:43:17.604 ( utilities/debugtool.cpp @ 38 ) *** Tag Dump complete *** 
 INFO 2015-11-25 22:43:17.611 ( nixnote.cpp @ 1765 ) "Communication Error - Data conflict : " 
 INFO 2015-11-25 22:43:17.612 ( nixnote.cpp @ 1765 ) "Communication Error - Data conflict : " 
```

I don't know if it is something specific with my built version, but...

**Comment by baumgarr** [comment]
It probably isn't anything specific to the version you built.  If I were to guess it was caused by one of these...

- The parent tag didn't exist at the time the child tried to sync.
- The parent of the tag was deleted.
- The tag with that name already existed.

I don't recall anything between betas 4 & 5 that would have corrected this, but I'm glad it is working now.
