### ISSUE TITLE
I Can't search notes with todo

### ISSUE THREAD

**Issue by yoburtu** [baumgarr/nixnote2#106]
Hello,

Nixnote 2 version: Beta 5.

When I create a new text note with "todo" check, I can't search this notes with "todo:false" in search section. The column "has to-do" don't have the dot.

If I create the note in web interfaz with "todo", I can search this note and the column "has to-do" has the dot.

Best regards.

**Comment by baumgarr** [comment]
I can't reproduce this.  If you create the note in NixNote does the problem remain, or does it happen regardless of where the note is created?

**Comment by yoburtu** [comment]
The problem is when I create the note in NixNote. If I create the note in web Client, for example, it work.

Regards.

**Comment by baumgarr** [comment]
This should be fixed in the next release.  Thanks!
