### ISSUE TITLE
When I opening note I need to wait few seconds (only when account have few k notes)

### ISSUE THREAD

**Issue by vitaly-zdanevich** [baumgarr/nixnote2#108]
All notes downloaded. I have more than 3k notes. At resource monitor I see max cpu usage at this few seconds by NixNote. I hope you can optimise this.

I tried another account with 50 notes and NixNote beta5 works good - switching to another note take 1/10 second 

Debian 8 i386, ram is anough

**Comment by baumgarr** [comment]
It really depends on the structure of the note and if you are searching.  I have almost 3000 notes in one account and it is very responsive.  If you want to change the message level to "trace" in the debugging options I can see where it is slow to see if there is any optimization that can be done, but I'm not sure there will be a whole lot of improvements.

**Comment by vitaly-zdanevich** [comment]
I set message level to 'trace' - reports will reach you automatically?

**Comment by vitaly-zdanevich** [comment]
You wrote:
`It really depends on the structure of the note`

I tested on maximum simplest note - the same few seconds for switching to another note as for clipped pages.

**Comment by jeffbuhrt** [comment]
vitaly-zdanevich start NixNote2 from a terminal, optionally with: nixnote2 > file.out 2>&1
The logging is to the output of the process only. #102 might be related to what you see if some notes cause ~100% when open and others don't. Also, what OS flavor and window manager are you using? [Fedora Gnome for example?] Do you have a specific repeat-by? Something I did for #102 was put the notes with a problem into their own notebook, make a 2nd Evernote account, share the notebook to the new, move .nixnote out of the way, restart nixnote2b5 and confirm the repeat-by. Then you can share that notebook to Randy, etc to repeat the problem also.

**Comment by baumgarr** [comment]
To answer your other question... Nothing is ever sent to me regardless of the message level.
