### ISSUE TITLE
Editor font color in plain-text

### ISSUE THREAD

**Issue by vitaly-zdanevich** [baumgarr/nixnote2#109]
I have dark gtk-theme and in NixNote 2 beta 5 I see dark font on dark background

**Comment by aiguofer** [comment]
Same here. I'm using https://github.com/killhellokitty/DeLorean-Dark-3.18 on Gnome Shell 3.18 and this is what it looks like for me:

![selection_004](https://cloud.githubusercontent.com/assets/780934/11550240/9ae0376e-993b-11e5-8372-fe0bed76a0d3.png)

Btw, glad to see some active development again, thanks!

**Comment by baumgarr** [comment]
I added the ability via the theme.ini to set the default background & font color of the editor.  I also setup a "dark editor" theme.  It will be available in the next release.

**Comment by vitaly-zdanevich** [comment]
Thank you for the dark theme and for NixNote!
