### ISSUE TITLE
Nixnote Unity scope not working in Ubuntu 14.04

### ISSUE THREAD

**Issue by hotice** [baumgarr/nixnote2#11]
The new Unity scope doesn't work for me in Ubuntu 14.04: I can see the scope under the Application lens (if you select Filter Results > Dash plugins) but no search results are returned by this scope. 

I've tried both the global search and selecting the plugin on the right as well as "evernote:" and "nixnote" keywords, but they didn't return any results.

I'm using Nixnote2 Beta 2 (and the new Nixnote Unity scope) debs downloaded from Sourceforge, in Ubuntu 14.04 (64bit).

**Comment by baumgarr** [comment]
I haven't received a lot of interest in the Unity Scope interface, so unless people say they actually need it I am dropping support for it.
