### ISSUE TITLE
nixnote2-2.0_beta6-0.x86_64.rpm fails to run on Fedora 23 x86_64

### ISSUE THREAD

**Issue by jeffbuhrt** [baumgarr/nixnote2#114]
Fedora 4.2.6-300.fc23.x86_64

@baumgarr I manually uninstalled nixnote2 per your note for #101.
Running Nixnote2 b6 fails even without having a .nixnote directory, but it does create the directory:
ls -l .nixnote
total 24
-rw-rw-r--. 1 jbuhrt jbuhrt  185 Dec 10 21:52 accounts.conf
drwxrwxr-x. 5 jbuhrt jbuhrt 4096 Dec 10 21:52 db-1
drwxrwxr-x. 2 jbuhrt jbuhrt 4096 Dec 10 21:52 logs-1
drwxrwxr-x. 2 jbuhrt jbuhrt 4096 Dec 10 21:52 qss
drwxrwxr-x. 2 jbuhrt jbuhrt 4096 Dec 10 21:52 spell
drwxrwxr-x. 2 jbuhrt jbuhrt 4096 Dec 10 21:52 tmp-1

nixnote2
Error: signal 11:
nixnote2(_Z13fault_handleri+0x2e)[0x5579eed9d1ae]
/lib64/libc.so.6(+0x34b20)[0x7fa2e8da9b20]
/lib64/libc.so.6(+0x9ede0)[0x7fa2e8e13de0]
nixnote2(_ZN17CrossMemoryMapper5writeE10QByteArray+0x106)[0x5579ef166936]
nixnote2(_ZN17CrossMemoryMapper5writeE7QString+0x2c)[0x5579ef166a8c]
nixnote2(main+0x122a)[0x5579eed98d7a]
/lib64/libc.so.6(__libc_start_main+0xf0)[0x7fa2e8d95580]
nixnote2(_start+0x29)[0x5579eed9d079]

$ rm -rf .nixnote
$ gdb nixnote2
GNU gdb (GDB) Fedora 7.10.1-30.fc23
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from nixnote2...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/nixnote2 
Missing separate debuginfos, use: dnf debuginfo-install nixnote2-2.0_beta6-0.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffddd32700 (LWP 25870)]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff1e7ede0 in __memcpy_sse2_unaligned () from /lib64/libc.so.6
(gdb) where
#0  0x00007ffff1e7ede0 in __memcpy_sse2_unaligned () from /lib64/libc.so.6
#1  0x00005555559ec936 in CrossMemoryMapper::write(QByteArray) ()
#2  0x00005555559eca8c in CrossMemoryMapper::write(QString) ()
#3  0x000055555561ed7a in main ()
(gdb) 

Note to make sure I uninstalled and reinstalled a couple times making sure it was removed in the middle, etc.

 # rpm --erase nixnote2
 # rpm -iv nixnote2-2.0_beta6-0.x86_64.rpm 
Preparing packages...
nixnote2-2.0_beta6-0.x86_64

$ rpm -qail nixnote2
Name        : nixnote2
Version     : 2.0_beta6
Release     : 0
Architecture: x86_64
Install Date: Thu 10 Dec 2015 09:48:29 PM EST
Group       : Applications/Internet
Size        : 10323990
License     : GPLv2
Signature   : (none)
Source RPM  : nixnote2-2.0_beta6-0.src.rpm
Build Date  : Fri 04 Dec 2015 12:30:37 AM EST
Build Host  : localhost.localdomain
Relocations : (not relocatable)
Packager    : Randy Baumgarte <randy@fbn.cx>
Vendor      : Randy Baumgarte
URL         : http://nevernote.sourceforge.net/
Summary     : An Evernote client clone for Linux
Description :
NixNote:: Evernote client clone for Linux

Copyright 2009-2015, Randy Baumgarte
Licensed under GNU General Public Lisence version 2

This is an incomplete clone of Evernote designed to run on Linux.
While this is designed to work with Evernote, it is in no way
connected with or supported by Evernote.  Any problems you encounter will not be corrected by them
and, since this is GPL software, you are using this software at your own risk.

See release.txt for details of what works and what doesn't work.

Documents:

changelog.txt:  ChangeLog and development history.
install.txt:    Build and install instructions.
credit.txt:     Credit of nixnote developers.
gpl.txt:        License description of GPL v2.
license.html:   Legal notices for licenses and trademarks.
colors.txt:     Sample config file to the color menu for note & title backgrounds.
theme.ini:      Theme configuration file.
shortcuts.txt   Shortcut configuration file.

  CFLAGS="${CFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic}" ; export CFLAGS ;
  CXXFLAGS="${CXXFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic}" ; export CXXFLAGS ;
  FFLAGS="${FFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -I/usr/lib64/gfortran/modules}" ; export FFLAGS ;
  FCFLAGS="${FCFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -I/usr/lib64/gfortran/modules}" ; export FCFLAGS ;
  LDFLAGS="${LDFLAGS:--Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld}"; export LDFLAGS;
  [ "1" = 1 ] && for i in $(find $(dirname ./configure) -name config.guess -o -name config.sub) ; do
      [ -f /usr/lib/rpm/redhat/$(basename $i) ] && /usr/bin/rm -f $i && /usr/bin/cp -fv /usr/lib/rpm/redhat/$(basename $i) $i ;
  done ;
  [ "1" = 1 ] && [ x != "x-specs=/usr/lib/rpm/redhat/redhat-hardened-ld" ] &&
      for i in $(find . -name ltmain.sh) ; do
        /usr/bin/sed -i.backup -e 's~compiler_flags=$~compiler_flags="-specs=/usr/lib/rpm/redhat/redhat-hardened-ld"~' $i
      done ;
  ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu \
	--program-prefix= \
	--disable-dependency-tracking \
	--prefix=/usr \
	--exec-prefix=/usr \
	--bindir=/usr/bin \
	--sbindir=/usr/sbin \
	--sysconfdir=/etc \
	--datadir=/usr/share \
	--includedir=/usr/include \
	--libdir=/usr/lib64 \
	--libexecdir=/usr/libexec \
	--localstatedir=/var \
	--sharedstatedir=/var/lib \
	--mandir=/usr/share/man \
	--infodir=/usr/share/info
sed -i 's|^hardcode_libdir_flag_spec=.*|hardcode_libdir_flag_spec=""|g' libtool
sed -i 's|^runpath_var=LD_RUN_PATH|runpath_var=DIE_RPATH_DIE|g' libtool
/usr/bin/nixnote2
/usr/share/applications/nixnote2.desktop
/usr/share/doc/nixnote2
/usr/share/doc/nixnote2/changelog.Debian.gz
/usr/share/doc/nixnote2/copyright
/usr/share/man/man1/nixnote2.1.gz
/usr/share/nixnote2
/usr/share/nixnote2/README.txt
/usr/share/nixnote2/Readme_Arch_Linux.txt
/usr/share/nixnote2/certs
/usr/share/nixnote2/certs/thawte.pem
/usr/share/nixnote2/certs/verisign_certs.pem
/usr/share/nixnote2/changelog.txt
/usr/share/nixnote2/colors.txt
/usr/share/nixnote2/gpl.txt
/usr/share/nixnote2/help
/usr/share/nixnote2/help/UserDocumentation.odt
/usr/share/nixnote2/help/UserDocumentation.pdf
/usr/share/nixnote2/help/about.html
/usr/share/nixnote2/images
/usr/share/nixnote2/images/alarmclock.png
/usr/share/nixnote2/images/attribute.png
/usr/share/nixnote2/images/black_dot.png
/usr/share/nixnote2/images/bold.png
/usr/share/nixnote2/images/bulletList.png
/usr/share/nixnote2/images/classic-theme
/usr/share/nixnote2/images/classic-theme/home.png
/usr/share/nixnote2/images/classic-theme/left_arrow.png
/usr/share/nixnote2/images/classic-theme/notebook-green.png
/usr/share/nixnote2/images/classic-theme/right_arrow.png
/usr/share/nixnote2/images/classic-theme/stack-green.png
/usr/share/nixnote2/images/classic-theme/synchronize.png
/usr/share/nixnote2/images/classic-theme/windowIcon.png
/usr/share/nixnote2/images/collapsed.png
/usr/share/nixnote2/images/copy.png
/usr/share/nixnote2/images/cut.png
/usr/share/nixnote2/images/datetime.png
/usr/share/nixnote2/images/delete.png
/usr/share/nixnote2/images/down_arrow_small.png
/usr/share/nixnote2/images/emailIcon.png
/usr/share/nixnote2/images/encrypt.png
/usr/share/nixnote2/images/eraser.png
/usr/share/nixnote2/images/expanded.png
/usr/share/nixnote2/images/favorites.png
/usr/share/nixnote2/images/fileclose.png
/usr/share/nixnote2/images/fontColor.png
/usr/share/nixnote2/images/fontHilight.png
/usr/share/nixnote2/images/gps.png
/usr/share/nixnote2/images/grid.png
/usr/share/nixnote2/images/hline.png
/usr/share/nixnote2/images/home.png
/usr/share/nixnote2/images/htmlentities.png
/usr/share/nixnote2/images/indent.png
/usr/share/nixnote2/images/italic.png
/usr/share/nixnote2/images/justifyCenter.png
/usr/share/nixnote2/images/justifyLeft.png
/usr/share/nixnote2/images/justifyRight.png
/usr/share/nixnote2/images/left_arrow.png
/usr/share/nixnote2/images/lens.png
/usr/share/nixnote2/images/link.png
/usr/share/nixnote2/images/linked-notebook.png
/usr/share/nixnote2/images/local-notebook.png
/usr/share/nixnote2/images/navigation.png
/usr/share/nixnote2/images/newNote.png
/usr/share/nixnote2/images/notebook-conflict.png
/usr/share/nixnote2/images/notebookSmall.png
/usr/share/nixnote2/images/notebook_old.png
/usr/share/nixnote2/images/numberList.png
/usr/share/nixnote2/images/outdent.png
/usr/share/nixnote2/images/password.png
/usr/share/nixnote2/images/paste.png
/usr/share/nixnote2/images/printer.png
/usr/share/nixnote2/images/public-notebook.png
/usr/share/nixnote2/images/purple-theme
/usr/share/nixnote2/images/purple-theme/home.png
/usr/share/nixnote2/images/purple-theme/left_arrow.png
/usr/share/nixnote2/images/purple-theme/notebook.png
/usr/share/nixnote2/images/purple-theme/purpleThemeInfo.html
/usr/share/nixnote2/images/purple-theme/right_arrow.png
/usr/share/nixnote2/images/purple-theme/stack-purple.png
/usr/share/nixnote2/images/purple-theme/synchronize.png
/usr/share/nixnote2/images/purple-theme/windowIcon1.png
/usr/share/nixnote2/images/purple-theme/windowIcon2.png
/usr/share/nixnote2/images/purple-theme/windowIcon3.png
/usr/share/nixnote2/images/purple-theme/windowIcon4.png
/usr/share/nixnote2/images/purple-theme/windowIcon5.png
/usr/share/nixnote2/images/redo.png
/usr/share/nixnote2/images/right_arrow.png
/usr/share/nixnote2/images/screenCapture.png
/usr/share/nixnote2/images/silhouette.png
/usr/share/nixnote2/images/spellCheck.png
/usr/share/nixnote2/images/splash_logo.png
/usr/share/nixnote2/images/stack.png
/usr/share/nixnote2/images/strikethrough.png
/usr/share/nixnote2/images/subscript.png
/usr/share/nixnote2/images/superscript.png
/usr/share/nixnote2/images/synchronize.png
/usr/share/nixnote2/images/tag.png
/usr/share/nixnote2/images/themeInfo.html
/usr/share/nixnote2/images/todo.png
/usr/share/nixnote2/images/trash.png
/usr/share/nixnote2/images/trayicon.png
/usr/share/nixnote2/images/tree-down.png
/usr/share/nixnote2/images/trunk.png
/usr/share/nixnote2/images/underline.png
/usr/share/nixnote2/images/undo.png
/usr/share/nixnote2/images/up_arrow_small.png
/usr/share/nixnote2/images/usage.png
/usr/share/nixnote2/images/webcam.png
/usr/share/nixnote2/images/windowIcon.png
/usr/share/nixnote2/install.txt
/usr/share/nixnote2/java
/usr/share/nixnote2/java/.classpath
/usr/share/nixnote2/java/.project
/usr/share/nixnote2/java/crypto.jar
/usr/share/nixnote2/java/src
/usr/share/nixnote2/java/src/cx
/usr/share/nixnote2/java/src/cx/fbn
/usr/share/nixnote2/java/src/cx/fbn/encrypt
/usr/share/nixnote2/java/src/cx/fbn/encrypt/Base64.java
/usr/share/nixnote2/java/src/cx/fbn/encrypt/Crypto.java
/usr/share/nixnote2/java/src/cx/fbn/encrypt/EnCrypt.java
/usr/share/nixnote2/license.html
/usr/share/nixnote2/qss
/usr/share/nixnote2/qss/editor.css
/usr/share/nixnote2/shortcuts.txt
/usr/share/nixnote2/spell
/usr/share/nixnote2/theme.ini
/usr/share/nixnote2/translations
/usr/share/nixnote2/translations/README
/usr/share/nixnote2/translations/nixnote2_ca.qm
/usr/share/nixnote2/translations/nixnote2_ca.ts
/usr/share/nixnote2/translations/nixnote2_cs_CZ.qm
/usr/share/nixnote2/translations/nixnote2_cs_CZ.ts
/usr/share/nixnote2/translations/nixnote2_da.qm
/usr/share/nixnote2/translations/nixnote2_da.ts
/usr/share/nixnote2/translations/nixnote2_de.qm
/usr/share/nixnote2/translations/nixnote2_de.ts
/usr/share/nixnote2/translations/nixnote2_es.qm
/usr/share/nixnote2/translations/nixnote2_es.ts
/usr/share/nixnote2/translations/nixnote2_fr.qm
/usr/share/nixnote2/translations/nixnote2_fr.ts
/usr/share/nixnote2/translations/nixnote2_ja.qm
/usr/share/nixnote2/translations/nixnote2_ja.ts
/usr/share/nixnote2/translations/nixnote2_pl.qm
/usr/share/nixnote2/translations/nixnote2_pl.ts
/usr/share/nixnote2/translations/nixnote2_pt.qm
/usr/share/nixnote2/translations/nixnote2_pt.ts
/usr/share/nixnote2/translations/nixnote2_ru.qm
/usr/share/nixnote2/translations/nixnote2_ru.ts
/usr/share/nixnote2/translations/nixnote2_sk.qm
/usr/share/nixnote2/translations/nixnote2_sk.ts
/usr/share/nixnote2/translations/nixnote2_zh_CN.qm
/usr/share/nixnote2/translations/nixnote2_zh_CN.ts
/usr/share/nixnote2/translations/nixnote2_zh_TW.qm
/usr/share/nixnote2/translations/nixnote2_zh_TW.ts

**Comment by baumgarr** [comment]
I can't recreate this on my fedora 23 instance.  I guess fall back to beta 5 for now.   It looks like it is failing trying to initialize the shared memory segment.

**Comment by jeffbuhrt** [comment]
Thanks Randy!

1) I can run NN2 beta 6 after a reboot.
Your thought it can't create a shared memory segment...
Maybe some shared memory resource wasn't cleaned up from Beta5. A reboot and it runs now.

I tried uninstalled beta6, reinstalled beta5, ran beta5, exited beta5, uninstalled b5, reinstalled b6, but the problem would not repeat. I tried to repeat with and without a .nixnote directory. I say ignore it as a fluke and if anyone on beta5 goes to beta6 sees it.. just reboot.

2) rpm still returns what appears to be the script itself vs what I assume was to be replaced by output from the script. The CFLAGS, CXXFLAGS, etc I pasted above occurs both on beta5 and beta6. [I just confirmed during my reinstall testing.]

**Comment by baumgarr** [comment]
I'm not very familiar with RPMs, so I'm not understanding what your issue is with the CFLAGS & such.

The problem with the beta-5 and earlier RPMs was that I didn't have things listed in the %files section, but instead had a post-uninstall command to delete the files it installed.  This worked until you did an upgrade because for an upgrade the RPM runs the post-uninstall of the old RPM after running the install of the new RPM.  So it was installing the new RPM and then deleting everything it just installed.

I changed the RPM to have the %files properly and removed the post-uninstall.  That is why the un-install is still needed prior to beta-6.  The existing beta-5 already has the post-uninstall and nothing I do in the beta-6 will fix it.

**Comment by jeffbuhrt** [comment]
Randy do you mean you don't understand where it came from or why seeing the exports and commands themself is a problem?

Running: 
'rpm -qal nixnote2' and 'rpm -qa nixnote2' are fine. 'rpm -qi nixnote2' shows the normal header and the command string itself (vs what I assume should be the output from the command).

**Comment by baumgarr** [comment]
Thanks for clarifying.  I was thinking it had issues installing, but it was the display that was an issue.  I fixed it and it should work properly on the next beta.

**Comment by jeffbuhrt** [comment]
Great Randy. 

I should have split the rpm text from the original ticket once we fix the failure to run.

**Comment by jeffbuhrt** [comment]
Updating to Beta7 was clean on Fedora 23 86_64. Also rpm -qi output is good new.
