### ISSUE TITLE
EDAMNotFoundException

### ISSUE THREAD

**Issue by vitaly-zdanevich** [baumgarr/nixnote2#116]
beta 6

And I don't know - all my notes synced or not...

ERROR 2015-12-12 22:34:51.283 ( communication/communicationmanager.cpp @ 1182 ) EDAMNotFoundException: 

 INFO 2015-12-12 22:34:51.286 ( nixnote.cpp @ 1775 ) "EDAMNotFoundException: Note not found:EDAMNotFoundException:  identifier=Note.notebookGuid key=8c552ef2-8dfc-4a5e-a754-73b6ef3fdabe" 
 INFO 2015-12-12 22:34:51.287 ( nixnote.cpp @ 1775 ) "EDAMNotFoundException: Note not found:EDAMNotFoundException:  identifier=Note.notebookGuid key=8c552ef2-8dfc-4a5e-a754-73b6ef3fdabe"

**Comment by baumgarr** [comment]
It is saying that whatever notebook you are syncing doesn't exist.

**Comment by vitaly-zdanevich** [comment]
doesn't exist in Evernote but exist in Nixnote? how can I found this problem notebook?

**Comment by baumgarr** [comment]
Look for any notes that are not synchronized and see what notebook they belong to.  Is it a shared notebook?  If so, do you have permissions to it?  You can tell if a note is synchronized by looking for the dot in the sync column.  If it has a dot it is not synchronized.

**Comment by vitaly-zdanevich** [comment]
I found few notes that not synced, but this notebook pretty old and exist everywhere...

**Comment by vitaly-zdanevich** [comment]
Aha, I found that my new note created under notebook `My Notebook` - but I don't have this notebook, I think this is bug

**Comment by baumgarr** [comment]
Weird.  it should create that notebook when you first start it, just because it needs a default.  Glad you found the problem.
