### ISSUE TITLE
encoding problem: instead of russian I see ?????? ??? at terminal after nixnote2 query --search="php"

### ISSUE THREAD

**Issue by vitaly-zdanevich** [baumgarr/nixnote2#117]
beta 6
I see:

5541   |SaluteMotors   |deleted homeanonses from file anonses1.php|                    |12/03/13 09:53:30   
5617   |SaluteMotors   |???? ????? ?????????? ????? ?? 250 000 Br ????????? ???????:|                    |12/25/13 11:48:47

**Comment by baumgarr** [comment]
Should be fixed in the next release.
