### ISSUE TITLE
dark theme: enabled, created note, synced - at Android I 'see' white text on white background

### ISSUE THREAD

**Issue by vitaly-zdanevich** [baumgarr/nixnote2#119]

**Comment by baumgarr** [comment]
I can't recreate this.

About the only way I can think that would happen is if you set the text color to white in NixNote using the color selection.  If you did that, the color is manually set and it will sync with that color.  The theme itself isn't synchronized so you end up with white text on a white background.

**Comment by vitaly-zdanevich** [comment]
tested again - working correct... but in first time I not changed any font color...

**Comment by baumgarr** [comment]
Cool.  Glad it is working.
