### ISSUE TITLE
Too small UI fonts in Ubuntu

### ISSUE THREAD

**Issue by Qazzy** [baumgarr/Nixnote2#12]
I can not say about another Linux distribution, but in Ubuntu 14.04 I have too small UI fonts. 

If I use qt4-config that does not help they stay the same

**Comment by aiguofer** [comment]
Hey, just wondering what the status is on this? I haven't seen any commits for this but looking at the code it seems fairly straightforward to implement. If no one has started work on this I'd love to take this up.

**Comment by baumgarr** [comment]
I have it partially working to allow the font size to be increased in a few places, but not everywhere.  I'll try to get the remainder done for the next beta.

**Comment by baumgarr** [comment]
Fonts can be changed via the preferences menu.  Closing issue.
