### ISSUE TITLE
sync failed

### ISSUE THREAD

**Issue by llorch-zh** [baumgarr/nixnote2#120]
```Unable to update note. Invalid note structure : : EDAMUserException: ENML_VALIDATITION parameter=Attribute "id" must be declared for element  type "div" ```  

ps: I'm a heavy user of evernote. I have pulled down 821 notes from cloud , and add 63 new notes to upload.

**Comment by llorch-zh** [comment]
I rewrite the new 63 notes with html source code . It works after all.

**Comment by baumgarr** [comment]
Glad you got it to work.  The next release should take care of those automatically.
