### ISSUE TITLE
dump of SQLite with all my notes is possible?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [baumgarr/nixnote2#121]
I know that now not possible to make db export from terminal, but maybe possible to dump SQLite with all my content?

**Comment by baumgarr** [comment]
Yes and no.

I'm assuming there is a utility that will backup the sqlite database via a command line, but I don't know what it is off the top of my head.  That will give you everything except the attachments & images.  Those are stored as regular files and are not in the sqlite database for performance reasons.

**Comment by vitaly-zdanevich** [comment]
Where can I find SQLite file and folder with attachments?

**Comment by baumgarr** [comment]
You can find it in ~/.nixnote/db-*

You can find more information on how it works by looking at the Help/Users Manual.
