### ISSUE TITLE
command line syntaxis

### ISSUE THREAD

**Issue by vitaly-zdanevich** [baumgarr/nixnote2#127]
now at nixnote2 beta 7
`nixnote2 addNote --notebook="My Stuff" --title="My New Note" --tag="Tag1" --tag="Tag2" --noteText="My Note Text"`

at `geeknote`:
`geeknote create --title <title>
                  --content <content>
                  [--tags <list of tags>]
                  [--notebook <notebook where to save>]`

What you think about coping syntaxis from `geeknote`? Geeknote is popular and good, why users need to remember different commands? [At GitHub Geeknote](https://github.com/VitaliyRodnenko/geeknote) have **1401** stars, when Nixnote2 have **136** stars. Now even Firefox marge api for addons with Chrome.

You can see the documentation for Geeknote here http://www.geeknote.me/documentation/#creating-notes

**Comment by baumgarr** [comment]
Right now that isn't something I plan to do.  Partly because of time constraints and partly because I think it would become a never ending task of keeping in sync with Geeknote any time they made a change.
