### ISSUE TITLE
fast search of target notebook when writing new note

### ISSUE THREAD

**Issue by vitaly-zdanevich** [baumgarr/nixnote2#130]
at web ui we have fast search of notebook, and it is good - for example I have ~40 notebooks so quick search must have. I hope NixNote will have fast notebook search in the dropdown or maybe at the left sidebar.
![web-ui](https://cloud.githubusercontent.com/assets/3514015/12006248/c85fcffe-abdf-11e5-8f19-8bfbfd587001.png)

**Comment by baumgarr** [comment]
Right now there are not any planned GUI changes. Maybe after the actual 2.0 release, but right now it is something I don't want to mess with because of the risk of introducing more bugs.
