### ISSUE TITLE
columns Updated and Created

### ISSUE THREAD

**Issue by vitaly-zdanevich** [baumgarr/nixnote2#135]
![created-updated](https://cloud.githubusercontent.com/assets/3514015/12011365/72db62b2-acdb-11e5-8bae-83fef11573db.png)

Maybe it is possible to optimize the elements on the screen? For example why we need to see the exact seconds of creation date at the list screen - this information is available inside note. Also as you see at screenshot - width of the column not enough for title `Date Created` - maybe just `Created` will be enough?

**Comment by baumgarr** [comment]
Right now there isn't a way to customize the column titles.

You can customize the way dates & times are displayed under the Preferences dialog under the Locale tab, but that is application wide.
