### ISSUE TITLE
sync ico rotation looks incorrect on dark gtk

### ISSUE THREAD

**Issue by vitaly-zdanevich** [baumgarr/nixnote2#137]
![sync](https://cloud.githubusercontent.com/assets/3514015/12011547/f2741bac-ace2-11e5-813a-d6155fc5bc5c.png)

**Comment by baumgarr** [comment]
This issue exists on the default background too but it isn't as noticeable.  The reason for this is the way it is rotating the default icon and the fact I can't easily get the background color of the toolbar.  Unfortunately there isn't anything I've been able to find that easily corrects this.
