### ISSUE TITLE
calendar view

### ISSUE THREAD

**Issue by vitaly-zdanevich** [baumgarr/nixnote2#138]
What you think about calendar view? Many users need calendar inside Evernote, I do too. Evernote is like organiser and every organising system must have calendar. Evernote already have reminders - user can set many reminders but can not see all reminders in calendar. On internet we can find few services that can show events from Evernote in calendar, for example [Sunrise](http://sunrise.am), but it is separate service and we can not edit content of note.

Few week ago I start writing [my own calendar for Web version](https://github.com/vitaly-zdanevich/evernote-calendar) - as a userscript and it already works, there is only few things remains to implement.

![screenshot 2015-12-28 at 3 53 10 am](https://cloud.githubusercontent.com/assets/3514015/12012806/8ef0d816-ad16-11e5-957a-f513f62026b4.png)

**Comment by baumgarr** [comment]
It isn't a bad idea and maybe I'll add it in the future, but right now I don't want to add anything this complex because it would add more bugs.  I'm trying to keep changes to a minimum so I can do an actual 2.0 release.
