### ISSUE TITLE
preferences screen: incorrect window size when opening

### ISSUE THREAD

**Issue by vitaly-zdanevich** [baumgarr/nixnote2#141]
![preferences-size](https://cloud.githubusercontent.com/assets/3514015/12023603/1c7a6112-adac-11e5-87a2-99d3bbc258a0.png)

**Comment by baumgarr** [comment]
Yes.  I had to add scroll bars because on smaller screen sizes the dialog had gotten large enough to not be able to see all of the buttons and/or options.

**Comment by fastcat** [comment]
But if the screen has plenty of space, why can't it open at the proper size, or at lest the proper width?
