### ISSUE TITLE
Problem when you search notes with non-English language

### ISSUE THREAD

**Issue by alex-theoto** [baumgarr/nixnote2#143]
Hello.
I hope this section is for bug report too...

When you make a note with non-English and lowercase letters, you can find them from search bar.
But when notes are with capital letters, you cannot find them.
In my case, the language is Greek.

Any idea how to fix this problem?
Thank you...

**Comment by baumgarr** [comment]
Try doing a search with a * in front & behind the word.  Like *cake*.  That triggers slightly different search logic.  I'm not sure if it helps, but it may.

**Comment by alex-theoto** [comment]
No, * doesn't help.
I tested other languages and didn't see this problem. I don't get it...

**Comment by baumgarr** [comment]
I did a search for this and it looks like it is a known thing with SQLite and some languages.  It looks like it is related to the way the SQLite or its driver is built.  I'm not sure there is anything much I can do to fix it but I'll give it some thought.  Sorry.

**Comment by alex-theoto** [comment]
Thank you very much for your research...

**Comment by baumgarr** [comment]
Can you give me an example of 3 sentences in Greek?  One in upper case, one in lower case, and one in mixed case.  I have an idea, but I need to test it with something first.

Thanks.

**Comment by alex-theoto** [comment]
ΑΥΤΟ ΕΙΝΑΙ ΕΝΑ ΑΥΤΟΚΙΝΗΤΟ
αυτο ειναι ενα αυτοκινητο
Αυτο ΕΙΝΑΙ ενα αυΤΟκιΝΗτο

With accent marks:
ΑΥΤΌ ΕΊΝΑΙ ΈΝΑ ΑΥΤΟΚΊΝΗΤΟ
αυτό είναι ένα αυτοκίνητο
Αυτό ΕΊΝΑΙ ένα αυΤΟκίΝΗτο

We usually use accent marks (') but it is not necessarily if the text is writen in upper case.

**Comment by baumgarr** [comment]
I think have a partial workaround.  It looks like it works for upper/lower case regardless if the note contains an accent mark, but if the note has an accent mark you can only search for it using an accent mark.  So ένα won't match ενα but είναι will match ΕΊΝΑΙ (I think).  

If you have the ability to build it from the source, the changes are on GitHub.  You can find instructions on building it from the source in the User Documentation under the Help menu.  To use it you need to go to "Edit/Preferences" and look under the "Search" tab.  Check the option "Experimental: force search to lower case".  

If you don't want to build it from source you'll have to wait for the next release (and I don't know when that will be).

There is a catch.  This only works on new or changed notes.  Existing notes will continue to have the problem.  If this fixes the issue then there are a couple of ways to re-index the entire database to correct the problem everywhere.  

Let me know if this helps or makes things worse.  

Thanks.

**Comment by alex-theoto** [comment]
Yes, when I use accent mark, the letter is different from the non-accent marked letter.

It worked. And strangely I can find the already written notes. Though I have only 6-7 notes for testing purpose.
Thanks.
But, just for the record, can you tell me how to re-index the entire database? Just in case...

Then you can close this issue.

**Comment by baumgarr** [comment]
Awesome.  It would have worked on notes that had lower-case and if you searched using upper-case, but I wouldn't have thought it would work the other way around.

There are two ways to re-index the entire database.

1.) Delete it and re-download everything.

2.) Start NixNote from the command line "nixnote2 --enableIndexing".  That will unlock an option under the Tools menu to re-index the entire database.  It will then go through every note again, so it is best to leave it alone for a while until it is done.  You can see if it is done by looking under the "Tools/Database Status" menu.  It is slow and I think it may have caused some database locks, so I disabled it by default.

Can I close this issue?

**Comment by alex-theoto** [comment]
I already deleted it and the config files. So that's why it worked fine.
Thank you, I'll close it...
