### ISSUE TITLE
please provide more descriptive text of errors to allow the user to understand what can be corrected

### ISSUE THREAD

**Issue by vitaly-zdanevich** [baumgarr/nixnote2#144]
![screenshot - 01042016 - 09 38 55 pm](https://cloud.githubusercontent.com/assets/3514015/12097246/a0efe000-b32b-11e5-9a62-7ee8dfbe3fe2.png)

**Comment by baumgarr** [comment]
There isn't much I can do.  Evernote generates those error messages, not NixNote.
