### ISSUE TITLE
Launchpad Daily Builds Failing

### ISSUE THREAD

**Issue by rsyring** [baumgarr/nixnote2#153]
Some Launchpad daily builds are failing.  

https://launchpad.net/~nixnote/+archive/ubuntu/nixnote2-daily

**Comment by artmg** [comment]
The Launchpad daily builds come from a packaging project, currently hosted at [https://github.com/artmg/nixnote2-packaging] - **please raise any [package related issues there](https://github.com/artmg/nixnote2-packaging/issues)** - Thanks

_PS: I think these failures have now passed_

**Comment by baumgarr** [comment]
Closing as the packaging is not part of this repository.
