### ISSUE TITLE
Non-daily Ubuntu PPA

### ISSUE THREAD

**Issue by rsyring** [baumgarr/nixnote2#154]
Do you have any interest in providing a non-daily PPA that would contain official releases only?  I'd like to get updates, but don't like nightly builds due to the instability.  I'm assuming if there was a PPA for the official beta releases, it would be more stable.

**Comment by artmg** [comment]
In theory the nixnote2-daily PPA is the first step towards a nixnote2-stable PPA. You can find the **existing feature enhancement to add a stable PPA** at [https://github.com/artmg/nixnote2-packaging/issues/2]. Currently the biggest obstacle to getting this working is finding people with (any) debian packaging skills who can share just a little of their time and experience to help the project. If you know any, then please _do_ point them in this direction, where they will be most welcome. Thanks

**Comment by kmf** [comment]
+1

**Comment by vitaly-zdanevich** [comment]
+1

**Comment by romansavrulin** [comment]
+1

**Comment by baumgarr** [comment]
You can open a request at the link provided by artmg above, but the ppa builds are not part of this repository and I don't control them.  Sorry.
