### ISSUE TITLE
Move away from SourceForge

### ISSUE THREAD

**Issue by rsyring** [baumgarr/nixnote2#155]
I initially avoided this project due to it's being on SourceForge and my hesitancy to download or trust anything from them.

I think it might help the project to have the website and download files hosted elsewhere.  Any thoughts regarding this?

**Comment by vitaly-zdanevich** [comment]
+1

**Comment by kmf** [comment]
+1

**Comment by romansavrulin** [comment]
+1

**Comment by hadim** [comment]
+1

**Comment by baumgarr** [comment]
When NixNote2 is out of beta I'll look into it, but right now I don't have the time and people still ask questions about the old NixNote.  It is confusing enough with two places but adding a third would be painful.

If you are hesitant about downloading anything you can always download the source & build it manually.  There are instructions in the help doc.
