### ISSUE TITLE
Notes deleted on Evernote won't delete in Nixnote2

### ISSUE THREAD

**Issue by fernandogutie** [baumgarr/nixnote2#156]
I just installed beta 7 on Ubuntu 14.04 and synced everything. Almost everything is working fine, but when I delete a note in Evernote web, that deletion doesn't sync into Nixnote2. I have tried several times and those notes get moved to a 'Conflict' notebook. I'm not sure I had that notebook before, but I see it empty in Evernote web, so maybe I did.

Nixnote2 deletions sync to Evernote perfectly. Btw, is there a way to see the deleted notes in Nixnote2?

**Comment by baumgarr** [comment]
The only way you should get a conflict is if a note was edited locally and on Evernote.  If that happens the sync won't know which one is correct, so it will move the local one to a conflict notebook.

You can view deletions by clicking on the "Trash" icon on the left hand side.

One thing is different with deletions.  When you delete a note in NixNote, you cannot permanently delete it in Evernote.  It always remains in the Trash on their clients until you empy it within the web interface or another of Evernote's clients.  That is their restriction to prevent third-party clients from accidentally deleting data.

**Comment by baumgarr** [comment]
No response. Closing.
