### ISSUE TITLE
Api rate limit exceeded

### ISSUE THREAD

**Issue by romansavrulin** [baumgarr/nixnote2#157]
When I sync my quite big account with nixnote2 i sometimes get the following exceptions.

INFO 2016-02-18 22:32:04.230 ( nixnote.cpp @ 1810 ) "Download 4% complete." 
 INFO 2016-02-18 22:35:45.751 ( nixnote.cpp @ 1810 ) "Download 4% complete." 
ERROR 2016-02-18 22:38:47.248 ( communication/communicationmanager.cpp @ 294 ) EDAMSystemException 
ERROR 2016-02-18 22:38:47.250 ( communication/communicationmanager.cpp @ 1149 ) EDAMSystemException Error Code: 19 

ERROR 2016-02-18 22:38:47.250 ( communication/communicationmanager.cpp @ 1151 ) EDAMSystemException Rate Limit: 1368 

ERROR 2016-02-18 22:38:47.250 ( threads/syncrunner.cpp @ 257 ) Error retrieving chunk 
 INFO 2016-02-18 22:38:47.252 ( nixnote.cpp @ 1810 ) "API rate limit exceeded.  Please try again in 23 minutes." 
ERROR 2016-02-18 22:38:47.676 ( communication/communicationmanager.cpp @ 169 ) EDAMSystemException 
ERROR 2016-02-18 22:38:47.678 ( communication/communicationmanager.cpp @ 1149 ) EDAMSystemException Error Code: 19 

ERROR 2016-02-18 22:38:47.679 ( communication/communicationmanager.cpp @ 1151 ) EDAMSystemException Rate Limit: 1383 

 INFO 2016-02-18 22:38:47.679 ( nixnote.cpp @ 1810 ) "API rate limit exceeded.  Please try again in 24 minutes."

**Comment by baumgarr** [comment]
The API rate limit is controlled by Evernote.  When you first authorize a client the rate is high for a day or so, but then it drops down.  There isn't anything I can do about that.
