### ISSUE TITLE
Sync index (headers + metadata), then the content

### ISSUE THREAD

**Issue by romansavrulin** [baumgarr/nixnote2#158]
I have a premium account of evernote, and it contains about 3k of notes, some of them can include PDFs or other files. It is usually very painful to sync my account with any fresh client installation, but nixnote sync process is the slowest.

Is it possible to sync only headers of notes (and metadata) for the first time, and continue to download contents in background?

**Comment by baumgarr** [comment]
No.  You can turn off PDF local indexing which can speed up syncs a little, but it also means you won't be able to search them until a note has been synchronized, processed by Evernote, and then re-synchronized.  After doing an initial sync you could turn it back on.  I don't know how much of a difference this will make with the speed of the sync but it should help a little.
