### ISSUE TITLE
Can't add tags to notes when built against QT5

### ISSUE THREAD

**Issue by fastcat** [baumgarr/nixnote2#161]
Working with a locally built binary from current git head (a834508b4672e762c7e8e5505f918aeeaa1292f5), the UI to add tags from the note editor shows the tags, but they don't get added to the note in the grid, and if I switch notes they disappear, and sync confirms they were not added.

Running a bisect to try to find when this broke...

**Comment by fastcat** [comment]
Bisect went all the way back to the introduction of QT5 support, so now I'm theorizing this is a problem with QT5 vs QT4 and retrying the git head with QT4.

With git head and building against QT4 (which sadly does not play nearly so nice on my HiDPI display), this problem mostly goes away.  The tag adds are retained, though the table doesn't update until I change the _note filter_ (e.g. click a different notebook or tag in the sidebar) -- switching notes is not enough.  I tried this switch filters with the QT5 build, and the result was that the tags were lost in the edit view too.

**Comment by WiseTrem** [comment]
Have the same. Is there any progress?

**Comment by baumgarr** [comment]
No, not yet. I don't yet support Qt-5 myself. Someone else was doing that port. My best recommendation is to build it with Qt-4 until I have time to look into this issue.

**Comment by fastcat** [comment]
@michaelcadilhac -- any chance you could take a look at this, since I think you did most of the original QT5 port?  While QT4 is OK on my "normal" desktop, QT5 is vastly superior on retina laptop screens :)

**Comment by baumgarr** [comment]
This is fixed in the latest updates.
