### ISSUE TITLE
sync icon background is not transparent

### ISSUE THREAD

**Issue by jeffkowalski** [baumgarr/nixnote2#162]
In the toolbar, the ```sync``` icon has a different, lighter, background than the other items.
This is only true while the sync is active (spinning).  It's fine when not spinning.
![screenshot from 2016-03-05 14 02 03](https://cloud.githubusercontent.com/assets/56880/13550817/124d99e8-e2db-11e5-8925-fefefe536a43.png)

**Comment by baumgarr** [comment]
This is a known issue and I haven't found any way around it. The problem is that the background color of the toolbar isn't available (or I can't find how to get it). As a result the background of the sync icon is the background color of the area behind the toolbar.
