### ISSUE TITLE
When a note fails to sync, the error does not specify which note failed to sync and the warning is easy to ignore

### ISSUE THREAD

**Issue by JPvRiel** [baumgarr/nixnote2#163]
When sync problems occur, two improvements in usability are suggested:
1. Instead of briefly flashing the note sync error message in the bottom status bar, have a more salient warning dialog.
2. Immediately make the user aware of which note or notes are not synching.

The normal >= Info level logging does not specifically identify the problematic note(s). It would be immediately useful and helpful if it did. This happens often enough (e.g. when cutting and pasting web/html content into nixnote) that having to switch to debug level logging to see the note in question is a bit of extra effort.

NixNote2 Beta 7 default message log (Info level)

```
INFO 2016-03-13 11:51:35.118 ( nixnote.cpp @ 1810 ) "Beginning Sync" 
ERROR 2016-03-13 11:51:37.401 ( communication/communicationmanager.cpp @ 548 ) EDAMUserException: 11 
 INFO 2016-03-13 11:51:37.402 ( nixnote.cpp @ 1810 ) "Unable to update note.  Invalid note structure : :EDAMUserException: ENML_VALIDATION parameter=Attribute "class" must be declared for element type "span"." 
 INFO 2016-03-13 11:51:37.402 ( nixnote.cpp @ 1810 ) "Unable to update note.  Invalid note structure : :EDAMUserException: ENML_VALIDATION parameter=Attribute "class" must be declared for element type "span"." 
```

As per the above, no clue which note is the problematic note.

Many other users have bumped into note sync conflicts, so it's fairly common. [Search for "EDAMUserException: 11"](https://github.com/baumgarr/nixnote2/issues?utf8=%E2%9C%93&q=is%3Aissue+%22EDAMUserException%3A+11%22)

**Comment by MetaMemoryT** [comment]
:+1:

see my comments here: https://github.com/baumgarr/nixnote2/issues/160

**Comment by baumgarr** [comment]
I'll add it to the list of enhancements, but right now the best thing to do is to look for any any notes which have a dot in the unsynchronized column.

**Comment by sunjam** [comment]
` nixnote.cpp @ 1810`
Is 1810 the number of the note in the database?

**Comment by baumgarr** [comment]
No, that is the line of the program that is reporting it. If you look in the debug log it should have a dump of the note that had an issue.  I've also just added an error message that should show the note title regardless of the message level.

**Comment by baumgarr** [comment]
There is now an option for a popup message. It is enabled by default, but you can enable it under the Preferences Sync tab.
