### ISSUE TITLE
Allow non-GUI operations to run without an X server

### ISSUE THREAD

**Issue by justyn** [baumgarr/nixnote2#164]
Nixnote2 has a handy command-line interface that can operate entirely without the GUI.
This is particularly useful for creating backups.

However trying to run even "nixnote2 --help" on a headless server (no X server) leads to this error:
nixnote2: cannot connect to X server

It is possible to run using Xvfw, for example:
Xvfb :1 -screen 0 800x600x16
export DISPLAY=:1.0
nixnote2 --help

However this is not ideal - in particular the sync command seems to work but then hang, making scripting backups difficult.

It would be great if non-GUI operations wouldn't try to connect to an X server.

Thanks for the great software.

**Comment by baumgarr** [comment]
This probably won't be done any time soon. In order to do this I'd need to setup a totally separate binary because the Qt libraries are expecting a window manager. I'll add it to the enhancements queue, but it probably won't happen any time soon.

**Comment by hosiet** [comment]
It would be great if we just split all the CLI features into a new separate binary executable. A new cli tool could greatly simplify the argument parsing of original `nixnote2` tool. This tool may not depend on X.

**Comment by baumgarr** [comment]
I think I have it working in the next beta where X won't be needed for non-GUI operations. It is still the same binary but it doesn't call the GUI libraries unless needed.
