### ISSUE TITLE
Error while loading shared libraries: libopencv_core.so.2.4

### ISSUE THREAD

**Issue by Logmytech** [baumgarr/nixnote2#165]
Whenever I run nixnote2 I get the following error.

`nixnote2: error while loading shared libraries: libopencv_core.so.2.4: cannot open shared object file: No such file or directory
`
No window is running or launched.

**Comment by Tonus1** [comment]
You might have another libopencv version installed. I had the same problem, regretting that the program asks for a specific version... 



Le 26 avr. 2016 18:51, à 18:51, Logmytech <notifications@github.com> a écrit:

**Comment by vmatyushin** [comment]
I have the same issue.
Also, when trying to build, I get:
```
release/webcamcapturedialog.o: In function `WebcamCaptureDialog::WebcamCaptureDialog(QWidget*)':
/tmp/yaourt/aur-nixnote2-git/src/build/../nixnote2/dialog/webcamcapturedialog.cpp:46: undefined reference to `cv::VideoCapture::VideoCapture(int)'
/tmp/yaourt/aur-nixnote2-git/src/build/../nixnote2/dialog/webcamcapturedialog.cpp:47: undefined reference to `cv::VideoCapture::isOpened() const'
```
I am using Arch Linux and have opencv 3.1.0-3 installed.

**Comment by baumgarr** [comment]
I'm working on making the webcam a plugin module, so if there is an opencv compatibility issue you can just remove the plugin and continue without that ability. It isn't a perfect solution but it is about the only thing I can come up with that works.

**Comment by baumgarr** [comment]
I think I have this moved as a plugin, so this should be fixed in the next release.

**Comment by michaldybczak** [comment]
Also have this bug. Can't wait till it's fixed. Nixnote2 is the best (and the only one really working) client for evernote.

**Comment by mani-zaeim** [comment]
I am using archlinux and opencv-3.1.0-3 , can not run nixnote and try nixnote-beta which is nixnote2 but get the same error!
any suggestion for resolving this issue ?
how about creating the softlink as it suggested on the link below:
[https://sourceforge.net/p/nevernote/bugs/254/](https://sourceforge.net/p/nevernote/bugs/254/)

**Comment by kaenan** [comment]
@mani-zaeim Creating softlinks works. Thanks!

- sudo ln -s /usr/lib/libhunspell-1.4.so /usr/lib/libhunspell-1.3.so.0
- sudo ln -s /usr/lib/libopencv_core.so /usr/lib/**libopencv_core.so.2.4**
- sudo ln -s /usr/lib/libopencv_highgui.so /usr/lib/libopencv_highgui.so.2.4
- sudo ln -s /usr/lib/libopencv_imgproc.so /usr/lib/libopencv_imgproc.so.2.4

One line command:
`sudo ln -s /usr/lib/libhunspell-1.4.so /usr/lib/libhunspell-1.3.so.0; sudo ln -s /usr/lib/libopencv_core.so /usr/lib/libopencv_core.so.2.4; sudo ln -s /usr/lib/libopencv_highgui.so /usr/lib/libopencv_highgui.so.2.4; sudo ln -s /usr/lib/libopencv_imgproc.so /usr/lib/libopencv_imgproc.so.2.4`

**Comment by iegrsy** [comment]
https://drive.google.com/open?id=1j5qC1izhLVbHFpw-KkVRXNca8ASV1km5 
Download this file.
Copy the contents into /usr/lib/x86_64-linux-gnu/
That is all.

**Comment by xianweilv** [comment]
> https://drive.google.com/open?id=1j5qC1izhLVbHFpw-KkVRXNca8ASV1km5
> Download this file.
> Copy the contents into /usr/lib/x86_64-linux-gnu/
> That is all.

It works for me. Thanks very much!

**Comment by robert7** [comment]
OK. or just use the newer updated version where you don't need it at all.. https://github.com/robert7/nixnote2

**Comment by michaldybczak** [comment]
Ah, totally forgot about this issue. Nixnote2 works fine for a long time on Manjaro (installed from AUR). It's been 3 years so I'm surprised that someone still has that problem.

**Comment by edwardnguyen1705** [comment]
Hi @xianweilv ,
Could you upload all the *.so.* files to googledrive? Thank you so much.

**Comment by robert7** [comment]
@edwardnguyen1705 you can also switch to v2.1 and you will not need the library..
