### ISSUE TITLE
Adjusting install.sh in order to install from custom build?

### ISSUE THREAD

**Issue by cehberlin** [baumgarr/nixnote2#169]
Hi,
I am not sure how it is intended to use the install.sh if you build from source. The problem is that the specified directories are not existing. I have changed the script in the following fashion in order to directly install from my own build. I am not sure, if I just missed something or if this would be a useful contribution. If it is not the right way of installing from source, it would be useful to have a documentation for the correct process.

```bash
#!/bin/sh

package_dir=$(cd `dirname $0` && pwd)

echo $package_dir

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

cp $package_dir/nixnote2.desktop /usr/share/applications/nixnote2.desktop
mkdir -p /usr/share/nixnote2
cp -r \
 $package_dir/certs \
 $package_dir/help \
 $package_dir/images \
 $package_dir/java \
 $package_dir/qss \
 $package_dir/translations \
 /usr/share/nixnote2/
cp \
 $package_dir/changelog.txt \
 $package_dir/license.html \
 $package_dir/shortcuts.txt \
 /usr/share/nixnote2/

cp $package_dir/nixnote2 /usr/bin/nixnote2

echo "Install complete"
```

**Comment by baumgarr** [comment]
The install.sh is meant to be used after the packages are built and included in the tar file. Run the ./package_scripts/build.sh to build a tar file. That tar file will contain include an install.sh with the proper directories built.

**Comment by baumgarr** [comment]
No response. Closing issue.
