### ISSUE TITLE
Issue installing on Ubuntu 16.04

### ISSUE THREAD

**Issue by kmf** [baumgarr/nixnote2#170]
`dpkg: dependency problems prevent configuration of nixnote2:
 nixnote2 depends on libpoppler28 | libpoppler43 | libpoppler44 | libpoppler46 | libpoppler49 | libpoppler52; however:
  Package libpoppler28 is not installed.
  Package libpoppler43 is not installed.
  Package libpoppler44 is not installed.
  Package libpoppler46 is not installed.
  Package libpoppler49 is not installed.
  Package libpoppler52 is not installed.
`

Any ideas?

**Comment by whopkins42** [comment]
I'm having the same problem on Kubuntu 16.04. libpoppler isn't installed, and isn't available to install with apt-get.

**Comment by aproposnix** [comment]
I think I saw somewhere that the developer has been very busy lately. To install on Ubuntu 16.04 use the tar ball until the new debs are created. That's what I did and it worked.

**Comment by whopkins42** [comment]
There's a bug filed over at sourceforge: https://sourceforge.net/p/nevernote/bugs/251/, with some links to possible solutions.

**Comment by maxadamo** [comment]
how are you trying to install? Are you installing the deb packages yourself, or are you using the PPA? 
The following ppa should work without problems: 
https://launchpad.net/~nixnote/+archive/ubuntu/nixnote2-daily

**Comment by baumgarr** [comment]
I'm running Kubuntu and the latest deb installs fine. I'm going to close this issue but if it is still a problem let me know.
