### ISSUE TITLE
Sync issues with notes containing code

### ISSUE THREAD

**Issue by Dave-Vallance** [baumgarr/nixnote2#171]
I often see issues when trying to sync notes which contain code.... I can't quite put my finger on what is the exact cause as some notes sync fine. 

I receive the following message

` INFO 2016-06-03 08:43:36.519 ( nixnote.cpp @ 1790 ) "Unable to update note.  Invalid note structure : :EDAMUserException: ENML_VALIDATION parameter=Attribute "class" must be declared for element type "span"." 
`

**Some notes:**
- Usually the notes with an issue come from copying and pasting a section of a website.
- If I add notes with code from another source..ie from the evernote app on my phone, it seems to never have an issue. 

**Example**
[Libre Office Basic - Hello World tutorial](http://www.debugpoint.com/2014/09/writing-a-macro-in-libreoffice-calc-getting-started/) is an example of a page that had an issue. I opened the page, highlighted the sections I was interested in, then copied and pasted into the app. 

**Version**
Nix-Note 2 Beta 7

**Comment by baumgarr** [comment]
I think I have this fixed in the next release. It should remove any "class" attributes in a span element.

If it is still an issue after the next beta please let me know.
Thanks.
