### ISSUE TITLE
Tray issue

### ISSUE THREAD

**Issue by GlebWork** [baumgarr/nixnote2#177]
If **minimize to tray** is unchecked and **close to tray** is checked, then on close it doesn't go tray

While both actions on **click** and **middle click** set to Show/Hide NixNote - neither of them actually work in that way. Left and Right Click call menu, where I can select Show/Hide. This option works from time to time.

Ubuntu 14.04.4 x64

**Comment by baumgarr** [comment]
I think I have it fixed. Let me know if it doesn't behave properly for you in the next beta.

**Comment by GlebWork** [comment]
Thank you! I will check that when new beta is ready
