### ISSUE TITLE
Issues about nixnote2.desktop

### ISSUE THREAD

**Issue by hosiet** [baumgarr/nixnote2#178]
I noticed one line like this:
> MimeType=x-scheme-handler/evernote;

That looks strange. The man page says that `nixnote2` cannot handle URLs like `evernote://`. Plus I have never seen this kind of URL/URI anywhere.

Shall we just remove this line?

**Comment by baumgarr** [comment]
It seems to me that I didn't have that at one time and something complained about it during a deb or RPM install. 

Maybe I'm remembering incorrectly. It has been a long time.

**Comment by hosiet** [comment]
Closed via #179.
