### ISSUE TITLE
Exhancement: Notification and Auto-Resume after API Rate Limit Reached

### ISSUE THREAD

**Issue by sunjam** [baumgarr/nixnote2#180]
No notification is being displayed within Nixnote once the API Rate Limite is reached.

What about at a graphical notification of the Rate Limit being reached?  Also important, please consider adding a sync auto-resume option for when the API time limit expires.

[https://gist.github.com/sunjam/19d8ad971ba28714804b2a1a8e0e6f11](Example of how output is currently displayed when API Rate Limit Reached)

**Comment by baumgarr** [comment]
This should be in the next release, but it may be a little buggy.
