### ISSUE TITLE
Sync errors: Attribute "data-saferedirecturl" must be declared for element type "a"."

### ISSUE THREAD

**Issue by texpert** [baumgarr/nixnote2#181]
Hello!

Couldn't sync a note (using nixnote2-daily+20160718 on Ubuntu 16.04 x64 - previous builds didn't make it either).

Full error line is:

 INFO 2016-07-20 12:11:01.986 ( nixnote.cpp @ 1820 ) "Unable to update note.  Invalid note structure : :EDAMUserException: ENML_VALIDATION parameter=Attribute "data-saferedirecturl" must be declared for element type "a"."

**Comment by baumgarr** [comment]
This should be fixed in the next release. Thanks.
