### ISSUE TITLE
Webcamplugin isn`t loaded

### ISSUE THREAD

**Issue by vitaleon** [baumgarr/nixnote2#182]
Hi!
Webcamplugin is installed but not loaded by nixnote (latest version).
For general installation folder "plugins" is created in  _/usr/share/nixnote2_. But `pluginsDir` is initialized with _/usr/bin_ (line 3604 of nixnote.cpp : `QDir pluginsDir(qApp->applicationDirPath());` ).
Perhaps `QDir pluginsDir(global.getProgramDirPath());` was supposed.
Best regards!

**Comment by baumgarr** [comment]
Thanks. You are absolutely correct. This should be fixed in the next release.
