### ISSUE TITLE
Another issue with tray

### ISSUE THREAD

**Issue by hosiet** [baumgarr/nixnote2#184]
When built with Qt5, nixnote2 will warn on startup:

    QSocketNotifier: Can only be used with threads started with QThread

When enabled the tray, the tray will not quit if close the main window or use Ctrl+Q. Selecting quit from tray menu won't work too.

**Comment by baumgarr** [comment]
The error "QSocketNotifier: Can only be used with threads started with QThread" doesn't cause any issues & can happen with Qt4 too.

I'll investigate the tray bug.

**Comment by baumgarr** [comment]
I think I have it fixed. Let me know if it doesn't work properly in the next beta.

**Comment by hosiet** [comment]
I tested it on debian stretch today. Now if I enable the tray icon and select to "close" from the menu of tray icon, the main window will close, but the tray will keep running. Also, selecting exit from File.. menu does not stop the tray.

Is it the desired behaviour? If yes, maybe we can add a "Quit" option for a clean exit? If no, there are still some issues left.

P.S. A fresh .deb package for debian stretch / debian unstable can be found [here](https://buildd.hosiet.me/repositories/debiancn/pool/main/n/nixnote2/nixnote2_2.0~beta8+20160805+ds-1_amd64.deb) if you need to make a test.

**Comment by baumgarr** [comment]
If you select "Show Tray Icon" and do not select "Close to tray" then, selecting close from the File menu or Close from the tray icon will cause the program to exit.

If you select "Show Tray Icon" and select "Close to tray" then selecting File/Close will close to tray and selecting "Close" from the tray icon will close the program.
