### ISSUE TITLE
Leftovers in building system

### ISSUE THREAD

**Issue by hosiet** [baumgarr/nixnote2#190]
Hi,

While doing review, I found some more leftovers in the building code:

1. `NixNote2.pro` disabled opencv linking in line 19, but did not disable it on line 11. Those lines should be kept in consistency.
2. `release.txt`, `shortcut_howto.txt`, `shortcut_example.txt` and `credit.txt` were mentioned in `README.txt` but I could not find them anywhere in source code and prebuilt deb/rpm packages.
3. The `*.ts` translation files should not be distributed in binary install packages.

Hope that those problems may be fixed before next release. Thanks.

**Comment by baumgarr** [comment]
Should be corrected. Thanks.
