### ISSUE TITLE
nixnote2: error while loading shared libraries: libhunspell-1.3.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by diggerdu** [baumgarr/nixnote2#192]
Ubuntu 14.04 lts 64bit

#sudo ldconfig -v|grep libhunspell

output:
libhunspell-1.3.so.0 -> libhunspell.so

please help

**Comment by diggerdu** [comment]
I download beta8 from sourceforge, it works well, but after i upgrade, the error occured

**Comment by baumgarr** [comment]
What version did you download? Beta 8 shouldn't ask for that. It is a separate plugin.

**Comment by diggerdu** [comment]
@baumgarr 
I download nixnote2-2.0-beta8_amd64.deb from http://jaist.dl.sourceforge.net/project/nevernote/NixNote2%20-%20Beta%208/nixnote2-2.0-beta8_amd64.deb
it works well, but once i upgrade, bug occur

**Comment by diggerdu** [comment]
So i delete ppa source form source.d

**Comment by baumgarr** [comment]
Sorry. I was thinking opencv, not hunspell.

You said it worked until you upgraded. What did you upgrade?

Are you sure you have a 64 bit version of hunspell? On my Ubuntu 14.04
machine it is being loaded from /
usr/lib/x86_64-linux-gnu/libhunspell-1.3.so.0.

I'll give it some thought, but nothing comes to mind.

**Comment by hosiet** [comment]
I believe he is installing/upgrading from some third-party Ubuntu PPA packaged by someone else. The only problem is that which ppa is he using.

Third party packaging can be of poor quality if the dependency is not dealt correctly, but the concrete analyze needs the example deb package.

**Comment by sfabius** [comment]
I have the same issue using the install script downloaded from sourceforge. 
File is nixnote2-2.0-beta8_amd64.tar.gz. 
Perhaps just wrong version of hunspell?:
`$ locate libhunspell
/usr/lib/libhunspell-1.4.so
/usr/lib/libhunspell-1.4.so.0
/usr/lib/libhunspell-1.4.so.0.0.0
/usr/lib/libhunspell.so
`
uname: Arch linux  4.7.2-1-ARCH #1 SMP PREEMPT x86_64 GNU/Linux.

I really don't care about spelling if I can just remove that...

**Comment by baumgarr** [comment]
The next beta moves Hunspell to a plugin to avoid this issue. I'd hoped to have it out last week, but there were a few issues preventing it.

**Comment by hosiet** [comment]
Instead of moving into a plugin, what about just make it into a compile-time flag? That would be much easier.

P.S. Archlinux users should look at the AUR packages. Anyone who is willing to update PKGBUILD will be much appreciated.

**Comment by baumgarr** [comment]
It would have been easier for me, but most people don't want to recompile the whole program and I don't want to offer multiple versions with various pieces disabled or enabled.
