### ISSUE TITLE
beta8 won't run on fedora 24!

### ISSUE THREAD

**Issue by Nolaan** [baumgarr/nixnote2#197]
Download and install the rpm. Try to sync you'll have this result : 
Login failed.
SSL Errors:
The issuer certificate of a locally looked up certificate could not be found

**Comment by baumgarr** [comment]
I can't reproduce this on Fedora. I have another beta coming out in a few days, so let me know if it changes the behavior.

**Comment by baumgarr** [comment]
No response. Closing issue.
