### ISSUE TITLE
Consider update src to conform to RFC 6068

### ISSUE THREAD

**Issue by hosiet** [baumgarr/nixnote2#199]
While checking source code with [check-all-the-things](https://tracker.debian.org/pkg/check-all-the-things):

```
# As per RFC 6068, there should be no slashes after "mailto:".
$ grep -rF mailto:/ .
./gui/browserWidgets/urleditor.cpp:                !url.toLower().startsWith("mailto://") &&
./gui/nbrowserwindow.cpp:        url.toLower().startsWith("mailto://") ||
```

I did not read into the source code, but I guess we should add another condition check to capture `mailto:sombody@example.com`-typed URL scheme.

**Comment by baumgarr** [comment]
Ok. It is done.
