### ISSUE TITLE
Confirming the overall license of the project

### ISSUE THREAD

**Issue by hosiet** [baumgarr/nixnote2#202]
The copyright status is clear for those source files which declared the license inside the file (Mostly GPL-2+, some GPL-2, bsd and others).

However, the license for the whole project seems ambiguous. In `license.html` and `README.txt` it says the whole project is under GPL-2. However in `copyright` file it says the whole project is under GPL-2+. It would be great if the license is clarified so that we could determine the copyright status for other files inside the project.

**Comment by baumgarr** [comment]
I updated the license. I didn't realize there was a difference between GPL2 & GPL2+. Everything should be GPL2+.

Thanks.
