### ISSUE TITLE
potential solution for characters decoding error (e.g. non-ASCII char.) in nixnote2

### ISSUE THREAD

**Issue by skjongithub** [baumgarr/nixnote2#204]
Use "DB Browser for SQLite" to browse the .db file, open DataStore table, switch to binary viewer, look for entries with the opening "<!DOCTYPE...", and add "3c3f786d6c2076657273696f6e3d2231
2e302220656e636f64696e673d225554462d38223f3e0d0a" (which means '<?xml version="1.0" encoding="UTF-8"?>') in the opening, and then the characters may be well decoded now. I uses traditional Chinese and at least this method works for me for now. Hoping this's helpful.

**Comment by skjongithub** [comment]
After multiple testing, I found that if I add a note from either nixnote2 or windows Evernote client software, the characters will be decoded successfully, BUT if I ADD or EDIT a note from the WEBPAGE version of Evernote, the corresponding entry in .db file will lose '<?xml version="1.0" encoding="UTF-8"?>' header and the decoding will err.

**Comment by NeSViT** [comment]
Hello, I also have problems with ukrainian and russian notes that I added from Evernote site using Web UI.
All works fine with english notes.
When I try to decode text that have unknown symbols I found that it converted from CP1251 -> UTF-8.

Hope it can help project with future improvements.

**Comment by baumgarr** [comment]
If you can export an example note from the Evernote Windows client that is in Russian or Ukranian it would help diagnose the problem.

**Comment by skjongithub** [comment]
I've recently wrote a Python script to handle this decoding problem. It worked with Traditional Chinese, at least. Maybe you can try it : https://github.com/skjongithub/Non-ASCII-Nixnote-fixer
But I cannot give any warranty about your data consistency, sorry

**Comment by baumgarr** [comment]
I added a setting in the Debugging tab of the Preferences dialog to force adding a UTF8 tag if one is missing. This will be in the next release.
