### ISSUE TITLE
Can't annotate a PDF.

### ISSUE THREAD

**Issue by Germanc** [baumgarr/nixnote2#206]
If I open a pdf from nixnote2 into Evince I can annotate it and save it into the same file. After doing that, if I go to Evernote Web, I see the file as "Unknown" and after syncing again the pdf disappear from nixnote2 and Evernote Web. Is it possible that if I annotate the file and save it with the same name for nixnote to reattach it with the new annotations ?
I can see the annotated pdf into the preview on the left side of evernote web, so I'm not sure why I can't open it or why it disappears.
Thanks !

**Comment by baumgarr** [comment]
I can't recreate this with any other type of file (I don't have a PDF editing program). Do you have this issue with other types of files?

**Comment by Germanc** [comment]
That's weird. I tested it with several different files before submitting  the bug. Now it's working as expected. I can annotate a pdf and it syncs correctly (I'm running the daily from the ppa). Thank you for your time, if it stops working I will try to reproduce easily with some simple file and attach here.
PD: It works ok with images too.

**Comment by alkorsan** [comment]
g
