### ISSUE TITLE
Use snap to package and deploy Nixnote2

### ISSUE THREAD

**Issue by caesar70** [baumgarr/nixnote2#207]
Hi Randy,
thank you for your hard and invaluable work.
I've read in another thread that you are struggling to mantain separated deb, rpm; I've also read of the issues in packaging nixnote2 for AUR.
Maybe you should consider to package your great software as snap, suitable for every distro.
In any case, thank you again for Nixnote2

**Comment by baumgarr** [comment]
I've spent some time looking into this and right now I don't think it is something I have time to implement. It sounds like a good idea, but RedHat & Fedora are pushing Flatpaks and the ports to non-Ubuntu systems are not fully implemented with the same security mechanisms. When/if all of the parties involved can come to a common standard I'll revisit it, but for right now I think I'd still need to maintain separate packages for other systems.
