### ISSUE TITLE
Plugin structure not supported in Qt5

### ISSUE THREAD

**Issue by hosiet** [baumgarr/nixnote2#208]
Compiling against Qt5 would cause the following problem:

```
hunspellplugin.cpp:47:1: error: static assertion failed: Old plugin system used
 Q_EXPORT_PLUGIN2(hunspellplugin, HunspellPlugin)
```

This is a Qt4-only feature and need to be ported onto Qt5.

**Comment by hosiet** [comment]
BTW, Installing plugins (in the form of shared library) into /usr/share is not acceptable for *any* linux distribution. Please consider moving it into /usr/lib/nixnote2/ .

**Comment by baumgarr** [comment]
Qt5 isn't supported, so your best luck is to go with Qt4 until I get time to do a port to Qt5.

**Comment by hosiet** [comment]
Arch Linux is planning to obsolete Qt4. Qtchooser now conflicts with qt5-base, which is the first step towards the eventual removal of Qt4.

Please consider putting the entire migration to Qt5 onto timetable. Thanks.

**Comment by baumgarr** [comment]
I've migrated the plugins to Qt5.
