### ISSUE TITLE
Error in sync - cyrrillic tag 

### ISSUE THREAD

**Issue by bvp** [baumgarr/Nixnote2#21]
Every time I run the synchronization see the error report

ERROR 2014-07-22 14:18:57.601 ( application.cpp @ 41 ) ********************************************************** 
ERROR 2014-07-22 14:18:57.601 ( application.cpp @ 42 ) ********************************************************** 
ERROR 2014-07-22 14:18:57.601 ( application.cpp @ 43 ) ********************************************************** 
ERROR 2014-07-22 14:18:57.601 ( application.cpp @ 44 ) ********************************************************** 
ERROR 2014-07-22 14:18:57.601 ( application.cpp @ 45 ) ********************************************************** 
ERROR 2014-07-22 14:18:57.601 ( application.cpp @ 46 ) ********************************************************** 
ERROR 2014-07-22 14:18:57.601 ( application.cpp @ 47 ) ********************************************************** 
ERROR 2014-07-22 14:18:57.601 ( application.cpp @ 48 ) std::exception was caught:  qevercloud::Optional: nonexistent value access2

**Comment by Wolfhound150** [comment]
I have the same problem with syncronization. I turned on DEBUG mode and found that problem is with note with cyrrillic tag that contains space symbol. After I removed the space character in the tag name in the web client, synchronization was successful

**Comment by ul** [comment]
@Wolfhound150 if you don't need to sort tags, you can try my fork https://github.com/ul/Nixnote2 until somebody will make right fix, disabling sorting helps to workaround problem.

**Comment by baumgarr** [comment]
I added a debug option to turn off sort tags.  It is mimicking the fork mentioned above.  It is not as goof of a workaround as I'd like but it is better than nothing.  By default this option is disabled and can be found in the Debug section of the Preferences. Thanks to UL for finding the workaround!

**Comment by baumgarr** [comment]
Closing as a workaround is provided.
