### ISSUE TITLE
Bug with special characters and spaces

### ISSUE THREAD

**Issue by danielmaurer** [baumgarr/nixnote2#210]
Bug with special characters and spaces. See below.

In Nixnote

> De modo semelhante a JacÃ³ Lutero lutou contra Deus atÃ© compreendÃª-lo como o Senhor soberano que tem amor profundo para com suas criaturas, mesmo caÃ­das.
> Gn 32.22-30
> 
> Jesus Ã© o Senhor
> oque implica dizer isso
> 
> Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Entusiasmo= Deus vibrando em vocÃª.Â Â Â Â Â 
> 
> Â Â Â Â Â Â Â Â Â Â Â Â Ele disse a LÃ¡zaro, vive ele viveu. A palavra de Deus Ã© poderosa, ela dÃ¡ vida por isso digamos, vive, crÃª, obedeÃ§a.Â Â Â Â Â 

In Evernote

> De modo semelhante a Jacó Lutero lutou contra Deus até compreendê-lo como o Senhor soberano que tem amor profundo para com suas criaturas, mesmo caídas.
> Gn 32.22-30
> 
> Jesus é o Senhor
> oque implica dizer isso
> 
> ```
>             Entusiasmo= Deus vibrando em você.     
> 
> 
>         Ele disse a Lázaro, vive ele viveu. A palavra de Deus é poderosa, ela dá vida por isso digamos, vive, crê, obedeça.     
> ```

**Comment by skjongithub** [comment]
I've recently wrote a Python script to handle this problem. It worked with Traditional Chinese, at least. Maybe you can try it : https://github.com/skjongithub/Non-ASCII-Nixnote-fixer
But I cannot give any warranty about your data consistency, sorry

**Comment by baumgarr** [comment]
Was this note originally created on Nixnote, or was it created on NixNote? Was it changed either on NixNote or on Evernote and then the problem appeared, or does it happen after the first sync?

**Comment by danielmaurer** [comment]
This note was originally created on Evernote and the problem happen after the first sync.

**Comment by rickmed** [comment]
I can confirm this. 

Created on nixnote:
"Unity DE, Compositing, Pulseaudio, Software Center, Upstart."

Worked on other things with evernote web.

Opened on nixnote:
"Unity DE,Â Compositing,Â Pulseaudio,Â Software Center, Upstart."

**Comment by baumgarr** [comment]
It looks like Evernote isn't sending the UTF8 tag in the note that NN is expecting. The Windows client in the past always sent this, but I don't have a Windows client to test with anymore.

I added a debug setting to force this if it isn't found. I don't want to do it by default in case it messes something else up, but by checking "Force UTF8 Encoding" it will add this tag. This should be in the next release.
