### ISSUE TITLE
publish binaries of releases on Github instead of Sourceforge

### ISSUE THREAD

**Issue by ludovicaelbrecht** [baumgarr/nixnote2#211]
Hi,

I use nixnote2 very frequently, so thanks a lot for creating it.

Would it be possible to host the releases (the various rpm, deb, ebuild files) on Github at https://github.com/baumgarr/nixnote2/releases instead of on Sourceforge?

Sourceforge isn't trustworthy enough, given its recent history. 

Sourceforge is also very unreliable to use. E.g. if you try to download the 64bit RPM for beta 10 from https://sourceforge.net/projects/nevernote/files/NixNote2%20-%20Beta%2010/, it currently says it's not available. So AFAIK there's no way to download that binary at the moment.

Thanks,
Ludovic

**Comment by baumgarr** [comment]
Thanks for letting me know about the problem with downloads on SourceForge. I've re-uploaded them and they appear to be fine now.

I don't see any easy way to publish binaries on GitHub. At one time they had a way to do it, but from what I've read in the past they don't recommend doing that now. They recommend using alternative sites. Eventually I may but a full website together & serve it from there, but right now I don't have the time.

Thanks.
