### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by dgbutterworth** [baumgarr/nixnote2#215]
This is not an issue - but simply an expression thanks and compliments.  Having looked around for a few minutes for methods to deliver this, here seems like the best (easiest) way to communicate the thought.
    You are my #1 hero (ranking of #1 = today, at least; category of hero = permanent).  This is exactly what I needed to fill a number of holes in my work-flow tool box. I've used Evernote for a while. Also, I began a move to open source software a while ago, for a lot of reasons - high among the reasons being a desire to have full control over my data, including long-term viability (or accessibility) of data/information. I made the final move to immersion in open source by switching to linux (currently Mint 17.3) as my OS - refusing to continue beyond WinXP.  Evernote, while useful, has always disturbed me due to the proprietary format.  I did run across your work a while ago (when still referred to as NeverNote - I'm not sure when, but I did hook into your shared NeverNote notebook long ago), but for reasons I can't remember did not pursue the option - until now.  NixNote2 is great!
    I'll stop there - for both our sakes.  I will consider which charity to direct an appropriate contribution - because I do like it enough to pay for it, and my ability to contribute in other ways are limited (I can't really code, but I will gladly post any bugs found and note any other constructive thoughts/idea).  For now, I'm hoping this expression of appreciation will serve as a modest contribution, albeit nebulous.
   So thanks.
David

**Comment by baumgarr** [comment]
Glad that you find it useful. Thanks for the contribution!
