### ISSUE TITLE
hunspellplugin.h:31:23: error: ‘IID’ has not been declared

### ISSUE THREAD

**Issue by zhtengw** [baumgarr/nixnote2#219]
After the latest seven commits from  3ea4ed4 , it keeps complaining when compiled:
"
plugins/hunspell/hunspellplugin.h:31:23: error: ‘IID’ has not been declared
     Q_PLUGIN_METADATA(IID "org.nixnote.NixNote2.HunspellInterface/2.0");
"

--------------- the full build log --------------

make -j7 
x86_64-pc-linux-gnu-g++ -c -O2 -pipe -march=native -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I/usr/include/poppler/qt4 -I. -o main.o main.cpp
x86_64-pc-linux-gnu-g++ -c -O2 -pipe -march=native -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I/usr/include/poppler/qt4 -I. -o nixnote.o nixnote.cpp
x86_64-pc-linux-gnu-g++ -c -O2 -pipe -march=native -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I/usr/include/poppler/qt4 -I. -o global.o global.cpp
x86_64-pc-linux-gnu-g++ -c -O2 -pipe -march=native -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I/usr/include/poppler/qt4 -I. -o filemanager.o settings/filemanager.cpp
x86_64-pc-linux-gnu-g++ -c -O2 -pipe -march=native -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I/usr/include/poppler/qt4 -I. -o nwebpage.o gui/nwebpage.cpp
x86_64-pc-linux-gnu-g++ -c -O2 -pipe -march=native -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I/usr/include/poppler/qt4 -I. -o nwebview.o gui/nwebview.cpp
x86_64-pc-linux-gnu-g++ -c -O2 -pipe -march=native -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I/usr/include/poppler/qt4 -I. -o databaseconnection.o sql/databaseconnection.cpp
In file included from ./gui/nbrowserwindow.h:61:0,
                 from gui/nwebview.h:31,
                 from gui/nwebview.cpp:21:
./plugins/hunspell/hunspellplugin.h:31:23: error: ‘IID’ has not been declared
     Q_PLUGIN_METADATA(IID "org.nixnote.NixNote2.HunspellInterface/2.0");
                       ^
./plugins/hunspell/hunspellplugin.h:31:27: error: expected ‘,’ or ‘...’ before string constant
     Q_PLUGIN_METADATA(IID "org.nixnote.NixNote2.HunspellInterface/2.0");
                           ^
./plugins/hunspell/hunspellplugin.h:31:71: error: ISO C++ forbids declaration of ‘Q_PLUGIN_METADATA’ with no type [-fpermissive]
     Q_PLUGIN_METADATA(IID "org.nixnote.NixNote2.HunspellInterface/2.0");
                                                                       ^
x86_64-pc-linux-gnu-g++ -c -O2 -pipe -march=native -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I/usr/include/poppler/qt4 -I. -o qsdebugoutput.o logger/qsdebugoutput.cpp
x86_64-pc-linux-gnu-g++ -c -O2 -pipe -march=native -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I/usr/include/poppler/qt4 -I. -o qslog.o logger/qslog.cpp
In file included from ./gui/nbrowserwindow.h:61:0,
                 from gui/ntabwidget.h:23,
                 from nixnote.h:35,
                 from main.cpp:22:
./plugins/hunspell/hunspellplugin.h:31:23: error: ‘IID’ has not been declared
     Q_PLUGIN_METADATA(IID "org.nixnote.NixNote2.HunspellInterface/2.0");
                       ^
./plugins/hunspell/hunspellplugin.h:31:27: error: expected ‘,’ or ‘...’ before string constant
     Q_PLUGIN_METADATA(IID "org.nixnote.NixNote2.HunspellInterface/2.0");
                           ^
./plugins/hunspell/hunspellplugin.h:31:71: error: ISO C++ forbids declaration of ‘Q_PLUGIN_METADATA’ with no type [-fpermissive]
     Q_PLUGIN_METADATA(IID "org.nixnote.NixNote2.HunspellInterface/2.0");
                                                                       ^
In file included from ./gui/nbrowserwindow.h:61:0,
                 from gui/ntabwidget.h:23,
                 from nixnote.h:35,
                 from nixnote.cpp:20:
./plugins/hunspell/hunspellplugin.h:31:23: error: ‘IID’ has not been declared
     Q_PLUGIN_METADATA(IID "org.nixnote.NixNote2.HunspellInterface/2.0");
                       ^
./plugins/hunspell/hunspellplugin.h:31:27: error: expected ‘,’ or ‘...’ before string constant
     Q_PLUGIN_METADATA(IID "org.nixnote.NixNote2.HunspellInterface/2.0");
                           ^
./plugins/hunspell/hunspellplugin.h:31:71: error: ISO C++ forbids declaration of ‘Q_PLUGIN_METADATA’ with no type [-fpermissive]
     Q_PLUGIN_METADATA(IID "org.nixnote.NixNote2.HunspellInterface/2.0");
                                                                       ^
x86_64-pc-linux-gnu-g++ -c -O2 -pipe -march=native -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I/usr/include/poppler/qt4 -I. -o qslogdest.o logger/qslogdest.cpp
Makefile:3372: recipe for target 'nixnote.o' failed
make: *** [nixnote.o] Error 1
make: *** Waiting for unfinished jobs....
Makefile:3611: recipe for target 'nwebview.o' failed
make: *** [nwebview.o] Error 1
Makefile:3223: recipe for target 'main.o' failed
make: *** [main.o] Error 1

**Comment by baumgarr** [comment]
I've migrated to Qt5. Please try compiling against that version.

**Comment by zhtengw** [comment]
So, does it mean that it can never be compiled under Qt4 after 2.0_beta10?

**Comment by baumgarr** [comment]
Not the plugins. The structure is different between how Qt4 & Qt5 handles plugins.

**Comment by zhtengw** [comment]
thanks @baumgarr , I have tried compiling against Qt5, and it completed without any error. I will update the Gentoo ebuild script then.

**Comment by baumgarr** [comment]
Just an FYI, I updated it so it can compile against either Qt4 or Qt5.

**Comment by zhtengw** [comment]
Thanks, the commit what you changed in is just what I hacked for compiling against qt4 under gentoo.
