### ISSUE TITLE
Nixnote2 beta2 crashes during sync - Possible inknote issue.

### ISSUE THREAD

**Issue by suky57** [baumgarr/Nixnote2#22]
Hi,

when I start nixnote and click sync button, it starts synchronizing. After downloading of 207 MB, it crashes.

There is terminal output:

DEBUG 2014-07-28 12:10:24.596 ( global.cpp @ 79 ) Shared memory key:  "1b73cc55-9a2f-441b-877a-ca1d0131cd21" 
 INFO 2014-07-28 12:10:24.597 ( main.cpp @ 135 ) Built with Qt 4.8.4 running on 4.8.6 
Got bus address:  "unix:abstract=/tmp/dbus-rkoRjDvhTY,guid=2c3bcd04bafdffe19eead21053d60ef5" 
Connected to accessibility bus at:  "unix:abstract=/tmp/dbus-rkoRjDvhTY,guid=2c3bcd04bafdffe19eead21053d60ef5" 
Registered DEC:  true 
Registered event listener change listener:  true 
 INFO 2014-07-28 12:10:33.017 ( nixnote.cpp @ 1564 ) "Zahajuji synchronizaci" 
 INFO 2014-07-28 12:10:33.018 ( nixnote.cpp @ 1564 ) "Stahuji změny" 
 INFO 2014-07-28 12:10:33.897 ( nixnote.cpp @ 1564 ) "Stahování 0% hotovo pro poznámkové bloky, štítky a hledání." 
 INFO 2014-07-28 12:11:52.733 ( nixnote.cpp @ 1564 ) "Stahování 97% hotovo pro poznámkové bloky, štítky a hledání." 
 INFO 2014-07-28 12:11:52.735 ( nixnote.cpp @ 1564 ) "Stahování dokončeno pro poznámkové bloky, štítky a hledání. Stahuji poznámky." 
Error: signal 11:
nixnote2(_Z13fault_handleri+0x18)[0x47f8c8]
/lib/x86_64-linux-gnu/libc.so.6(+0x35480)[0x7fc000777480]
/usr/lib/x86_64-linux-gnu/libQtCore.so.4(_ZN7QObject7connectEPKS_PKcS1_S3_N2Qt14ConnectionTypeE+0x187)[0x7fc00149dae7]
nixnote2(_ZN20CommunicationManager20downloadInkNoteImageE7QStringPN10qevercloud8ResourceES0_S0_+0x2e2)[0x5e3af2]
nixnote2(_ZN20CommunicationManager16checkForInkNotesER5QListIN10qevercloud8ResourceEE7QStringS5_+0x9d)[0x5e42cd]
nixnote2(_ZN20CommunicationManager16processSyncChunkERN10qevercloud9SyncChunkE7QString+0x5ce)[0x5e4abe]
nixnote2(_ZN20CommunicationManager12getSyncChunkERN10qevercloud9SyncChunkEiiib7QString+0x52c)[0x5e666c]
nixnote2(_ZN10SyncRunner17syncRemoteToLocalEi+0x39f)[0x4cbecf]
nixnote2(_ZN10SyncRunner12evernoteSyncEv+0x2fe)[0x4cd72e]
nixnote2(_ZN10SyncRunner11synchronizeEv+0x21e)[0x4ce06e]
nixnote2[0x6f3335]
/usr/lib/x86_64-linux-gnu/libQtCore.so.4(_ZN7QObject5eventEP6QEvent+0x1c1)[0x7fc0014a0ed1]
/usr/lib/x86_64-linux-gnu/libQtGui.so.4(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x8c)[0x7fc001d01c0c]
/usr/lib/x86_64-linux-gnu/libQtGui.so.4(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x2a0)[0x7fc001d08360]
nixnote2(_ZN11Application6notifyEP7QObjectP6QEvent+0x15)[0x61e3a5]
/usr/lib/x86_64-linux-gnu/libQtCore.so.4(_ZN16QCoreApplication14notifyInternalEP7QObjectP6QEvent+0x6d)[0x7fc0014887fd]
/usr/lib/x86_64-linux-gnu/libQtCore.so.4(_ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData+0x201)[0x7fc00148bed1]
/usr/lib/x86_64-linux-gnu/libQtCore.so.4(+0x1a8e43)[0x7fc0014b5e43]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x254)[0x7fbffbadbe04]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x49048)[0x7fbffbadc048]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x2c)[0x7fbffbadc0ec]
/usr/lib/x86_64-linux-gnu/libQtCore.so.4(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x77)[0x7fc0014b5fa7]
/usr/lib/x86_64-linux-gnu/libQtCore.so.4(_ZN10QEventLoop13processEventsE6QFlagsINS_17ProcessEventsFlagEE+0x31)[0x7fc001487481]
/usr/lib/x86_64-linux-gnu/libQtCore.so.4(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0x185)[0x7fc001487795]
/usr/lib/x86_64-linux-gnu/libQtCore.so.4(_ZN7QThread4execEv+0xe9)[0x7fc001385c39]
/usr/lib/x86_64-linux-gnu/libQtCore.so.4(+0x7b39f)[0x7fc00138839f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x80a4)[0x7fc0001110a4]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7fc00082804d]
QThreadStorage: Thread 0x7fbfd405e4d0 exited after QThreadStorage 10 destroyed
Error: signal 11:
nixnote2(_Z13fault_handleri+0x18)[0x47f8c8]
/lib/x86_64-linux-gnu/libc.so.6(+0x35480)[0x7fc000777480]
/usr/lib/x86_64-linux-gnu/libQtGui.so.4(_ZN4QPenC1Ev+0x24)[0x7fc001e77164]
/usr/lib/x86_64-linux-gnu/libQtGui.so.4(_ZN13QPainterStateC1Ev+0x64)[0x7fc001e43e94]
/usr/lib/x86_64-linux-gnu/libQtGui.so.4(+0x37ebf3)[0x7fc001eb9bf3]
/usr/lib/x86_64-linux-gnu/libQtGui.so.4(+0x388640)[0x7fc001ec3640]
/usr/lib/x86_64-linux-gnu/libQtGui.so.4(_ZN8QPainter5beginEP12QPaintDevice+0x12e)[0x7fc001e47f0e]
/usr/lib/x86_64-linux-gnu/libQtGui.so.4(_ZN8QPainterC2EP12QPaintDevice+0x108)[0x7fc001e48a18]
/usr/lib/x86_64-linux-gnu/libQtGui.so.4(_ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore+0x514)[0x7fc001d4c0e4]
/usr/lib/x86_64-linux-gnu/libQtGui.so.4(+0x3d4c72)[0x7fc001f0fc72]
/usr/lib/x86_64-linux-gnu/libQtGui.so.4(_ZN14QWidgetPrivate16syncBackingStoreEv+0x80)[0x7fc001d41460]
/usr/lib/x86_64-linux-gnu/libQtGui.so.4(_ZN7QWidget5eventEP6QEvent+0x580)[0x7fc001d518e0]
/usr/lib/x86_64-linux-gnu/libQtGui.so.4(_ZN11QMainWindow5eventEP6QEvent+0x103)[0x7fc00210fd63]
/usr/lib/x86_64-linux-gnu/libQtGui.so.4(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x8c)[0x7fc001d01c0c]
/usr/lib/x86_64-linux-gnu/libQtGui.so.4(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x2a0)[0x7fc001d08360]
nixnote2(_ZN11Application6notifyEP7QObjectP6QEvent+0x15)[0x61e3a5]
/usr/lib/x86_64-linux-gnu/libQtCore.so.4(_ZN16QCoreApplication14notifyInternalEP7QObjectP6QEvent+0x6d)[0x7fc0014887fd]
/usr/lib/x86_64-linux-gnu/libQtCore.so.4(_ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData+0x201)[0x7fc00148bed1]
/usr/lib/x86_64-linux-gnu/libQtCore.so.4(+0x1a8e43)[0x7fc0014b5e43]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x254)[0x7fbffbadbe04]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x49048)[0x7fbffbadc048]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x2c)[0x7fbffbadc0ec]
/usr/lib/x86_64-linux-gnu/libQtCore.so.4(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x5d)[0x7fc0014b5f8d]
/usr/lib/x86_64-linux-gnu/libQtGui.so.4(+0x2662c6)[0x7fc001da12c6]
/usr/lib/x86_64-linux-gnu/libQtCore.so.4(_ZN10QEventLoop13processEventsE6QFlagsINS_17ProcessEventsFlagEE+0x31)[0x7fc001487481]
/usr/lib/x86_64-linux-gnu/libQtCore.so.4(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0x185)[0x7fc001487795]
/usr/lib/x86_64-linux-gnu/libQtCore.so.4(_ZN16QCoreApplication4execEv+0x87)[0x7fc00148cef7]
nixnote2(main+0x922)[0x47c7d2]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7fc000763b45]
nixnote2[0x47f7e8]

**Comment by baumgarr** [comment]
Both of you are dying trying to download ink note images.  I'll see if I can reproduce it.

**Comment by baumgarr** [comment]
I think I have it fixed.  If it is still an issue after the next beta please re-open this incident.

**Comment by suky57** [comment]
Hi Randy!

great job! Thank you  so much I can.

Can you tell me when will be the next beta released?

Thank you and have a nice day!

Martin Sukany
Czech Republic

*Martin Sukaný*
T: +420 776 275 713
E: martin@sukany.cz
L: https://www.linkedin.com/pub/martin-sukan%C3%BD/79/588/431

2015-03-28 20:42 GMT+01:00 baumgarr <notifications@github.com>:

**Comment by baumgarr** [comment]
Soon.  There is another bug or two I want to take a shot at and I'll
release it.  Hopefully in a week, but it really depends on how much free
time I can find.
