### ISSUE TITLE
Pasting evernote: urls not working

### ISSUE THREAD

**Issue by bedohave** [baumgarr/nixnote2#221]
Similar to https://github.com/baumgarr/nixnote2/issues/83:

**What I tried**

- Copied note link from Note A
- Opened Note B for editing
- Pressed Ctrl-V (or Edit/Paste)

**What I Expected**
A link titled _Note A_ in Note B

**What Happened**
Nothing. Nothing in the source; manually inserting <a> tag into source works. 

Running: nixnote2-daily+20161107 on Ubuntu 16.10

**Comment by baumgarr** [comment]
I can't recreate this. Was the note synchronized?

**Comment by bedohave** [comment]
Yes. It was. Tried on several occasions with several notes.

Then, after changing the note and user-interface fonts from "System 
default" (to other installed fonts), it started working. I am now able to 
paste these links.

So odd.


Shall I mark this solved?

**Comment by baumgarr** [comment]
I'm going to mark it as resolved since I can't reproduce it. If it happens again let me know.

Thanks.

**Comment by rickmed** [comment]
I can confirm. I have Arial as font in editor, when changed to system default it worked.

**Comment by baumgarr** [comment]
I still can't recreate this. What window manager are you using?

If you are using the PPA, try updating it tomorrow. Set the messages level to Debug and try to recreate the problem. If you can, then past at least a portion of the logs here. I'm specifically looking for messages from nbrowserwindow in the 800-900 range. That should tell me what NixNote sees from the past itself and will help me to narrow down the problem.

**Comment by rickmed** [comment]
wierd: didn't work with systemd font, changed back to arial and worked again. I'll update and see if it happens again.

**Comment by bedohave** [comment]
I got the latest build via the PPA (nixnote2-daily+20161209). This pasting error now occurs regardless of

- changes to UI font (system default, any other)
- changes to note font (same as above)
- syncs
- app restarts

Window manager is Unity.

These are the last five messages in the log after I tried doing a paste of a link:

> 
> DEBUG 2016-12-09 11:16:53.087 ( gui/nbrowserwindow.cpp @ 895 ) Have URL?: false 
> DEBUG 2016-12-09 11:16:53.087 ( gui/nbrowserwindow.cpp @ 923 ) Has HTML: false "" 
> DEBUG 2016-12-09 11:16:53.088 ( gui/nbrowserwindow.cpp @ 924 ) Has Color: false 
> DEBUG 2016-12-09 11:16:53.088 ( gui/nbrowserwindow.cpp @ 925 ) Has Url: false 
> DEBUG 2016-12-09 11:16:53.088 ( gui/nbrowserwindow.cpp @ 929 ) Url: "evernote:///view/181281/s2/adae94e0-e9c0-4766-80b5-dfd840011505/adae94e0-e9c0-4766-80b5-dfd840011505/"

**Comment by baumgarr** [comment]
Next stupid question. What is the exact title of the note you are trying to paste?

**Comment by baumgarr** [comment]
... and is it in a notebook you own or a shared notebook?

**Comment by bedohave** [comment]
Exact title is "Ailie and Madeleine's Company" in my own notebook.

**Comment by baumgarr** [comment]
I think I found it. I should be able to upload a fix tonight.

**Comment by baumgarr** [comment]
It should be updated. Give it a try after the nightly build & let me know if it fixes it. If it doesn't please copy the last lines like you did the last time. Thanks!

**Comment by bedohave** [comment]
The 20121211 version not only seems to have fixed this problem, it also appears to be treating the "Default GUI Font Size" more accurately. In the past, changes to this setting (from default to 14) made the UI elements appear more like 12pt. 

Thanks!

**Comment by baumgarr** [comment]
I'm not sure why that would impact the font, but I am glad it is working better

**Comment by bedohave** [comment]
Ya, odd. Could just as easily been something spurious on my side. (Sometimes I'm not the most patient tester, you know, changing lots of things at once...changing some back...) 

Loving Nixnote2 btw; it's so fast.

**Comment by rickmed** [comment]
Currently, when I copy a link and go ctrl+v, nothing happens, then I do ctrl+shift+p (paste unformatted) and it pastes it unformatted, if I then go ctrl+v it pastes it correctly as a link. Weird

build  2.0-beta-10-0+863+47+201701081902, xubuntu 16.04
