### ISSUE TITLE
Daily PPA builds failing since 24 Nov

### ISSUE THREAD

**Issue by artmg** [baumgarr/nixnote2#226]
Hi, due to a [downstream issue with the Launchpad import](https://github.com/artmg/nixnote2-packaging/issues/20) of the source code from this project, the Daily PPA has not received any newly committed code since 24th November.

Please note that this issue is being raised here as an FYI only. The action to rectify must be taken downstream by the PPA packagers. @baumgarr and other code contributors to this project **cannot** be held accountable for this hiatus in updates.

Once the downstream issue is resolved, and builds are happening once again I will report here and close this ticket. I apologise for any inconvenience to the user base.

**Comment by artmg** [comment]
Progress update: attempt at rectifying downstream looks promising. Builds apparently successful and on their way to the PPA. Let's hope you start seeing updates available again soon...

```
# update to latest version available in PPA you previously installed
sudo apt-get update
sudo apt-get install nixnote2
# check internal version number
dpkg -s nixnote2 | grep Version
```
and check that Help / About for friendly version. Should be at least **2016120x**

**Comment by artmg** [comment]
Hmmm, still failing but with different issue now - raised new ticket [Build fails compiling Hunspell Plugins](https://github.com/artmg/nixnote2-packaging/issues/21)

I might need some help on this one - I'll start by checking for related issues in baumgarr repo.

**Comment by artmg** [comment]
Ok, the PPA's look like they're back on line, but they're successfully building against QT5 version now, so you may notice a difference :)

**Comment by baumgarr** [comment]
Since they are building again, I'm going to close this issue. Thanks for the help!
