### ISSUE TITLE
Add reminder from command line

### ISSUE THREAD

**Issue by sunjam** [baumgarr/nixnote2#233]
Hi, I was looking through shortcuts.txt and the help page for a way to add a reminder from the command line.

Is this possible?

example: nixnote2 addNote --notebook="My Stuff" --title="My New Note" **--reminder**=%x%x%x

**Comment by baumgarr** [comment]
No, this currently can't be done but I'll give it some thought.

**Comment by baumgarr** [comment]
I pushed out this change. You should be able to set a reminder on new notes & alter the reminder on existing notes. I haven't done exhaustive testing, but on my basic testing it works. If you encounter problems let me know.  Thanks for the suggestion.
