### ISSUE TITLE
Debug message in latest build -- nixnote2 has refused to start a couple times

### ISSUE THREAD

**Issue by sunjam** [baumgarr/nixnote2#234]
Getting this output (using latest git build) when starting nixnote2 from terminal.  It has refused to start a couple times, but works when I execute it from the terminal a couple times in a row

$ nixnote2
DEBUG 2016-12-10 09:54:26.716 ( ../nixnote2/gui/shortcutkeys.cpp @ 203 ) Loading system shortcuts from  "/usr/share/nixnote2/shortcuts.txt" 
DEBUG 2016-12-10 09:54:26.717 ( ../nixnote2/gui/shortcutkeys.cpp @ 205 ) Loadng user shortcuts from  "/home/james/.nixnote/shortcuts.txt" 
DEBUG 2016-12-10 09:54:26.717 ( ../nixnote2/gui/shortcutkeys.cpp @ 236 ) Unable to open file for reading or file does not exist. 
QObject::startTimer: QTimer cannot have a negative interval

**At this point GUI either starts or drops me back to prompt.**

**Comment by baumgarr** [comment]
Are there any more debug messages when it fails to start? You could also try setting the message level to trace to see if it provides more information. Also double check that there isn't another instance running.

**Comment by sunjam** [comment]
**Ok, changed log level to Trace.**

[Here is the resulting output gist](https://gist.github.com/sunjam/4b50038e7a83ee0a5ac8e81b4afb47b2)

I launched latest nixnote2 as trace, synced it, and closed it.  It actually froze completely at the end and I Xfce gave me a "Sure you want to close this unresponsive application?"  "**Yes**/No" then it was killed.

**Comment by baumgarr** [comment]
I don't see anything in the trace that makes me suspicious. If you have sync on startup & close enabled, then disable them. That will cause a slower startup & shutdown and could be causing xfce to think it is hung.

If that doesn't work then try a new database in case it is somehow corrupt. You can rename ~/.nixnote/db-1 to something else or setup a new account and give it a try. Don't do a sync, just try to exercise the program locally. That will help determine if it is a DB/sync issue. 

Other than that I can't think of anything other than seeing if it behaves differently on a different machine or window manager. The places it hung both times is different so recreating it will be difficult.

**Comment by sunjam** [comment]
Update, seems all of Evernote is going offline today especially due to maintenance (all their data is moving to Google Cloud) and will be in migration until 12/16.

**Comment by baumgarr** [comment]
Is this still a problem for you after the migration?

**Comment by sunjam** [comment]
Just updated to the latest build.
[here is output when starting Nixnote from terminal](https://gist.github.com/sunjam/11f68664b82f9a264bd267bb48dbc861) with my regular database.
Here is [trace level log](https://gist.github.com/sunjam/461147687e1826e69a76df500924779d).

Hmm, Sync says "Sync'ed with errors."  Added sync trace level output as a comment to the above link.

**Comment by baumgarr** [comment]
I think you are reporting two different errors. The sync error isn't causing a lockup. The note that won't sync is because Evernote is complaining about a title of the note. Either it has some type of invalid character or some other restriction that Evernote doesn't like. It will actually have the note title a few lines above in the debugging output than the one you showed.  I also just added an error line that should produce the note title when it fails to sync, so that should help.

**Comment by sunjam** [comment]
Well, on notes not syncing I tried checking and removing any possible conflicts... was hoping everything would work (I add a lot of notes via web client through out the day), but once I sync'ed to nixnote this evening [I got the following sync with errors](https://gist.github.com/sunjam/461147687e1826e69a76df500924779d)

**Comment by baumgarr** [comment]
RROR 2016-12-16 19:56:13.755 ( ../nixnote2/threads/syncrunner.cpp @ 1153 ) "Error uploading note:9mm Potentiometer Source in China"
INFO 2016-12-16 19:56:13.755 ( ../nixnote2/nixnote.cpp @ 1857 ) "Unable to update note. Invalid note structure : :EDAMUserException: ENML_VALIDATION parameter=Attribute "type" is required and must be specified for element type "en-media"."
INFO 2016-12-16 19:56:13.755 ( ../nixnote2/nixnote.cpp @ 1857 ) "Unable to update note. Invalid note structure : :EDAMUserException: ENML_VALIDATION parameter=Attribute "type" is required and must be specified for element type "en-media"."

I'm note sure how you created the attachment to that note, but there should be a type attribute to that en-media tag specifying the mime type. You may need to re-add it manually by going into View/Show Source.

**Comment by sunjam** [comment]
I added the file by placing it into a folder I've added as my one 
'Auto Import Folder.'  I've noticed if I try to add multiple files in this manner I get the error: "Unable to Save.  Either tidy isn't installed or the note is too complex to save."    Kept getting this error so instead of using the auto import folder I just created a note and adding files as attachments.

**Comment by baumgarr** [comment]
How was the file created in the auto import folder?

**Comment by sunjam** [comment]
It was a conversation thread from Facebook that I had copy and pasted into a text file I'd created in Nixnote.  I was able to resolve "tidy not installed" and failure to sync by copying/pasting the text into a markdown editor and copy/pasting the resulting html code back into Nixnote.

**Comment by baumgarr** [comment]
Doing a copy & paste from a web page is something I've never fully supported. If it works then that is great, but I'd recommend using Evernote's web clipper for web pages. The reason being that Evernote requires very well structured HTML and doing a cut & paste from a web page will most likely get you very malformed HTML.

NixNote uses Tidy to try and clean things up, but not everything can be fixed.

The same is pretty much true with import folders. You can do simple text notes or individual files (which will be created in new notes as atachments), but you can't do anything fancy like import an HTML page and expect it to work. I don't think I have anything setup to handle that type of file.

Sorry.

**Comment by panasaan** [comment]
same problem here

**Comment by sunjam** [comment]
@panasaan 

Hi, it'd be more helpful if you attached your debug log for nixnote.  Happy holidays.  Also, did you update or build nixnote2 from source recently?
