### ISSUE TITLE
Newly set tags won't save (and vanish when switching away from the note)

### ISSUE THREAD

**Issue by jeffbuhrt** [baumgarr/nixnote2#235]
I am using nixnote2-2.0_beta10-3.ndias.fc25.x86_64 on Fedora x86_64.

When I set any tag on a new or existing sync'd note the tag doesn't save. I see the tag in the middle section, but not at the top. I select another note and reselect the note I set the tag and it is gone.

Debug log:
DEBUG 2016-12-14 21:04:15.625 ( gui/nbrowserwindow.cpp @ 366 ) Setting note contents to 5513 
DEBUG 2016-12-14 21:04:15.625 ( gui/nbrowserwindow.cpp @ 378 ) this.lid: 5518 5513 
DEBUG 2016-12-14 21:04:15.625 ( gui/nbrowserwindow.cpp @ 386 ) editor is dirty 
DEBUG 2016-12-14 21:04:15.625 ( gui/nbrowserwindow.cpp @ 397 ) Getting note 
DEBUG 2016-12-14 21:04:15.633 ( gui/nbrowserwindow.cpp @ 412 ) Checking if note is in cache 
DEBUG 2016-12-14 21:04:15.634 ( gui/nbrowserwindow.cpp @ 414 ) Fetching from cache 
DEBUG 2016-12-14 21:04:15.634 ( gui/nbrowserwindow.cpp @ 420 ) Setting content from cache. 
DEBUG 2016-12-14 21:04:15.634 ( gui/nbrowserwindow.cpp @ 451 ) Setting up note title 
DEBUG 2016-12-14 21:04:15.643 ( gui/nbrowserwindow.cpp @ 456 ) Setting editor contents 
DEBUG 2016-12-14 21:04:15.645 ( gui/nbrowserwindow.cpp @ 464 ) Setting attributes 
DEBUG 2016-12-14 21:04:15.645 ( gui/nbrowserwindow.cpp @ 499 ) Setting tags 
DEBUG 2016-12-14 21:04:15.662 ( gui/nbrowserwindow.cpp @ 518 ) Setting notebook 
DEBUG 2016-12-14 21:04:15.663 ( gui/nbrowserwindow.cpp @ 521 ) Setting URL 
DEBUG 2016-12-14 21:04:15.663 ( gui/nbrowserwindow.cpp @ 524 ) Setting note attributes 
DEBUG 2016-12-14 21:04:15.663 ( gui/nbrowserwindow.cpp @ 533 ) Calling set source 
DEBUG 2016-12-14 21:04:15.663 ( gui/nbrowserwindow.cpp @ 543 ) Checking thumbanail 
DEBUG 2016-12-14 21:04:15.664 ( gui/nbrowserwindow.cpp @ 553 ) Exiting setContent 
DEBUG 2016-12-14 21:04:17.183 ( gui/nbrowserwindow.cpp @ 366 ) Setting note contents to 5518 
DEBUG 2016-12-14 21:04:17.183 ( gui/nbrowserwindow.cpp @ 378 ) this.lid: 5513 5518 
DEBUG 2016-12-14 21:04:17.183 ( gui/nbrowserwindow.cpp @ 386 ) editor is dirty 
DEBUG 2016-12-14 21:04:17.183 ( gui/nbrowserwindow.cpp @ 397 ) Getting note 
DEBUG 2016-12-14 21:04:17.188 ( gui/nbrowserwindow.cpp @ 412 ) Checking if note is in cache 
DEBUG 2016-12-14 21:04:17.188 ( gui/nbrowserwindow.cpp @ 414 ) Fetching from cache 
DEBUG 2016-12-14 21:04:17.188 ( gui/nbrowserwindow.cpp @ 420 ) Setting content from cache. 
DEBUG 2016-12-14 21:04:17.188 ( gui/nbrowserwindow.cpp @ 451 ) Setting up note title 
DEBUG 2016-12-14 21:04:17.193 ( gui/nbrowserwindow.cpp @ 456 ) Setting editor contents 
DEBUG 2016-12-14 21:04:17.195 ( gui/nbrowserwindow.cpp @ 464 ) Setting attributes 
DEBUG 2016-12-14 21:04:17.195 ( gui/nbrowserwindow.cpp @ 499 ) Setting tags 
DEBUG 2016-12-14 21:04:17.205 ( gui/nbrowserwindow.cpp @ 518 ) Setting notebook 
DEBUG 2016-12-14 21:04:17.205 ( gui/nbrowserwindow.cpp @ 521 ) Setting URL 
DEBUG 2016-12-14 21:04:17.205 ( gui/nbrowserwindow.cpp @ 524 ) Setting note attributes 
DEBUG 2016-12-14 21:04:17.205 ( gui/nbrowserwindow.cpp @ 533 ) Calling set source 
DEBUG 2016-12-14 21:04:17.205 ( gui/nbrowserwindow.cpp @ 543 ) Checking thumbanail 
DEBUG 2016-12-14 21:04:17.205 ( gui/nbrowserwindow.cpp @ 553 ) Exiting setContent

**Comment by baumgarr** [comment]
At the top of the log it says what version of Qt you are using. What does it say and what is the build date?

**Comment by jeffbuhrt** [comment]
I had to enable debug, then restart (others, FYI).

Built on  Nov 28 2016  at  14:30:39
Built with Qt 5.7.0 running on 5.7.0

**Comment by baumgarr** [comment]
I can't be positive, but I think this is a bug I have already fixed. Beta 10 and earlier didn't fully support Qt5. Ay the end of October I added support for it. I can't be positive it is related because your copy of NN was built after then so I don't know what version of the source code was used, but the symptoms are identical. 

If you have the ability you can try building against the current source, otherwise you'll need to wait for the next release. Sorry. 

I'm going to close this ticket, but if it is still an issue after the next release please let me know. Thanks.
