### ISSUE TITLE
Local notebook "switches" to synchronized 

### ISSUE THREAD

**Issue by rikardo48** [baumgarr/nixnote2#236]
I create a local notebook. I verify the sync checkbox is unchecked. When I sync to Evernote, the notes in the notebook are initially not synced. However overtime, the notebook status will change to synchronized and the data will be on Evernote. This has happened several times.

**Comment by baumgarr** [comment]
I think I found the problem. If I am right it is a very old bug. I'll try to recreate it and validate the fix over the next few days.

**Comment by rikardo48** [comment]
Thank you.

**Comment by baumgarr** [comment]
It wasn't what I thought, so I need more information. Can you give me any rough sequence of events for this to occur? Does it happen after the first sync or maybe after a note is restored from the trash? Is it a conflict notebook that becomes synchronized? When you look at the notebook's properties, is does it have a the checkbox marked as synchronized?

Thanks for the info.

**Comment by rikardo48** [comment]
When I've noticed it, it is "after the fact". But here are some data points:

- Previously created offline notebooks become synchronized and their content as well.
- Recently I added a number of offline notebooks. I The notebook names are visible online but the content is not. If I add a note from the web client to an offline notebook the note shows up at next sync in Nixnote2, along with the other notes which remain offline. 
- Notes that I have moved in Nixnote between an online notebook and an offline notebook will show "synchronized" in the properties information even though I no longer see them online. 
- I have also tried to empty trash online after moving files. 

Now that I am watching closely, if I notice a pattern I will report it.

**Comment by baumgarr** [comment]
Thanks. That help. I was thinking you were saying that the notebook & all of the contents are becoming synchrinized, but it sounds like the notebook is being created in Evernote but NN2 still thinks it is local. That helps. I think I know what it is. It is close to what I initially thought the problem was, but not as bad.

**Comment by baumgarr** [comment]
I found it and can recreate it. i have it fixed but need to double check I haven't broken anything else. Thanks for the help!

**Comment by baumgarr** [comment]
I think I have this fixed and I'll upload the fix later today. If it is still an issue after the next beta please reopen the ticket. Thanks for the report!
