### ISSUE TITLE
Notebooks keep being not synchronized

### ISSUE THREAD

**Issue by dgutkowsky** [baumgarr/nixnote2#237]
I can authorize client with the Evernote and download all the notebooks and notes but after successful sync I get the following problems:
- all notebooks have unchecked 'Synchronized' checkbox and I am not able to check it
- when I add new notebook and note and try to upload it on server I am getting errors (EDAMNotFoundException: Note not found...)

I have checked every settings including debugging and they seems to be fine.

Am I doing something wrong?

(Ubuntu-Mate 16.04 64-bit, newest daily build)

**Comment by baumgarr** [comment]
Sorry. I committed a change before I fully tested it. You'll need to delete your database & re-download it after refreshing it from Github. That should correct the issue.
