### ISSUE TITLE
Paste without formatting keyboard shortcut does not work

### ISSUE THREAD

**Issue by atishagarwala** [baumgarr/nixnote2#238]
Currently running nixnote2-daily+20161218 on a fresh install of Ubuntu 16.10. It appears that the "Paste without formatting" keyboard shortcut does not work. When I select the option from the edit menu with the mouse, it works fine; however the keyboard shortcut as listed does nothing.

Edited my shortcuts.txt to change the keystrokes for the shortcut; the changed keystrokes show up in the edit menu and shortcuts list, but still doesn't work. Let me know what other information I can give you to help!

**Comment by baumgarr** [comment]
What window manager are you using and what version of Qt? There is a problem with Unity and Qt5 that some shortcuts are not being sent to the application. As far as I can tell, there is nothing I can do about it. The only options are to use a different window manager or to use Qt4.

**Comment by atishagarwala** [comment]
Qt version 5.6.1 with Unity. That's too bad; it's the only shortcut I regularly use that doesn't seem to work.

**Comment by baumgarr** [comment]
You'd need to rebuild it with Qt4 (the instructions are in the help doc) or use the deb from Sourceforge. The other guy who reported this problem did some research and found this:

https://bugs.launchpad.net/appmenu-qt5/+bug/1380702

He also read where setting the environment variable 

QT_QPA_PLATFORMTHEME=''

or

UBUNTU_MENUPROXY=''

They didn't work for him, but you may want to give it a try. If it works let me know and I'll add it to the help doc.

He did verify that it worked on other window managers, so I really don't think it is a NN bug, but I'm still keeping my eyes open for anything that can help.

**Comment by rickmed** [comment]
I'm having the same problem in xfce4 (gtk)

**Comment by baumgarr** [comment]
This isn't related to the same problem, but it is broken. I'll see what I can do to fix it.

**Comment by baumgarr** [comment]
I should be more clear. 

The problem with the paste in an extternal window isn't the same as the problem with Unity.

**Comment by baumgarr** [comment]
I think I found the problem with the paste-unformatted in an external window & it should be fixed in the next release.
Thanks for the report.
