### ISSUE TITLE
Cannot delete tags from a note

### ISSUE THREAD

**Issue by kennethso168** [baumgarr/nixnote2#242]
Running version nixnote2-daily+20161229 from daily PPA build on linux mint 18.1 cinnamon. Please find the logs attached. The logs were produced when I open nixnote2 (I set it to sync on start), and then tried to click on the "X" button to delete a tag "test" on the note with title "Test NixNote". However the tag came back when I selected another note and selected back the note. I tried deleting the tag again and did a sync, and the tag also came back after a sync. Thank you.
[debug.txt](https://github.com/baumgarr/nixnote2/files/679448/debug.txt)

**Comment by baumgarr** [comment]
I don't do the PPA build so I cannot be sure what version you are using. Do a Help/About and let me know what beta version it says. My guess is that you are using Beta 10 which has issues with Qt5. 

Try to download the latest beta from SourceForge & see if it corrects the issue. If not, try downloading the Qt4 version & see if you can reproduce the problem.

**Comment by kennethso168** [comment]
The Help>About in the PPA build really just said "nixnote2-daily+20161229". So not sure which beta it was.
Anyway thanks for pointing me to SourceForge. I tried Beta 11 with Qt5 and the issue still exists. Beta 11 with Qt4 solves the issue.
So I guess it's an issue with Qt5. I think I will stick with the Qt4 version from SourceForge for the time being.

**Comment by baumgarr** [comment]
I think I have this fixed for the next beta. Thanks for the report!
