### ISSUE TITLE
Plugins inside /usr/share/ is not correct

### ISSUE THREAD

**Issue by hosiet** [baumgarr/nixnote2#244]
According to [Filesystem Hierarchy Standard (FHS)](http://refspecs.linuxfoundation.org/fhs.shtml), `/usr/share/` [should only stores architecture-independent data](http://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s11.html). Obviously plugins are architecture-dependent.

You may want to install them into [`/usr/lib/nixnote2`](http://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s06.html).

**Comment by baumgarr** [comment]
Technically NN itself is architecture dependent so it should be moved, but doing this would result in other issues that I don't want to address before the beta is done. The plugins are also not really shared libraries but are plugins to enhance NixNote itself. They are nixnote dependent and would never be used by any other program. 

Right now, it is just safer to leave things as they are.
