### ISSUE TITLE
Can't search notes with "-" (hyphen)

### ISSUE THREAD

**Issue by gitcrtn** [baumgarr/nixnote2#247]
I am using nixnote2-2.0-beta11_amd64 on Ubuntu 14.04 LTS Desktop.
Search results are not displayed, when I search notes with "-" (hyphen).
I think this may be because of the specification of SQL.
I have made sure I can search notes with "_" (underscore) for matching "-" (hyphen).
Please fix it for searching notes with "-" for matching "-".
Thank you.

See also: Why does “_” (underscore) match “-” (hyphen)?
http://stackoverflow.com/questions/8236818/why-does-underscore-match-hyphen

**Comment by baumgarr** [comment]
I think I have this fixed for the next release. If it is a problem then, please let me know. Thanks for the report.
