### ISSUE TITLE
Open in New Window fails to recognise new note title (Minor)

### ISSUE THREAD

**Issue by artmg** [baumgarr/Nixnote2#25]
Once you have done Open Note in New Window, it will not recognise any new update to Title (note name)

This is, however, a relatively minor issue

**NixNote 2.0-beta2** on Lubuntu 14.04 (package nixnote from ppa:vincent-c/nevernote)

## Reproduce
The following test is all on a single new note which is created, then successively renamed, to reproduce the issue

* create a note and set the Title to NewNoteCalledA
* select different note to see Title change in Note List
* Select NewNoteCalledA to view it

* modify Title to NewNoteCalledB
* select different note to see Title change in Note List
* right click on NewNoteCalledB and choose View in New Window
* Note Window opens with Title NewNoteCalledB
* Close New Window
* Select NewNoteCalledB to view it

* modify Title to NewNoteCalledC
* select different note to see Title change in Note List
* right click on NewNoteCalledC and choose View in New Window
* Note Window opens with Title still showing as NewNoteCalledB (B rather than C)

## Workaround
Changing Notebook to refresh the Note List will NOT make the New Window appear with the correct name.
Exiting the application and restarting WILL make the New Window appear with the correct name

**Comment by baumgarr** [comment]
Fixed and will be available in the next release.
