### ISSUE TITLE
NixNote 2 - copyAndPaste doesn't work correctly from Chrome (Ubuntu 16.04 LTS)

### ISSUE THREAD

**Issue by raven2cz** [baumgarr/nixnote2#251]
CopyAndPaste feature doesn't work from Chrome (Ubuntu 16.04 LTS). The clipboard has to be insert first to the gedit (or other editors) and copy text again, after that the paste works to nixnote. But direct paste from the browser doesn't work.
Direct paste from chrome works for all other applications. It seems that it has to be some wrong processing of clipboard in the nixnote.

**Comment by artmg** [comment]
Hi, to help diagnose this issue, could you please 

1. look in NixNote / Help / About and paste into this issue the version of nixnote2- you are using. 
2. Also please do the same for the Help / About Qt version.
3. Could you please also try creating a **New Text Note**, then copy your text from Chrome, and **right-click** in the new blank note and choose Paste - please report what happens. 
4. Then try right-click **Paste as Unformatted Text** and also report what happens. 
5. Finally, please use Chrome to browse to a specific page we can test against, https://github.com/baumgarr/nixnote2 then copy from there and try to paste into a New Text Note.

Thanks

**Comment by raven2cz** [comment]
Hi.
Sorry for disturbance. But it's working now. I cannot simulate it again. Maybe some update fix the problem from yesterday. I had this problem one month. 
point 1: nixnote2-daily+20170108
point 2: Qt version 5.5.1.
point 3: It is OK now. The text is paste.
point 4: It is OK now. The text is paste.
point 5: I used your page for all tests.

**Comment by baumgarr** [comment]
Glad it is working now. I couldn't reproduce it on KDE, so I thought it may be done specific to Ubuntu. 

Also, I recommend using Evernote's web clipper. Copying text from a page containing HTML can be very  problematic because NixNote cannot always clean it up properly.

**Comment by raven2cz** [comment]
I found the problem. The problem is not text from the body of the browser. 
The URL from the top URL field cannot be paste to the Nixnote2. To another editors or apps the text is paste.
