### ISSUE TITLE
Doesn't import recent .enex files

### ISSUE THREAD

**Issue by Piscean** [baumgarr/nixnote2#253]
I have a local notebook of scanned documents which doesn't sync with Evernote's backend service.  Every year I export from Evernote into a .enex file.  2015.enex, 2016.enex, etc.

nixnote2 will import my 2015.enex file (~600 notes) and previous, but won't import the 2016.enex file.  What's more, if I export just 1 note to a .enex file, nixnote2 won't import it.  My guess is Evernote changed their format slightly after my 2015.enex file was created so that the new format is no longer able to import to nixnote2.

I'm running 2.0-beta11

**Comment by baumgarr** [comment]
I don't have easy access to a Windows client. Would it be possible for you to export a simple note and attach it so I can examine the structure? I think a simple note with a line of text will do. Thanks!

**Comment by Piscean** [comment]
This note is a scan of my TV channel guide, exported from the current Evernote on Windows.  Had to rename as .txt to get the upload to work.

[Channel Guide 2017_01_21_10_11_09.enex.txt](https://github.com/baumgarr/nixnote2/files/721394/Channel.Guide.2017_01_21_10_11_09.enex.txt)

**Comment by baumgarr** [comment]
Thanks. I have a check at the beginning of the import that verifies it is a version that it can understand. The one you gave me is for "6.x" but I only have a check for "5.x". 

The quickest way around it is to edit the enex file and replace the "6.x" with "5.x". When I did that the file imported. I don't have any details on what else may have changed, but it did import it.

The import also produced a second dialog box that I need to investigate. To dismiss it I had to click "cancel" but the notes imported anyway.

I need to dig a little deeper, but if you are in a hurry changing the version may be the quickest way around the problem.

**Comment by Piscean** [comment]
I'll try that, thank you!  I noticed the second dialog box as well, but as you noted, it appears to be harmless, at least from the user's perspective.

**Comment by baumgarr** [comment]
I've corrected that dialog error and have pushed out the changes. If you still have an issue after the next update please reopen this ticket.

Thanks.

**Comment by Piscean** [comment]
Thanks for the fast turn around!


Eric


________________________________
