### ISSUE TITLE
Consider using qevercloud 3.x library

### ISSUE THREAD

**Issue by hosiet** [baumgarr/nixnote2#254]
Hello,

This is a follow-up for #187.

Please consider update qevercloud/ directory to use [qevercloud 3.x](https://github.com/d1vanov/QEverCloud). This library is currently used by the Debian version of nixnote2 (and the bundled one stripped away). Making qevercloud/ directory a git submodule (which contains d1vanov's qevercloud repository) might be a good idea. Using the same codebase can help prevent future problems caused by diverging development between the old version and the new version.

Static link should be acceptable, too. Perhaps all we need is to update file path in NixNote2.pro and adjust `#include` lines inside nixnote2 source code.

**Comment by baumgarr** [comment]
That isn't something I want to do at this time. My primary concern is to get it out of beta with as few major changes as possible. After that I may consider it, but I'm not making any guarantees.
