### ISSUE TITLE
KDE Neon Dark Breeze Theme not readable

### ISSUE THREAD

**Issue by raven2cz** [baumgarr/nixnote2#258]
Hello,
Nixnote2 on KDE Neon Dark Breeze theme not readable Titles and whole content of notes.
See attached screenshots. Is there some possibility to change globally background of note to white? Or invert black fonts to white?
![screenshot_20170124_114431](https://cloud.githubusercontent.com/assets/20504243/22244160/b34b7ae6-e22a-11e6-86d9-1dee16be1754.jpeg)

**Comment by baumgarr** [comment]
Have you tried using any of the dark themes in NixNote?

**Comment by mortenskoett** [comment]
I'm curious as to where you modify the theme for Nixnote?

I'm using 2.0_beta10 downloaded from copr on Fedora.

I'm not able to choose any themes while running Nixnote. Is there a configuration file I should edit?

![screenshot from 2017-01-29 13-55-29](https://cloud.githubusercontent.com/assets/17837870/22404129/b7ba9b12-e62a-11e6-8613-bb62b0a3ef41.png)

**Comment by baumgarr** [comment]
I'd try downloading beta-11 first.

https://sourceforge.net/projects/nevernote/files/.

You can control the themes by editing the themes.ini file. Copr must have edited it to remove some of them, but editing it is pretty easy. If you look in the theme.ini in the GitHub directory you'll see a few examples.

**Comment by mortenskoett** [comment]
Alright so far so good. Running beta-11 now.

If I wanted the look similar to the picture on Github, I should edit the rest in theme.ini? Where is theme.ini found? It's not exsisting in ~/.nixnote.

Situation now:
![screenshot from 2017-01-29 15-26-23](https://cloud.githubusercontent.com/assets/17837870/22404746/a95a41dc-e637-11e6-97ad-965a53389ca1.png)

**Comment by baumgarr** [comment]
I didn't create the image on GitHub, so I can't say all of the changes that were made, but I'm guessing he was running a dark KDE theme similar to your initial post and then used the dark theme in NixNote to flip the editor background colors.

You can find the theme.ini file in /usr/share/nixnote2

**Comment by mortenskoett** [comment]
That's great! Thanks a lot.

**Comment by raven2cz** [comment]
I'm using ppa for ubuntu: http://ppa.launchpad.net/nixnote/nixnote2-daily/ubuntu/

**Comment by michaldybczak** [comment]
I have exactly the same problem on Manjaro KDE, Dark Breeze or Dark Breath. Installed from AUR. Will install git version to check if there is a difference.

EDIT: Nope, the same problem on git version.
