### ISSUE TITLE
Note shortcuts not opening

### ISSUE THREAD

**Issue by rickmed** [baumgarr/nixnote2#259]
When I click on a not shortcut on the panel it does not open, it just shows a weird list of some of the notes in the note shortcut list. Then I need to click the one I want to open it.

**Comment by baumgarr** [comment]
I'm not sure I understand what you are saying and I don't experience any unusual behavior when using shortcuts/favorites.

What version are you running?

Can you provide some screenshots of what you are trying to describe? 

Does this happen with every note, or just one?

**Comment by rickmed** [comment]
![nixnote_shortcuts](https://cloud.githubusercontent.com/assets/7104786/22386583/24aa53ee-e4ae-11e6-89ce-fb54eaf4799b.gif)

On click, shouldn't the note appear on the most right panel?

**Comment by baumgarr** [comment]
It should appear on the right, but not in a new window. Oddly I cannot recreate this behavior, but I'll try on another machine. 

What is the version of NN you are using?

As for the ones that are in the list that are not the matching note, are they pinned? Pinned notes always appear.

**Comment by rickmed** [comment]
2.0-beta-10-0+870+47+201701230602~ubuntu16.04.1 amd64 

If I understand coorectly, yes, all of the ones that appear on the list when I clicked in the gif are pinned

**Comment by baumgarr** [comment]
Ok. That explains the extra notes. 

Try downloading beta 11 from SourceForge and see if that fixes it. I don't recall fixing this in the past but maybe I'll get lucky.

**Comment by rickmed** [comment]
If I install from sourceforge, how would I upgrade later on? Is the ppa no longer being updated?

**Comment by baumgarr** [comment]
I'm not a PPA expert but I believe it won't matter. I'm not the author of the PPA, but if it gets updated with a newer version it should be upgraded when you do a check.

**Comment by baumgarr** [comment]
I found out how to recreate it. It only happens if you have it on narrow list view.

**Comment by rickmed** [comment]
shouldn't the ppa (ppa:nixnote/nixnote2-daily) being updated to beta 11?  I've seen more recently updated than the beta 11 release was in this repo but it updated to a beta 10, what's up with that?

**Comment by baumgarr** [comment]
I don't control the PPA, but generally the PPA will be more unstable because things are more current and haven't been tested.

The other problem is still the same problem as before. It isn't resetting the filter criteria properly. 

The odd thing is that it only happens on some builds. For me I can only recreate it on Windows using the narrow list view. Linux works fine for me.

If you switch to the wide view does the problem still occur?

**Comment by rickmed** [comment]
"If you switch to the wide view does the problem still occur?" yes

**Comment by baumgarr** [comment]
That was a painful bug to diagnose and must have been around for years. 

I think I have it fixed, but I need to do more testing. To get around it you can go into Edit/Preferences and go into the Debugging tab. From there, check the "Show LID column" and restart NixNote.

If you are pinning notes and selecting a shortcut it may still pick the wrong note from the list, but it won't leave it blank. A permanent fix should be out soon. I just want to do a little more testing and to get it working with pinned notes.

Thanks!

**Comment by baumgarr** [comment]
This should be in the next release. Thanks for the report.
