### ISSUE TITLE
Save Note without changing focus?

### ISSUE THREAD

**Issue by artmg** [baumgarr/nixnote2#261]
Although I can't be sure, it _appears_ that your changes to a Note are committed to the local database when you change focus onto another note (e.g. click on a different note or notebook) or when the app closes. Now, it has been quite a while since nixnote2 crashed on me during common usage, and my suspend is behaving most of the time, but I still have this nervousness about "will I loose the vital notes I typed last", especially when working on multiple notes in New Window mode. 

When using most writing apps, I have a habit of pressing `CTRL-S` periodically to commit recent changes to disk, especially after an intense period of writing, or when I leave my machine for a break. This does not appear to work in nixnote2, and the only method I have found to force a commit to disk is to grab hold of my mouse, click to display a different note, and navigate back to the one where I was working.

Is there a quick and simple way to force a Save of the recent changes to the current note without lifting your hands from the keyboard? Thanks.

**Comment by baumgarr** [comment]
I'm all for paranoia when it comes to saving data. It will be in the next release.

**Comment by artmg** [comment]
Fantastic, you're a very generous person @baumgarr Thanks
