### ISSUE TITLE
Minor Issue: Line Break \n in Note Title Results in Sync Error

### ISSUE THREAD

**Issue by ElBarto90** [baumgarr/nixnote2#262]
When pasting a Note Title containing a ' new line' as it would when copy-pasting a title of a document for example, the note can not be synced, resulting in an error:

ERROR 2017-01-31 17:14:44.511 ( communication/communicationmanager.cpp @ 557 ) EDAMUserException: 2 
ERROR 2017-01-31 17:14:44.511 ( threads/syncrunner.cpp @ 1149 ) "Error uploading note:test\nnotiz" 
 INFO 2017-01-31 17:14:44.511 ( nixnote.cpp @ 1866 ) "Unable to sync. Bad data format : :EDAMUserException: BAD_DATA_FORMAT parameter=Note.title" 
 INFO 2017-01-31 17:14:44.512 ( nixnote.cpp @ 1866 ) "Unable to sync. Bad data format : :EDAMUserException: BAD_DATA_FORMAT parameter=Note.title"

**Comment by baumgarr** [comment]
I think I have it fixed.  Thanks for the report.

**Comment by ElBarto90** [comment]
It is fixed indeed! Thank you very much for your work!
