### ISSUE TITLE
Spell check issue on Ubuntu 16.04

### ISSUE THREAD

**Issue by amarouni** [baumgarr/nixnote2#263]
I'm currently using `nixnote2-daily+20170129` and I keep getting `Hunspell plugin not found or could not be loaded.` when trying to check spelling. I installed all of the hunspell Ubuntu libraries that I could find :
```
18:33 $ dpkg -l | grep hunspell
ii  hunspell-en-us                                    20070829-6ubuntu3                               all          English_american dictionary for hunspell
ii  hunspell-fr                                       1:5.5-1                                         all          French dictionary for hunspell (dependency package)
ii  hunspell-fr-classical                             1:5.5-1                                         all          French dictionary for hunspell (classical version)
ii  libhunspell-1.3-0:amd64                           1.3.3-4ubuntu1                                  amd64        spell checker and morphological analyzer (shared library)
ii  libhunspell-dev:amd64                             1.3.3-4ubuntu1                                  amd64        spell checker and morphological analyzer (development)

```
But I'm still getting the same popup. Is there any additional configuration in nixnote2 of on my system ?

**Comment by artmg** [comment]
Hi, I'm afraid to say that the plugin functionality for nixnote2 (including spell and webcam) is not currently supported from the daily build PPA. Please note this is a packaging issue, nothing within the responsibility of this project to fix.

Until that [downstream issue](https://github.com/artmg/nixnote2-packaging/issues/24) is fixed, if you want to use the spell check feature on ubuntu, you will have to install nixnote2 from a different place, not the daily PPA. Sorry

**Comment by baumgarr** [comment]
You can also download it directly from SourceForge. https://sourceforge.net/projects/nevernote/files/NixNote2%20-%20Beta%2011/Linux/

It was separated out to minimize library conflicts on different distributions.

**Comment by baumgarr** [comment]
If you still have issues please reopen this. Thanks.
