### ISSUE TITLE
Insert Row and Insert Column commands do not works fine

### ISSUE THREAD

**Issue by danielmaurer** [baumgarr/nixnote2#264]
In Nixnote daily 01/30 Insert Row and Insert Column commands do not works fine. When executes one of this commands adds an row or column "invisible". If executes the Simplify formatting command in Evernote the row or column is changed to "visible".

**Comment by baumgarr** [comment]
I can't recreate this. Can you try this:

1.) Create an empty text note.
2.) Insert a table normally.
3.) Do an insert row 
4.) Do a "View/Show Source" to look at the HTML. Then cut & paste the generated HTML into a text document & attach it to this ticket.

Thanks.

**Comment by danielmaurer** [comment]
This issue only appears when the table is created in Evernote.

Thanks

**Comment by baumgarr** [comment]
Thanks for the clarification. This should be fixed in the next release.
