### ISSUE TITLE
Note import via command line crashes

### ISSUE THREAD

**Issue by Gizze** [baumgarr/nixnote2#265]
The import of notes from the command line does not work any more.
   nixnote2 import --input=test_import.nnex
leads to
   QWidget: Cannot create a QWidget when no GUI is being used
   Aborted (core dumped)

The note can be imported from the GUI without problems.
This used to work in 2.0 beta 7. With the update to 2.0 beta 10 I saw this error the first time (and it is still there in beta 11).
This problem breaks my script-based workflow.

**Comment by baumgarr** [comment]
This should be fixed in the next release. If it is still an issue please reopen it. Thanks.

**Comment by Gizze** [comment]
Great! When will that be roughly? I am wondering whether in this case downgrading is necessary at all. Thanks for all the commitment.
Gizze
-- 
Sent from my Android phone with WEB.DE Mail. Please excuse my brevity.On 01/02/2017, 12:14 baumgarr <notifications@github.com> wrote:

  
    
      This should be fixed in the next release. If it is still an issue please reopen it. Thanks.

**Comment by baumgarr** [comment]
If people would quit opening tickets it would be out sooner.  ;-)

I don't like to make predictions because I'm always wrong. I had hoped to have a new release two weeks ago, but I'm guessing it will be another two until I get time to put all of the pieces together.

If you want to give me your email I can send you a pre-build binary. It would allow you to test that it works. I just need to know if you are using the Qt4 or Qt5 version and if you are using 32 or 64 bit. You could also use the ppa if you wish. That gets updated daily if there are any changes. The downside of either is that you run the risk of me having broken something else.

**Comment by Gizze** [comment]
baumgarr schrieb:
> If people would quit opening tickets it would be out sooner.  ;-)
Shame on me...

> I don't like to make predictions because I'm always wrong. I had hoped to have a new release two weeks ago, but I'm guessing it will be another two until I get time to put all of the pieces together.

I promise I won't file another ticket.

> If you want to give me your email I can send you a pre-build binary. It would allow you to test that it works. I just need to know if you are using the Qt4 or Qt5 version and if you are using 32 or 64 bit. You could also use the ppa if you wish. That gets updated daily if there are any changes. The downside of either is that you run the risk of me having broken something else.
> 

Having an up-to-date binary would be awesome. I use the Qt4 (4.8.6)
version in 64 bit on SuSE Linux. My email is shoppa0815@web.de .
Thanks for all the work which you invest here.

Gizze

**Comment by baumgarr** [comment]
It should be on its way. I edited the above post to remove your email. Let me know how it works.

Thanks.

**Comment by Gizze** [comment]
Hm...
I still see the same behaviour with the new version 2.0_beta11+git20170130.

**Comment by baumgarr** [comment]
I just uploaded the fix last night. I also sent you a binary that should have corrected it.

**Comment by Gizze** [comment]
I tried this new binary.
Its About note gives me 2.0_beta11+git20170130.
These are the startup messages at the command line:
nixnote2: /usr/lib64/libcurl.so.4: no version information available (required by nixnote2)
DEBUG 2017-02-03 23:47:46.080 ( gui/shortcutkeys.cpp @ 205 ) Loading system shortcuts from  "/usr/share/nixnote2/shortcuts.txt" 
DEBUG 2017-02-03 23:47:46.082 ( gui/shortcutkeys.cpp @ 207 ) Loadng user shortcuts from  "/home/gizze/.nixnote/shortcuts.txt" 
DEBUG 2017-02-03 23:47:46.082 ( gui/shortcutkeys.cpp @ 238 ) Unable to open file for reading or file does not exist. 

The old binary yields the same version in the About note: 2.0_beta11+git20170130, but the very first startup message about libcurl without version information does not show up:
DEBUG 2017-02-03 23:50:18.964 ( gui/shortcutkeys.cpp @ 205 ) Loading system shortcuts from  "/usr/share/nixnote2/shortcuts.txt" 
DEBUG 2017-02-03 23:50:18.965 ( gui/shortcutkeys.cpp @ 207 ) Loadng user shortcuts from  "/home/gizze/.nixnote/shortcuts.txt" 
DEBUG 2017-02-03 23:50:18.965 ( gui/shortcutkeys.cpp @ 238 ) Unable to open file for reading or file does not exist. 

I am really using two different versions here with different file sizes:
ll /usr/bin/nixnote2*
-rwxr-xr-x 1 root root 5585032 Feb  3 20:55 /usr/bin/nixnote2
-rwxr-xr-x 1 root root 5622000 Jan 31 17:41 /usr/bin/nixnote2_bak

I feel we are close but not quite there yet. Sorry about this.

**Comment by baumgarr** [comment]
The help/about is just reading from an HTML file. Part of the build process updates that file. Since I didn't send you a new one it will still have the old information. When you start up the GUI, the messages should tell you the date & time that the last full build was done. If that says Feb. 2, then you have the right module.

The libcurl message confuses me, but it may be that I accidentally did a debug build rather than a release and it is looking for information that isn't available. It isn't one of my messages, but it doesn't look like it hurt anything (at least it kept running). 

Did the import work?

**Comment by Gizze** [comment]
Unfortunately, the import did not work yet. Even with the new version (and I am sure I use the new one) I get the old error message
gizze@hm-linux:~> nixnote2 import --input=test_export.nnex
nixnote2: /usr/lib64/libcurl.so.4: no version information available (required by nixnote2)
DEBUG 2017-02-04 11:00:47.370 ( gui/shortcutkeys.cpp @ 205 ) Loading system shortcuts from  "/usr/share/nixnote2/shortcuts.txt" 
DEBUG 2017-02-04 11:00:47.371 ( gui/shortcutkeys.cpp @ 207 ) Loadng user shortcuts from  "/home/gizze/.nixnote/shortcuts.txt" 
DEBUG 2017-02-04 11:00:47.371 ( gui/shortcutkeys.cpp @ 238 ) Unable to open file for reading or file does not exist. 
QWidget: Cannot create a QWidget when no GUI is being used
Aborted (core dumped)
gizze@hm-linux:~> 

When I switch to debug verbosity level in the GUI I see that this is the new executable:
DEBUG 2017-02-04 11:02:45.572 ( main.cpp @ 174 ) Built on  Feb  2 2017  at  21:44:31 
DEBUG 2017-02-04 11:02:45.572 ( main.cpp @ 175 ) Built with Qt 4.8.6 running on 4.8.6 
DEBUG 2017-02-04 11:02:45.573 ( main.cpp @ 231 ) Setting up NN

The command-line invocation does not produce as much debug information, though. Is there a command-line switch perhaps that would give us more insight into what's happening here?

The testcase to reproduce this problem is fairly easy by the way: Just create a simple note, export it and try to import again.

**Comment by baumgarr** [comment]
I think I had a problem with my automated build process. I sent you another one so please give it a try.

Thanks.

**Comment by Gizze** [comment]
This executable works fine! Thanks a lot for your quick help. I appreciate it a lot!
