### ISSUE TITLE
ppa nixnote2-daily for beta-11

### ISSUE THREAD

**Issue by raven2cz** [baumgarr/nixnote2#267]
Hello,
I have in ubuntu:
http://ppa.launchpad.net/nixnote/nixnote2-daily/ubuntu xenial InRelease

but there is still old beta-10. Is it possible to provide beta-11?
I don't want to use downloading of deb. This provides more flexible way.
Thanks for help.

**Comment by artmg** [comment]
Hi,

Thanks for reporting this. As the downstream maintainer of the daily PPA package I have just _fixed this **apparent** versioning issue_, but I want to clarify a couple of points to any daily PPA users:

* the **changelog version** on the daily PPA is purely superficial and has nothing to do with the functionality in the package
* users of the daily PPA always get **the very latest code**, including any new bugs that are introduced unintentionally. You are right that this is more flexible, but you must understand that daily changes can temporarily break some features.
* you can see when your installed version was last rebuilt by checking **Help / About** in the nixnote2 menu, where you will see something like `nixnote2-daily+20170201` - this is the **only** _version_ that affects the functionality in the daily PPA.

The nixnote2-daily PPA automatically rebuilds every time there are changes to the main source code. If you do not have automatic updates enabled, you can update manually to the latest daily built using the command `sudo apt-get install nixnote2`. Yes I know it says _install_, but that makes sure that particular package is up to date from the repos you have chosen.

People who want a more stable version should install the deb from another location. @baumgarr puts in a lot of effort to ensure that his formal beta releases have been Quality Assured (QA). Others may prefer to take the risk and get the latest functionality, and like you enjoy the simpler option of trusting the PPA to deliver the very latest code. Unfortunately this does not automatically copy forward the changelog every time baumgarr does his formal beta release, and I have not had the time to fix the [underlying downstream issue](https://github.com/artmg/nixnote2-packaging/issues/17)

However I have now manually updated the changelog so it appears in sync with the main project. Again, thanks for reporting this

**Comment by artmg** [comment]
after using Software Updater (or `sudo apt-get install nixnote2`) the version reported by `dpkg -s nixnote2` is
```
2.0-beta-11-0+883+48+201702031316~ubuntu16.10.1
```
aka `nixnote2-daily+20170203` (from Help / About).
Issue ready to Close - thanks
