### ISSUE TITLE
Tray Icon Behavior Ubuntu

### ISSUE THREAD

**Issue by mohadib** [baumgarr/nixnote2#269]
Helllo,

 Using nixnote2-daily+20170205 in Ubuntu. I have "Show/Hide NixNote" selected for "Tray Icon Click Action". No matter what I select I still always get a drop down with options like "New Note", or "Show/Hide". I always want to show NixNotes when I click that icon.

![image](https://cloud.githubusercontent.com/assets/5350023/22790888/d67c8d26-eea4-11e6-9ed4-6c97fa1a723b.png)

**Comment by baumgarr** [comment]
I can't recreate this and I've tried on a couple of different systems. 

Look in ~/.nixnote/nixnote-1.conf.  Look for the settings "trayMiddleClickAction" & "trayMiddleClickAction". What are those values set to?

**Comment by mohadib** [comment]
in  ~/.nixnote/nixnote-1.conf  I have nothing for trayMiddleClickAction or trayMiddleClickAction.
In ~/.nixnote/nixnote-3.conf I have both and they are both set to 0.

```
jdavis@jdavis-desktop ~/.nixnote $ ls
accounts.conf  db-1  db-3  logs-1  logs-3  nixnote-1.conf  nixnote-3.conf  nixnote.conf  qss  spell  tmp-1  tmp-3
jdavis@jdavis-desktop ~/.nixnote $ grep tray *.conf
nixnote-3.conf:trayMiddleClickAction=0
nixnote-3.conf:traySingleClickAction=0
```

**Comment by baumgarr** [comment]
The zero says it should be a show/hide for a left click & middle click. Even if you didn't have it, those are the default values. The only thing that should show the context menu is a right click.

Something is intercepting the trigger & changing it to a context menu action. I've tried on 5 different machines running different distributions (including 2 that were Ubuntu) and one Windows but I haven't been able to recreate it.

I'll leave this open for a little while to see if anything comes to me, but unless I can recreate it there isn't anything I can do. Sorry.

**Comment by sleidig** [comment]
I am experiencing the same issue on my Ubuntu 16.04 system. Any click on the tray icon will only show the context menu regardless of the settings.

**Comment by mohadib** [comment]
Might we worth mentioning I'm using the XFCE desktop environment on Ubuntu.

**Comment by baumgarr** [comment]
I don't think there is anything I can do to resolve this. I have an option in 2.0.1 that allows for a double click that may help (but you want to disable the single click first). The problem is that the window manager is sending the right-click action regardless of what button is actually clicked. I have no way of determining what button is actually clicked.

Sorry.
