### ISSUE TITLE
Unable to update note. Invalid note structure

### ISSUE THREAD

**Issue by Agamennon** [baumgarr/nixnote2#27]
I am getting : Unable to update note. Invalid note structure when i try to sync, i am not sure what note is the offending one as there is no information

thanks for the program!  hope i can use it again

**Comment by poetimp** [comment]
I am likewise getting this error and have followed #14 with no luck in identifying the offending note. To aid in troubleshooting, would it be possible to add the title of the note to the error message seen in the console? 

Here is what I am seeing on 2.0 Beta 3:

```
$ nixnote2
DEBUG 2015-07-06 22:37:53.689 ( global.cpp @ 84 ) Shared memory key:  "1b73cc55-9a2f-441b-877a-ca1d0131cd21"
 INFO 2015-07-06 22:37:53.690 ( main.cpp @ 139 ) Built with Qt 4.8.6 running on 4.8.6
 INFO 2015-07-06 22:37:55.096 ( nixnote.cpp @ 1554 ) "Beginning Sync"
ERROR 2015-07-06 22:37:55.331 ( communication/communicationmanager.cpp @ 488 ) EDAMUserException: 11

 INFO 2015-07-06 22:37:55.332 ( nixnote.cpp @ 1554 ) "Unable to update note.  Invalid note structure : "
 INFO 2015-07-06 22:37:55.332 ( nixnote.cpp @ 1554 ) "Unable to update note.  Invalid note structure : "
```

**Comment by justyn** [comment]
I hate to just post +1 to @poetimp , but I so frequently get "Unable to update note: Invalid note structure" that I too would really love to see it tell me which note right away, it would save me a lot of time.

**Comment by baumgarr** [comment]
Upgrade to beta 4 and see if it helps.  There were some changes that, depending on the reason, should correct this.

**Comment by baumgarr** [comment]
No response.  Closing.
