### ISSUE TITLE
Broken runtime dir deduction in global.cpp

### ISSUE THREAD

**Issue by hosiet** [baumgarr/nixnote2#274]
`Global::getProgramDirPath()` in `global.cpp` is mostly broken for a non-standard prefix.

```cpp
// Return the path the program is executing under
// If we are in /usr/bin, then we need to return /usr/share/nixnote2.
// This is because we want to find other paths (like images).  This
// allows for users to run it out of a non-path location.
QString Global::getProgramDirPath() {
    QString path = QCoreApplication::applicationDirPath();
    if (path == "/usr/bin")
        return "/usr/share/nixnote2";
    if (path == "/usr/share/bin")
        return "/usr/share/nixnote2";
    if (path == "/usr/local/bin")
        return "/usr/share/nixnote2";
    return path;
}
```

* Oh there is nothing like `/usr/share/bin`. `/usr/share` only stores architecture-independent files.
* I believe we should return "/usr/local/share/nixnote2" rather than "/usr/share/nixnote2" for the last one.

Actually the path deduction should be based on $prefix if my understanding is correct. If current executable dir is "$prefix/bin/", then we should return "$prefix/share/nixnote2". This will work under any situation.

**Comment by baumgarr** [comment]
I've changed the logic to do $prefix/share/nixnote2.
