### ISSUE TITLE
Strange Â character in some notes. Html encoding problem?

### ISSUE THREAD

**Issue by fivef** [baumgarr/nixnote2#277]
I use beta 11 and in some notes I see strange Â characters instead of some spaces.
In the nixnote source view this character is `Â&nbsp;`

I found a stackoverflow question related to this:
http://stackoverflow.com/questions/1461907/html-encoding-issues-%C3%82-character-showing-up-instead-of-nbsp

In evernote web:
![evernote_strange_character](https://cloud.githubusercontent.com/assets/1077593/22972551/5e2e68fa-f37a-11e6-86f8-ff1b434b5eaa.png)

In nixnote:
![nixnote2_strange characters](https://cloud.githubusercontent.com/assets/1077593/22972556/6437103a-f37a-11e6-8c81-44be17e58bf4.png)

**Comment by baumgarr** [comment]
Try going into the Edit/Preferences dialog. Look under the "Debugging" tab. Make sure "Force UTF-8" encoding is enabled. You may need to restart NixNote to see any differences. If that doesn't correct it then try editing it on Evernote's web interface & syncing again to get a fresh copy. 

Let me know if that doesn't help.

Thanks.

**Comment by fivef** [comment]
Thanks,
Enabling Force UTF-8 and restarting NixNote worked!

**Comment by baumgarr** [comment]
Good. I should probably make that the default option, but I'm always hesitant to enable things like that until I'm sure I'm not causing more issues than I solve.

Thanks for letting me know it worked!

**Comment by luiszandonadi** [comment]
Thanks, Enabling Force UTF-8 and restarting NixNote worked!
