### ISSUE TITLE
Feature Request: Setting the config directory via cmd line

### ISSUE THREAD

**Issue by MarcMil** [baumgarr/nixnote2#278]
Currently, the directory under which NixNote2 saves its settings is fixed to
```
homeDirPath = QDir().homePath() + QString("/.nixnote/")
````

It would be nice to support something like a --configdir command line option to override the default location. This would make it possible to use Evernote portable on a USB-Stick.

**Comment by baumgarr** [comment]
Why not setup a symbolic link? Then you don't need to pass a command line parameter.

**Comment by MarcMil** [comment]
Sadly, under Windows, NixNote does not start when setting up a symbolic link instead of a real directory.

**Comment by baumgarr** [comment]
Simple enough change. It should be in the next release.
