### ISSUE TITLE
Notification bubble shows partly off-screen in Gnome 3

### ISSUE THREAD

**Issue by fastcat** [baumgarr/Nixnote2#28]
Same problem as haiwen/seafile-client#92 -- Because of how Gnome positions the message tray, the bubble gets drawn half off the screen where it's not visible :(

Replacing the bubbles with libnotify notifications seems to be one common solution to this type of issue.  I suppose forcing the bounds of the bubble window are within the screen geometry might be another way.

**Comment by baumgarr** [comment]
The next release will have an option under Preferences to switch from Qt's notification to notify-send.  Please re-open this ticket if this doesn't correct the problem.
