### ISSUE TITLE
Failed Renaming of Saved Searches - Capitalization of name seen as equal

### ISSUE THREAD

**Issue by davidswords** [baumgarr/nixnote2#283]
When renaming a saved search I have noticed the following:

Original name: wkr:TEST
Changed to: wkr:test

When clicked away, to save the name change, saved search remains labeled as wkr:TEST.

**Comment by baumgarr** [comment]
That's an old thing I forgot from a long time ago. Thanks for the reminder. A simple workaround is to rename it to something different, then rename it back.

**Comment by davidswords** [comment]
No problem.
Yeah, that's what I ended up doing.

**Comment by baumgarr** [comment]
Fixed in the next release
