### ISSUE TITLE
Nixnote fails to start after upgrade to Ubuntu 16.10

### ISSUE THREAD

**Issue by mkowske** [baumgarr/nixnote2#285]
I upgraded to 16.10 yesterday from 16.04 LTS and nixnote has refused to launch now. I have tried both the .deb file from sourceforge.net site and adding the DailyPPA repo and installing from there. Here is the error I get when trying to start:

DEBUG 2017-02-24 09:02:23.851 ( gui/shortcutkeys.cpp @ 244 ) Unable to open file for reading or file does not exist. 
Error: signal 11:
nixnote2(_Z13fault_handleri+0x2e)[0x5568ae2a5d4e]
/lib/x86_64-linux-gnu/libc.so.6(+0x35860)[0x7fafe9800860]
Error: signal 11:
nixnote2(_Z13fault_handleri+0x2e)[0x5568ae2a5d4e]
/lib/x86_64-linux-gnu/libc.so.6(+0x35860)[0x7fafe9800860]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN7QObject10disconnectEPKS_PKcS1_S3_+0x27f)[0x7fafea6f071f]
/usr/lib/x86_64-linux-gnu/libQt5DBus.so.5(+0x28610)[0x7fafd4f9e610]
/usr/lib/x86_64-linux-gnu/libQt5DBus.so.5(+0x156c2)[0x7fafd4f8b6c2]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(+0xadc68)[0x7fafea4e7c68]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ca)[0x7fafe81f46ca]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x5f)[0x7fafe98d30af]

The DEBUG message is new with the repo build. I didn't get that when starting with the .deb file from the website.

**Comment by baumgarr** [comment]
The first thing I'd try is to remove any of the nixnote plugins. 

If that doesn't work, rename ~./nixnote/nixnote-1.conf to something else & try to restart. That will restart your settings, but you should still have the same database.

If that doesn't work I'd try renaming the ~./nixnote/db-1 directory. When it starts you'll get a new database. If that corrects it, then your database is probably corrupt. If that doesn't fix it then you can rename the directory back.

If nothing else I'd try to build it from the source in case there is something odd about your Qt setup.

**Comment by mkowske** [comment]
Sorry, but where are the plugins located? I don't think I installed any.

I did try your other two renaming suggestions and no change so I will 
try a source compile.

**Comment by mkowske** [comment]
Is there a guide on how to build from source out there? I've been trying 
for an hour... I've built packages from source before but not java based.

**Comment by baumgarr** [comment]
If you look in the help directory you'll find a user manual that has some instructions.

I didn't think the plugins were the issue, but it never hurts to eliminate one possibility. I really don't think it is getting that far.

You don't need to worry about the Java piece of NixNote. That is only needed if you want to encrypt or decrypt note text. Without it you'll just see the icon indicating that text is encrypted.

Whatever is happening it is happening very early in the startup. From the stack dump it doesn't even look like it is starting the main NixNote code before ending. It acts like some type of library incompatibility or corrupt library.

**Comment by mkowske** [comment]
I thought this might have been an overall QT5 issue, but I am able to use other QT5 applications (qtcreator) for example.

**Comment by baumgarr** [comment]
If you have Qt Creator, then I'd open the NixNote.pro in that it. Compile it using a debugging profile and launch it. It should stop at the line that is having the error.

**Comment by baumgarr** [comment]
No response. Closing issue.
