### ISSUE TITLE
Performance issues when there are many tags

### ISSUE THREAD

**Issue by kaikramer** [baumgarr/nixnote2#289]
My notebook has around 1600 notes and more than 1000 tags. 

Whenever I click on a note, it takes more than a second until it is finally shown. According to the log all this time is spent loading the tag names for the completer:
```
TRACE 2017-02-25 15:07:29.255 ( ..\nn2\gui\browserWidgets\tageditornewtag.cpp @ 88 ) Entering loadCompleter : 15TagEditorNewTag 
TRACE 2017-02-25 15:07:30.604 ( ..\nn2\gui\browserWidgets\tageditornewtag.cpp @ 116 ) Exiting loadCompleter : 15TagEditorNewTag 
```
After deleting all the tags the performance is fine, but that's not really a solution.

OS: Windows 8.1
NixNote version: 2.0-beta12 (Built on  Feb 12 2017  at  09:54:10)

**Comment by baumgarr** [comment]
With that many tags I'm surprised it is that fast.

Thanks for the trace. I'll see what I can do.

**Comment by baumgarr** [comment]
Can you provide your email? I'll give you an experimental build that may help.

**Comment by kaikramer** [comment]
Sure: kai.kramer@gmail.com

**Comment by baumgarr** [comment]
It should be on its way. I edited your above comment to remove your email.

**Comment by kaikramer** [comment]
Nothing in inbox so far, nothing in spam folder either.

**Comment by baumgarr** [comment]
Weird. Try downloading this one.

[nn2.zip](https://github.com/baumgarr/nixnote2/files/819812/nn2.zip)

**Comment by kaikramer** [comment]
Performance is perfectly fine now. Thank you!

**Comment by baumgarr** [comment]
Great. Thanks.
