### ISSUE TITLE
[Enhancement] Option to only show notifications for sync errors

### ISSUE THREAD

**Issue by fastcat** [baumgarr/Nixnote2#29]
Being notified of sync errors is nice (esp. given Evernote's frequent "you're talking to us too much" rate limiting responses), but being notified about automatic/periodic successful syncs is often noise.

So, making sync notifications be a tri-state (e.g. "Never", "Errors", "Always") instead of a boolean on/off would be a nice enhancement.

**Comment by baumgarr** [comment]
Should be in the next beta.
