### ISSUE TITLE
Always Start minimized

### ISSUE THREAD

**Issue by komitaltrade** [baumgarr/nixnote2#291]
Hi again.

(Linux Mint 18.1 x64 Cinnamon)

First, compliments. It works indeed great.

Small issue I found. Always Start minimized option with (+) Minimize to tray checked not works as it should to be by description.

- Now, it start MINIMIZED TO TASKBAR and tray icon is activated (issue is - if in session you didn't useed NixNote, session can't be closed vs opened NixNote).

- Description of Preferences indicated that it should to start minimized to tray (not taskbar), so, like when in Thunderbird works FireTray (same have CherryTree).

So, I agree that single checked preferences doing what they should to do, but combination not. It will be nice if you can fix it.

**Comment by baumgarr** [comment]
Sorry. I'm not understanding what you are saying.

On the first one, are you saying that if it is set to minimize to tray that you cannot use the tray icon if you have start minimized & minimize to tray set? If you are saying that the tray icon isn't appearing then there isn't anything I can do about that. Some window managers don't support the Qt tray icon (or Qt doesn't support them). I cannot control that. I attempt to check at startup and if it definitely isn't supported it won't minimize to the tray icon regardless of what you specify. That is an attempt to keep it from vanishing, but sometimes the combination of Qt & the window manager report incorrectly that the tray icon is supported even when it isn't. Unfortunately there isn't anything I can do about that.

On the second one I don't see any problem. The minimize to tray & start minimized really don't impact each other. The minimize to tray states what should happen whenever NixNote is minimized (either minimize normally to the taskbar or to a tray icon. The other states how it should startup. If you want it to automatically start in a minimized state or to restore the previous window size. If both are specified (and the window manager supports it), NixNote will start minimized to the tray icon.

**Comment by komitaltrade** [comment]
1) I attached settings (NixNote is 01.png and CherryTree is 02.png).
A) First issue
2) I attached screencast, where you can see:
- Taskbar (left) shows only NixNote )open by settings) and Firefox opened (as I open it). Apps with similar functionality (Thunderbird and CherryTree you can see that they start minimized in Tray (right) but they are not open in Taskbar (left) - and that’s how it should to be.
- Tray (right) you can see (as I already wrote) Thunderbird (FireTray add-on), CherryTree (by settings) and NixNote (by settings).
B) Second issue (main)
Above will not be important as fact that NixNote (if remain unused) will not block the system shutdown. So, if I didn't used during session NixNote at all it mean that dialogue will remain open and it prevent system from shutdown. To fix it, I must to shutdown (exit) NixNote manually (what is annoying).

I hope that it is clear now.
![01](https://cloud.githubusercontent.com/assets/9955962/23519326/752026cc-ff44-11e6-9c1c-ac16d97c070d.png)
![02](https://cloud.githubusercontent.com/assets/9955962/23519325/751c3bb6-ff44-11e6-9f85-0ba720cbe30a.png)
![screencast](https://cloud.githubusercontent.com/assets/9955962/23519588/779a27e4-ff45-11e6-97e4-75367f1e2cd4.gif)

**Comment by baumgarr** [comment]
Thanks for the clarification. It is weird that I can't reproduce the minimize part on KDE, but I was able to reproduce it on Windows. I think I have it fixed.
