### ISSUE TITLE
Login failed: Error creating SSL context()

### ISSUE THREAD

**Issue by erch** [baumgarr/nixnote2#293]
On Windows when I try the first synchronize I got this error: 
Login failed: Error creating SSL context()

Any idea of what the problem is ?

Thanks
Eric

**Comment by baumgarr** [comment]
Someone else was having the same issue. I uploaded a copy of the SSL libraries here: https://sourceforge.net/projects/nevernote/files/NixNote2%20-%202.0/Windows%20-%20Beta%2013/

Take the DLL files there and copy them to the same directory as the NixNote executable. Recycle NixNote and give it a try. Let me know if it helps.

Thanks.

**Comment by erch** [comment]
Thanks very much , it works with the addition of the ssl lib.

Eric

**Comment by baumgarr** [comment]
Great!  Thanks for letting me know. I'll include them in the next release.
