### ISSUE TITLE
Unable to update note.  Invalid note structure

### ISSUE THREAD

**Issue by petRUShka** [baumgarr/nixnote2#294]
After editing my note I've come to that problem during sync:

```
INFO 2017-03-02 11:06:54.598 ( nixnote.cpp @ 1880 ) "Unable to update note.  Invalid note structure : :EDAMUserException: ENML_VALIDATION parameter=Attribute "data-address" must be declared for element type "span"." 
```

nixnote2-2.0-4 for ArchLinux AUR.

**Comment by baumgarr** [comment]
How was rhe note created?

**Comment by petRUShka** [comment]
There was note created in Nixnote2. Some content of the note was pasted in from Web. After deleting some blank lines (possibly with some not visible tags inside) syncing became working as expected. 

I have deleted duplicate of that not-syncing note, so If I have opportunity to view HTML-code of a note I can try to extract problem block from my note.

**Comment by baumgarr** [comment]
Pasting between a web browser & NixNote is problematic due to the fact that HTML can be badly formed & Evernote doesn't permit all HTML tags. 

See issue #295 for more information.

**Comment by HaleTom** [comment]
I'm getting the same error, but twice:

```
 INFO 2017-03-18 13:01:44.320 ( nixnote.cpp @ 1866 ) "Beginning Sync" 
 INFO 2017-03-18 13:01:44.326 ( nixnote.cpp @ 1866 ) "Downloading changes" 
 INFO 2017-03-18 13:01:44.633 ( nixnote.cpp @ 1866 ) "Download 0% complete for notebooks, tags, & searches." 
 INFO 2017-03-18 13:01:44.634 ( nixnote.cpp @ 1866 ) "Download complete for notebooks, tags, & searches.  Downloading notes." 
 INFO 2017-03-18 13:01:45.683 ( nixnote.cpp @ 1866 ) "Download 0% complete." 
 INFO 2017-03-18 13:01:46.485 ( nixnote.cpp @ 1866 ) "Download complete." 
ERROR 2017-03-18 13:01:47.433 ( communication/communicationmanager.cpp @ 557 ) EDAMUserException: 11 
ERROR 2017-03-18 13:01:47.434 ( threads/syncrunner.cpp @ 1149 ) "Error uploading note:Conscious relationships discussion group facebook posting" 
 INFO 2017-03-18 13:01:47.435 ( nixnote.cpp @ 1866 ) "Unable to update note.  Invalid note structure : :EDAMUserException: ENML_VALIDATION parameter=Attribute "data-testid" must be declared for element type "span"." 
 INFO 2017-03-18 13:01:48.863 ( nixnote.cpp @ 1866 ) "Unable to update note.  Invalid note structure : :EDAMUserException: ENML_VALIDATION parameter=Attribute "data-testid" must be declared for element type "span"." 
```
Setting "Force UTF8 Encoding" as per #295 makes no difference.

How do I find out which note(s) have this issue?

**Comment by baumgarr** [comment]
In this case, look for the note with the title "Conscious relationships discussion group facebook posting"

To correct the issue you can do a choose the option "View Source" & look for a <span> tag with the attribute of "data-testid".

**Comment by HaleTom** [comment]
I totally n00bed on reading all lines in that error message. Thanks for your patience with me, I'm sure it will help future googlers.

**Comment by baumgarr** [comment]
No​ problem. There can be a lot of messages and it is easy to overlook things.
