### ISSUE TITLE
certain images of notes not shown after a search

### ISSUE THREAD

**Issue by somhi** [baumgarr/nixnote2#297]
Ubuntu 16.04 / nixnote2-2.0_amd64.deb Qt5

I've experienced problems viewing attached images of notes after searching them. 
When I see the note in it's notebook the image is shown fine, but when I do a search of the note, instead of the image I've got a little image icon with an interrogative symbol. 
It's strange behaviour because it's doesn't happens always. Let's say 50% of times and I would say that it only happens to .jpg files (which in reality are png images) but not all jpg images.

**Comment by baumgarr** [comment]
I can't recreate this.

What do you mean when you say ".jpg files (which are really png images)"?

When it happens, can you do view the source & do a cut & paste into this issue so I can see if it is something that is strange about the HTML that is being created?

**Comment by somhi** [comment]
In a particular note ("humitats casa" for my reference) I have two images.  Both images are saved at /home/jordi/.nixnote/db-1/dba folder with .jpg extension (180.jpg, 182.jpg), but both files start with 0x89 0x50 which mean are in reality PNG images.   When I export an image from evernote web interface it also exports it as .jpg but the file start also with 0x89 0x50 so it's an Evernote issue.

When I go the the notebook and view the note, I can see always both images. This is the source code. Notice the two files are .jpg.
<div><img hash="21b704727aaafb77f8901c0bffe0dd1d" type="image/jpeg" src="file:////home/jordi/.nixnote/db-1/dba/180.jpg" oncontextmenu="window.browserWindow.imageContextMenu('180', '180.jpg');" en-tag="en-media" lid="180"><img hash="5262af369248e786c844b0d2501963f2" type="image/jpeg" src="file:////home/jordi/.nixnote/db-1/dba/182.jpg" oncontextmenu="window.browserWindow.imageContextMenu('182', '182.jpg');" en-tag="en-media" lid="182"></div>

When I searched for the note above, and clicked in the search results, I could only see the 182.jpg image. This is right if you see the html code below of the note as the file 180.png doesn't exist.
<div><img hash="21b704727aaafb77f8901c0bffe0dd1d" type="image/jpeg" src="file:///home/jordi/.nixnote/tmp-1/180.png" oncontextmenu="window.browserWindow.imageContextMenu('180', '180.jpg');" en-tag="en-media" lid="180"><img hash="5262af369248e786c844b0d2501963f2" type="image/jpeg" src="file:////home/jordi/.nixnote/db-1/dba/182.jpg" oncontextmenu="window.browserWindow.imageContextMenu('182', '182.jpg');" en-tag="en-media" lid="182"></div>

Another search and I could see both images because in source code both appeared as .jpg

Another search and now I didn't see any image. Both were .png in the source code.
<div><img hash="21b704727aaafb77f8901c0bffe0dd1d" type="image/jpeg" src="file:///home/jordi/.nixnote/tmp-1/180.png" oncontextmenu="window.browserWindow.imageContextMenu('180', '180.jpg');" en-tag="en-media" lid="180"><img hash="5262af369248e786c844b0d2501963f2" type="image/jpeg" src="file:///home/jordi/.nixnote/tmp-1/182.png" oncontextmenu="window.browserWindow.imageContextMenu('182', '182.jpg');" en-tag="en-media" lid="182"></div>

Really strange behaviour.

**Comment by baumgarr** [comment]
Thanks for the explanation. 

I think what is happening is that Qt is getting confused because the extension doesn't match the contents.

When you do an image search, to color the results it creates a copy of the original image overlaid with the yellow highlight. I'm guessing that Qt is guessing incorrectly at the file type based on the extension, so it is trying to read a JPG but getting garbled data because it is a PNG. 

Try replacing the nixnote2 binary with this version to see if it helps. I'm probing the first few bytes of the file to try and force the file type. Make a backup of the existing nixnote2 in case this makes things worse.

[nn2.tar.gz](https://github.com/baumgarr/nixnote2/files/826114/nn2.tar.gz)

**Comment by somhi** [comment]
Just tried it now and at the moment is working well.   Thanks ;)

**Comment by baumgarr** [comment]
Great. Thanks.
