### ISSUE TITLE
Translation updates and typo fixes before next release

### ISSUE THREAD

**Issue by hosiet** [baumgarr/nixnote2#299]
Opening this issue so that we could make some check before next release.

I am updating zh_CN translation now and found multiple typos. Will file a PR soon. Please wait till I finish the PR before declaring next release.

**Comment by baumgarr** [comment]
No problem. I don't think I'll be ready before next weekend so take your time. If you need longer than that it is no big deal.

**Comment by hosiet** [comment]
Fixed via #300.
