### ISSUE TITLE
Unable to sync: Bad data format

### ISSUE THREAD

**Issue by fastcat** [baumgarr/nixnote2#30]
I'm getting this error on *one* instance of nixnote2, each time I try to sync.  I have two other instances running on other PCs, and they appear to be syncing fine.  The most notable difference is that the one that is failing had been "off" for a few days, so it has more stuff to catch up on.

```
DEBUG 2014-09-26 19:53:19.980 ( threads/syncrunner.cpp @ 50 ) Starting SyncRunner.synchronize() 
TRACE 2014-09-26 19:53:19.981 ( threads/syncrunner.cpp @ 90 ) Sync thread: 140540083119872 
DEBUG 2014-09-26 19:53:19.981 ( communication/communicationmanager.cpp @ 143 ) Inside CommunicationManager::getUserInfo 
DEBUG 2014-09-26 19:53:20.612 ( threads/syncrunner.cpp @ 126 ) --->>>  Current Chunk High Sequence Number:  5165 
DEBUG 2014-09-26 19:53:20.612 ( threads/syncrunner.cpp @ 127 ) --->>>  Last User High Sequence Number:  5165 
DEBUG 2014-09-26 19:53:20.612 ( communication/communicationmanager.cpp @ 143 ) Inside CommunicationManager::getUserInfo 
 INFO 2014-09-26 19:53:20.612 ( nixnote.cpp @ 1564 ) "Beginning Sync" 
ERROR 2014-09-26 19:53:21.210 ( communication/communicationmanager.cpp @ 366 ) EDAMUserException: 2 

 INFO 2014-09-26 19:53:21.210 ( nixnote.cpp @ 1564 ) "Unable to sync. Bad data format : " 
 INFO 2014-09-26 19:53:21.210 ( nixnote.cpp @ 1564 ) "Unable to sync. Bad data format : " 
```

I'm running a local build from source of 7a8d85673fb6984838d056c2e21e05d2a38aa01b

**Comment by gi0rgi0ne** [comment]
I have the same error, but it appeared without changing any sharing-properties. Is there a fix for this error?

**Comment by baumgarr** [comment]
I'm not sure if it will help, but could you try beta 4 to see if it alters the behavior?  If you have any notes that won't sync please edit them under beta4 & re-save them.  You just need to put a space in the note to force a save.  I want to see if some of the saving logic cleans them up.

Thanks.

**Comment by baumgarr** [comment]
No response.  Closing.
