### ISSUE TITLE
daily build fails on tidy/tidy.h in enmlformatter.cpp

### ISSUE THREAD

**Issue by artmg** [baumgarr/nixnote2#301]
The last successful daily build was nixnote2-daily+20170220. Since then the build has tried and failed a couple of times with the following error
```
html/enmlformatter.cpp:32:23: fatal error: tidy/tidy.h: No such file or directory
```
For reference I have [a downstream issue logged](https://github.com/artmg/nixnote2-packaging/issues/25)

I suspect this is because ubuntu tidy package does NOT need the `tidy/` path prefix, but I'm trying to understand the recent changes around **tidy** to understand the best way to deal with this. Any guidance gratefully welcomed. Cheers

**Comment by hosiet** [comment]
I just tried to rebuild against d5ac3887f08c259407a5f7cd0203c820b1d1c4da and finished successfully using instructions from 37b5a92ee4b7a81dbff7026f2 on Debian Unstable / Debian Stretch. The only change was to add `libtidy-dev` into Build-dep list.

Please pay close attention to the `libtidy` version you are building against to.

**Comment by artmg** [comment]
@hosiet that tree appears to give everything the Ubuntu Launchpad needs for building, superseding the contents of my nixnote2-packaging project. For now I can copy what you have there, which will get the build going. However, in the longer run, if this formal `debian` folder was a part of the main project then the build would just keep working automatically. Please let me know if this might be integrated into branch at any time
Many thanks!

**Comment by hosiet** [comment]
@artmg This might not be merged by upstream in near future. If you are building on Launchpad, I really doubt whether this src tree can pass building on Ubuntu <= 16.04.

**Comment by artmg** [comment]
I can see from [the ubuntu package history that tidy](http://packages.ubuntu.com/search?keywords=tidy) (and libtidt-dev) up to Xenial (16.04) was a radically different version than used with Yakkety and later. I am keeping my fingers crossed that the code will be compatible with both version-streams, otherwise it will become very difficult to maintain build that work with all current versions of Ubuntu. I'll report back once I have more results.

**Comment by artmg** [comment]
I'm happy to report that we now have a Nixnote2 daily build again across all ubuntu versions from Trusty LTS to Zesty alpha. Many thanks @hosiet for your valuable debian file resources ... merging these (with some of the older stuff for previous versions) really helped me stick this back together. Fortunately the "tidy" devs got their versioning to work seamlessly across ubuntu versions.

I'll close this issue for now, as the build is back again - if any users have issues with Nixnote2 installation from the Daily PPA, then we shall track them via a new issue

Thanks
