### ISSUE TITLE
Missing menu bar?

### ISSUE THREAD

**Issue by ilpepe** [baumgarr/nixnote2#302]
Hi,
I seem to be missing the menu bar in ubuntu 16.04 unity.
I'm supposed to be on the ppa, but I can't check the version...
I did a reinstall over ppa, without any luck.
Might I be missing dependencies?
Best regards,
Pieter

**Comment by hosiet** [comment]
Do check global menu settings on Unity DE. If the menu bar does not exist on either main window or Unity's global menu bar, this might be a bug. Several screenshots might be useful as well.

**Comment by ilpepe** [comment]
![image](https://cloud.githubusercontent.com/assets/8060194/23855280/638a2a02-07f5-11e7-804b-41b6bf19fa08.png)

**Comment by ilpepe** [comment]
![image](https://cloud.githubusercontent.com/assets/8060194/23855354/9b07b508-07f5-11e7-8c92-cd150f982625.png)
but changing the setting doesn't do a thing

**Comment by ilpepe** [comment]
somehow seems to be fixed. i didn't take any steps, be it for a reboot and an on and of of the screen above (in the menu bar to windiw's title bar and back)...
