### ISSUE TITLE
Unity Search Lens

### ISSUE THREAD

**Issue by sleidig** [baumgarr/nixnote2#303]
To improve my workflow I would love to have integration into the ubuntu unity search lens for my notes. Seems like the feature was dropped earlier ( #11 ). Any chance of getting this back? Or suggestions on how I might put in some work towards this myself?

**Comment by baumgarr** [comment]
I don't have any immediate plans to work on it. There were a few reasons that I stopped. 
- I don't use Unity myself. 
- There was the problem that at one point Unity Lenses needed to be written in Python, but then they switched to C++ for performance. 
- The documentation of how to write them isn't well done. 

If you want to resurrect it, the first thing I'd do is read up on how to do a Lense on Ubuntu's site. Once you are comfortable you could do the basic structure of it in C++. If you decide to do it then I can point you in the best way how to do it, but basically the best way to do it would be to use the cross memory feature in NixNote to determine if another instance is running & then do a query to view the results. The code in NixNote you'd want to examine is the command line interface. It would work similar to that . That is a vague answer, but if you want to dig into it then let me know & I'll give a more detailed answer.
