### ISSUE TITLE
issue with copying/pasting links

### ISSUE THREAD

**Issue by tomkc** [baumgarr/nixnote2#305]
It looks there's a problem with pasting text formatted as an hyperlink within the orginal note or between notes - it also doesn't matter if the text is formatted with bullet list. I also lost some data cause that bug, because undo/redo wasn't working properly for mentioned hyperlinks operations (when using cut). I'm using Nixnote 2.0-beta 11.

**Comment by baumgarr** [comment]
I can't recreate the issue, or I don't understand clearly what you are doing. Is this still an issue with the latest release?

**Comment by tomkc** [comment]
it's still an issue.Try copying some url from web browser in some note, hit enter (nixnote will format it as a hyperlink-blue text underlined), copy or cut it, and try to paste in to different note.

**Comment by baumgarr** [comment]
I think I may have fixed this with a commit I did in May. In any event, I can't recreate it with the latest builds. If it is still an issue after the next release let me know & I'll reopen this issue.
