### ISSUE TITLE
Sync behind proxy doesn't work since beta11

### ISSUE THREAD

**Issue by rocky7x** [baumgarr/nixnote2#306]
Hello,

Starting with beta11 (when qt version was split to 4 and 5) the sync from behind a proxy doesn't work anymore. The reason is that proxy cannot be turned on without turning on the Socks5 option. But our company proxy is not a socks5 proxy - I only need to turn on the proxy server and leave Socks5 option turned off. This strangely doesn't work - either both are turned on or off. Any idea?

**Comment by baumgarr** [comment]
I didn't write the proxy code & I don't have a proxy to test it with, but there is still a Qt-4 version out on SourceForge. That code hasn't changed in a while, so I don't think it has anything specific to the release number, maybe just how qt4 handles proxies compared to qt5?

**Comment by rocky7x** [comment]
Well, I see that since the split to qt4 and qt5, so starting with beta 11, there is an option to use socks 5 proxy which wasn't there before. So there must have been a change in the proxy code. And I think that introduction of this option broke it. The thing is, that since beta 11 neither qt4 not qt5 works with proxy.

**Comment by baumgarr** [comment]
Sorry, I don't remember those changes to the proxy logic (probably because I didn't do the changes). :)

I think I have it fixed for the next release. If you need it sooner than that let me know and I'll send you an early build.

**Comment by caspertone2003** [comment]
Problem not solved in windows 2.0-beta12
Thanks
