### ISSUE TITLE
Sync failing - "API rate limit exceeded"

### ISSUE THREAD

**Issue by glansberry** [baumgarr/nixnote2#307]
New install on a fresh ubuntu 16.04 on i386.  Plenty of ram and hard drive space.  I've got a large amount of notes stored in evernote.  I only have been able to download those that come prior to 2014, all newer notes are not downloaded.  Next to most notebooks I see something like (0/55) , or (0/4) I think this means how many notes have been downloaded vs how many are in the cloud.

Here's the log:
INFO 2017-03-18 16:02:07.317 ( nixnote.cpp @ 1880 ) "Beginning Sync" 
 INFO 2017-03-18 16:02:07.318 ( nixnote.cpp @ 1880 ) "Downloading changes" 
 INFO 2017-03-18 16:02:07.487 ( nixnote.cpp @ 1880 ) "Download 0% complete for notebooks, tags, & searches." 
 INFO 2017-03-18 16:02:09.244 ( nixnote.cpp @ 1880 ) "Download 98% complete for notebooks, tags, & searches." 
 INFO 2017-03-18 16:02:09.245 ( nixnote.cpp @ 1880 ) "Download complete for notebooks, tags, & searches.  Downloading notes." 
 INFO 2017-03-18 16:03:04.038 ( nixnote.cpp @ 1880 ) "Download 0% complete." 
 INFO 2017-03-18 16:03:58.170 ( nixnote.cpp @ 1880 ) "Download 1% complete." 
 INFO 2017-03-18 16:04:50.647 ( nixnote.cpp @ 1880 ) "Download 2% complete." 
 INFO 2017-03-18 16:06:03.621 ( nixnote.cpp @ 1880 ) "Download 4% complete." 
 INFO 2017-03-18 16:08:06.427 ( nixnote.cpp @ 1880 ) "Download 5% complete." 
ERROR 2017-03-18 16:09:01.247 ( communication/communicationmanager.cpp @ 303 ) EDAMSystemException 
ERROR 2017-03-18 16:09:01.255 ( communication/communicationmanager.cpp @ 1192 ) EDAMSystemException Error Code: 19 

ERROR 2017-03-18 16:09:01.255 ( communication/communicationmanager.cpp @ 1194 ) EDAMSystemException Rate Limit: 3200 

ERROR 2017-03-18 16:09:01.255 ( threads/syncrunner.cpp @ 260 ) Error retrieving chunk 
 INFO 2017-03-18 16:09:01.255 ( nixnote.cpp @ 1880 ) "API rate limit exceeded.  Please try again in 54 minutes." 
ERROR 2017-03-18 16:09:01.383 ( communication/communicationmanager.cpp @ 178 ) EDAMSystemException 
ERROR 2017-03-18 16:09:01.384 ( communication/communicationmanager.cpp @ 1192 ) EDAMSystemException Error Code: 19 

ERROR 2017-03-18 16:09:01.384 ( communication/communicationmanager.cpp @ 1194 ) EDAMSystemException Rate Limit: 3347 

 INFO 2017-03-18 16:09:01.385 ( nixnote.cpp @ 1880 ) "API rate limit exceeded.  Please try again in 56 minutes."

**Comment by baumgarr** [comment]
Evernote limits the number of API calls that 3rd party clients can do per hour. Unfortunately there isn't anything I can do about it. The only thing you can do is wait until the next hour & re-sync. It should pick up where it left off. Sorry.
