### ISSUE TITLE
Can Nixnote support www.yinxiang.com?

### ISSUE THREAD

**Issue by hellolzc** [baumgarr/nixnote2#308]
Evernote has another website  www.yinxiang.com in China.
Could Nixnote support www.yinxiang.com?

**Comment by zhtengw** [comment]
Yes, I am using.

Best regards,
Aten

**Comment by baumgarr** [comment]
There are two options.

One is to open the account maintenance dialog under the File menu. Click the "Add" button to create a new account. This will give you the option for what server to sync with.

The other option is to edit the ~/.nixnote/accounts.conf and change the <server> tag. This only works if you've never synchronized the current account with Evernote. If you've already done a sync you'll probably encounter weird problems.

**Comment by hellolzc** [comment]
Thank you very much!

**Comment by robert7** [comment]
it should work - see https://github.com/baumgarr/nixnote2/issues/459
