### ISSUE TITLE
Add link to http://nixnote.org/

### ISSUE THREAD

**Issue by RobberPhex** [baumgarr/nixnote2#309]
In web http://nixnote.org/, there is link to https://github.com/baumgarr/nixnote2.

But, there isn't link back to http://nixnote.org/.

**Comment by RobberPhex** [comment]
You can just add website in project setting:

![website in project setting](https://cloud.githubusercontent.com/assets/1926185/24082871/603f5de2-0d07-11e7-960e-142e24f68f4b.png)

**Comment by baumgarr** [comment]
What do you mean, "move to issue from the forums"?

**Comment by RobberPhex** [comment]
@baumgarr forums is inactive,

we can shut down forums. If there is any suggestion, just post on github issue.
