### ISSUE TITLE
Cannot import enex file

### ISSUE THREAD

**Issue by tchaffee** [baumgarr/nixnote2#311]
The import just hangs. I am using the format described at https://gist.github.com/evernotegists/6116886 and https://blog.evernote.com/tech/2013/08/08/evernote-export-format-enex/ . 

Any suggestions? 

Here is a gist of a file that does not work for import https://gist.github.com/tchaffee/0948bc1ff01e573ca00c82f32a2bb3d6

**Comment by baumgarr** [comment]
The next release should fix it. I've never had an Evernote Mac export, so there was no testing for it.

**Comment by tchaffee** [comment]
It's not really a Mac export. I created the export file myself with a little javascript that converts some bookmarks from a csv file. Is there something I could change in my XML output that would make it work with the current version? Thanks for your help.

**Comment by baumgarr** [comment]
Sure. In the en-export tab change the application= value to 
"Evernote/Windows" 
and the version= value to 
"5.x"
