### ISSUE TITLE
Unable to update note.

### ISSUE THREAD

**Issue by cozcinar** [baumgarr/nixnote2#317]
I am receiving error in the version 20170322

The error is

> Unable to update note. Invalid note structure ::EDAMUserException: ENML_VALIDATION parameter=Attribute "type" is required and must be specific for element type "en-media".

Could you please help me to solve this issue ?

Thanks

**Comment by baumgarr** [comment]
If edit the note & re-save it, does it go away?

**Comment by cozcinar** [comment]
Thank you @baumgarr  it went away!
