### ISSUE TITLE
Unable to open file for reading or file does not exist.

### ISSUE THREAD

**Issue by davidswords** [baumgarr/nixnote2#318]
I've been running under 14.04 from the daily build I think....
I have found the following error when running from command line.

DEBUG 2017-03-27 17:07:10.803 ( gui/shortcutkeys.cpp @ 246 ) Unable to open file for reading or file does not exist. 
DEBUG 2017-03-27 17:07:10.803 ( gui/shortcutkeys.cpp @ 246 ) Unable to open file for reading or file does not exist. 

Any ideas?

**Comment by baumgarr** [comment]
This is just an old debug message. It is removed in newer builds. It is just saying that it cannot find a custom shortcut.txt file. It has no impact on usability.
