### ISSUE TITLE
Formating icons panel shows and disappears all the time

### ISSUE THREAD

**Issue by michaldybczak** [baumgarr/nixnote2#319]
I'm not sure if that's intended behaviour but it's MASSIVELY ANNOYING. I use "focus follow mouse" for most convenient workflow and the notice text jumps up and down up and down up and down due to the fact that icon panel shows when notice sub-window is active and gets hidden when that sub-window gets unfocused. This is driving me crazy!

Is there a way to force the panel to stay in one play all the time?

No other programs behave that way so I can't comprehend who fall into the idea that such behaviour would be helpful?

**Comment by baumgarr** [comment]
Look under Edit/Preferences and uncheck Auto Hide Editor Toolbar.

**Comment by michaldybczak** [comment]
Thanks! Why didn't I see it before? I was staring at it and... didn't recognise it. Now it's all good :D.
