### ISSUE TITLE
Missing themes

### ISSUE THREAD

**Issue by mkowske** [baumgarr/nixnote2#320]
Started nixnote today and there was nothing listed under Edit -> Theme except "system default". Previously there were about 4 or 5 listed. I can't figure out how to recover this. I have tried re-installing.

**Comment by baumgarr** [comment]
What is in your ~./nixnote/theme.ini & /usr/share/nixnote/theme.ini?

**Comment by mkowske** [comment]
Neither of those files exist... I just took a copy of theme.ini from here and the themes appear in the menu now but don't work like they used to. The Material Light theme (which previously was quite nice looking) only changes the icons. The background color and fonts remain unchanged --

![2017-03-28_064422_screenshot](https://cloud.githubusercontent.com/assets/26007801/24403362/23e9a7ea-1382-11e7-92d3-d931a1af2932.png)
![2017-03-28_064416_screenshot](https://cloud.githubusercontent.com/assets/26007801/24403363/23ea3840-1382-11e7-8532-73d04109151f.png)

**Comment by mkowske** [comment]
Yes, that was it. I had to reset the font set in qtconfig-qt4 for it to look like it used to. 

The QT4 version of nixnote works fine and looks good now.
The QT5 version of nitxnote does not respect the QT theme i have set with qtconfig.

This probably relates to the issue I posted on sourceforge (btw, where is the preferred place to post issues?) where it crashed on startup when I used the QT5 version. Well it starts now, but doesn't set the QT theme properly. It is working well enough for me anyway.

**Comment by aproposnix** [comment]
> What is in your ~./nixnote/theme.ini & /usr/share/nixnote/theme.ini?

Neither of these files exist on my fresh install of the nixnote2-daily+20170329

I only have the option to select "System Default" . 

Looking through "/usr/share/nixnote2/images" I see the theme assets (Classic-theme, Material-light, Purple-Theme) are available.

**Comment by baumgarr** [comment]
Sorry for the slow response. Things have been a little crazy for me the last few months.

Have you tried downloading the themes.ini from GitHub & placing it in /usr/share/nixnote2?

**Comment by danielmaurer** [comment]
This issue also appears for me. I'm using KDE Neon 5.10.1.
Copy and paste theme.ini fixes this, but the trash and sync icons are with System Default theme.

**Comment by kevinhowbrook** [comment]
> Have you tried downloading the themes.ini from GitHub & placing it in /usr/share/nixnote2?

This worked for me :+1:

**Comment by baumgarr** [comment]
Is this still a problem for anyone on this thread?

**Comment by aproposnix** [comment]
It's OK for me now. Thanks.

**Comment by ReplicaObscura** [comment]
I don't know if this should really be closed. Yes, manually downloading theme.ini from the repository and manually placing it in the right folder will make things work. But shouldn't this file be put in place when installing nixnote2 via package manager?

**Comment by nkahe** [comment]
Yeah, would be great if themes worked OOTB.

**Comment by 1tm** [comment]
Where can themes.ini be downloaded? Failed to find it...

**Comment by justasmundeikis** [comment]
Totally agree, in my case after coping theme.ini only the editor space is dark...

**Comment by 00h-i-r-a00** [comment]
I copied themes.ini to /usr/share/nixnote2 and .nixnote and it still doesn't work for me.

**Comment by spenceroreidy** [comment]
I have the latest daily (nixnote2-daily+20180516) and this still appears to be missing themes OOTB. And as mentioned above, copying theme.ini into /usr/share/nixnote2 no longer seems to work?

**Comment by robert7** [comment]
@spencerready although you have "daily 20180516" - last update in this "upstream" is from October 2017
but there is active fork - see https://github.com/baumgarr/nixnote2/wiki
in the new version 2.1 the themes are working OOTB (in case you using the PPA version) - although they are still a bit "lame" - anyone wanting to contribute is welcome :)
but at least the "dark version" in few variations is working OOTB

see https://github.com/robert7/nixnote2/wiki/NixNote-Themes

**Comment by spenceroreidy** [comment]
@robert7 thanks for responding; I poked around a little more after I replied on this thread and found your fork. Already got it, and thanks for keeping this going; much appreciated :)
