### ISSUE TITLE
Menu not showing after "Minimize to tray"

### ISSUE THREAD

**Issue by sleidig** [baumgarr/nixnote2#322]
When activating the setting "minimize to tray" the main menu in the Ubuntu status bar (File|Edit|View|Note|...) is not showing up anymore after minimizing and showing NixNote again. 
On startup, before the first minimizing to tray, the menu is displayed. Also, without the option "minimize to tray" the menu is showing after minimizing and reshowing the window.
(Ubuntu 16.04, Unity)

**Comment by baumgarr** [comment]
I can't recreate this behavior & since Unity is being killed by Ubuntu, I don't think there is anything I can do about it. Sorry.
