### ISSUE TITLE
Feature request: Raw Edit mode button

### ISSUE THREAD

**Issue by vitovt** [baumgarr/nixnote2#325]
It would be great to have possibility to edit raw html source of the page.

**Comment by osamuaoki** [comment]
FYI: Try show source and try edit the source ... Wow, it changes ... Not that I know how, it is reflected to the display.

**Comment by baumgarr** [comment]
The "Show Source" is the best way to edit the raw HTML, but be careful. It is really easy to mess up & not be able to sync a note.

**Comment by hosiet** [comment]
@baumgarr I wish you could recall that editing HTML via "Show Source" function is rather buggy in the GUI part too. The textarea keeps scrolling to the top, which made editing rather difficult.

**Comment by baumgarr** [comment]
I just pushed out a change to (hopefully) scroll the note back to the same position after a source edit. It causes a flicker but it should keep the same position. Not the best solution, but better than nothing.
