### ISSUE TITLE
note shows different "Author"

### ISSUE THREAD

**Issue by kuatroka** [baumgarr/nixnote2#328]
Hi, I just noted that one of my notes suddenly started to show an author name that is not the same as all the others. I have this one note that for some reason now shows me author - "Andy Hand".
Any help in understanding it would be appreciated.

Note was created 3 days ago and only today I noticed a different author's name.
Thanks

**Comment by baumgarr** [comment]
Sorry for the slow response. I've been a little busy.

There is an option in Edit/Preferences that says "Set Author on New Notes". Try disabling that and see if it corrects your issue.

**Comment by baumgarr** [comment]
No response. Closing issue.
