### ISSUE TITLE
Gets greyed out about every 10 seconds on Ubuntu 14.04. Not useable.

### ISSUE THREAD

**Issue by fivef** [baumgarr/Nixnote2#33]
One CPU Thread always seems to be a 100% the other 7 more or less idle.

**Comment by baumgarr** [comment]
When you first download it will take up a lot of CPU indexing the notes.  I've made a few changes so hopefully the graying out doesn't happen (or at least as often).

**Comment by fivef** [comment]
NixNote is usable in Beta 3. Short greyouts only from time to time. Thanks

**Comment by baumgarr** [comment]
Should be more permanently fixed in beta 4.

**Comment by fivef** [comment]
No greyouts in Beta 7!
