### ISSUE TITLE
Needs update to libpng16-16 (latest)

### ISSUE THREAD

**Issue by devinhedge** [baumgarr/nixnote2#331]
Current 2.0 is dependent on an outdated libpng12-0 and needs to be updated to libpng16-16.

**Comment by hosiet** [comment]
This issue means a manual library transition (as well as a recompilation / a new release).

`libpng12-0` is not available on systems released after May 2016, which means it is not available on Ubuntu 16.10+ and Debian 9+.

`libpng16-16` is available on Ubuntu 16.04 LTS or higher, Debian 9 or higher.

@baumgarr it is up to you to decide which libpng lib do you want to link against in binary releases. Note that `libpng12` is not compatible with `libpng16`.

Compiling from source will not encounter this problem at all anyway.

**Comment by baumgarr** [comment]
Newer releases will be built on newer distros, but that will break older LTS versons.
