### ISSUE TITLE
More Ubuntu 16.04 dependency issues: four depracated libraries

### ISSUE THREAD

**Issue by devinhedge** [baumgarr/nixnote2#332]
Trying to install from source. Ran into the following installing the dev packages:

Package libopencv-highgui2.4 is not available.
Package libopencv-imgproc2.4 is not available
E: Package 'libopencv-core2.4' has no installation candidate
E: Package 'libopencv-highgui.4' has no installation candidate
E: Package 'libopencv-imageproc.4' has no installation candidate
E: Unable to locate package libqt-sql-sqlite

Poking around, this seems to be just an issue of newer libraries being available.

**Comment by baumgarr** [comment]
Sorry for the slow response. Things have been chaotic & I haven't had much time to look at NixNote.

The opencv ones are not a big deal & only needed if you want to build the plugin that enables webcam notes. If you don't need webcam notes, then don't worry about compiling the wabcam plugin.

The libqt-sql-sqlite is critical, but you didn't say what distribution you are using so  can't be much help on that end. It is possible that it is part of the base qt package for your distro. Every one is a little different. If you can't find it, you can try compiling it anyway. If it fails then your distro probably has it as a different name. If it succeeds then it is probably packaged as part of Qt.

**Comment by hosiet** [comment]
@devinhedge I am wondering how did you "install from source". Things should not be messy given correct `-dev` packages installed.

BTW You might be seeking for `libqt4-sql-sqlite`. See https://packages.debian.org/sid/libqt4-sql-sqlite .

**Comment by baumgarr** [comment]
No response. Closing issue.
