### ISSUE TITLE
rpm for RHEL?

### ISSUE THREAD

**Issue by RaviRJoshi** [baumgarr/nixnote2#333]
This is not reporting a bug. But is it possible to find an rpm for RHEL?

**Comment by artmg** [comment]
Hi Ravi, have you looked in the SourceForge downloads area for nixnote2? Browse to https://sourceforge.net/projects/nevernote/files/ then look in the latest version, Linux folder, and choose qt5 or qt4 as you prefer and you should find the latest RPM to download from there and install into RedHat. Hope this helps, Art

**Comment by RaviRJoshi** [comment]
Thanks Art. I am able to download rpm. It is for CentOS 7. However glibc > 2.18 dependency prevents it from install it. CentOS has 2.17, and a manual install of 2.18+ is strongly discouraging me from installing it.
Is there a version that uses 2.17 or less?

**Comment by artmg** [comment]
Although it may be possible to work around for glibc dependencies by downloading or compiling specific versions, you might find it more reliable to use the copr repo and let **yum** handle the dependencies for you.

Try following the [instructions in the read me for installing RPMs from the copr repo ](https://github.com/baumgarr/nixnote2#rpm-package-on-copr)

**Comment by artmg** [comment]
Hi Ravi, did this suggestion resolve your issue? Please let us know if it can be Closed. Thanks

**Comment by RaviRJoshi** [comment]
Hi Randy,
You can please go ahead and close the case.
(I haven't been able to build it on CentOS 7, dependencies are a bit too much for me to overcome. I'm using it instead on Ubuntu.)
Thannks.
