### ISSUE TITLE
Feature request: exporting to Evernote/OneNote

### ISSUE THREAD

**Issue by paudan** [baumgarr/nixnote2#337]
I think it would be a very beneficial feature, as it would also increase interoperability and allow easier migrations from/to the most popular software. Importing from OneNote would be useful and required as well, as it is quite difficult to migrate from OneNote to NixNote (Evernote has such feature)

**Comment by baumgarr** [comment]
Is there a place where the OneNote file format is documented?

**Comment by baumgarr** [comment]
I found where it is documented by MS, but the format is complex enough that it would take a fair amount of effort to implement. I'll keep it in mind for a future feature, but right now it isn't something I want to undertake. If someone wants to do it, I'll add it when they have it working.

The easiest thing to do would be to import it using Evernote, then export the database to an enex (or synchronize with Evernote) then import it to NixNote.
