### ISSUE TITLE
Force UTF8 Encoding: spell error and suggestion (CJK)

### ISSUE THREAD

**Issue by osamuaoki** [baumgarr/nixnote2#339]
For CJK user on linux and any modern windows should be using UTF-8 text.;-)

In User's manual (P26):
 “Force UTF8 Encoding” - Evernote doesn’t always seem to send the <xml>
 header with notes created or edited in the web interface. This can cause
 an issue with some special characters. As a workaround, this will add
 the <xml> tags to notes that are missing it. This is experimental and
 disabled by defalut, but if you are having issues where special
 characters are being displayed improperly this may correct the issue.

This should be.. s/defalut/default/

This feature is essential to be enabled on the CJK environment.  Please elaborate what kind of adverse effects you see so people using Chinese/Japanese can manage risks since this is marked as experimental feature.

In order to make people aware of this nice feature, I placed a dummy bug report to Debian.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=864978

If you see no adverse effect, please make this default feature.

**Comment by baumgarr** [comment]
UTF-8 forcing is now the default for newer builds. thanks for the feedback.
