### ISSUE TITLE
Feature Request - Adding checkboxes from keyboard

### ISSUE THREAD

**Issue by jacobconroy75** [baumgarr/nixnote2#343]
Awesome program. Nixnote2 is the closest I've found to Endnote. The ability to add checkboxes from the keyboard would make it perfect. This function was control+shift+T on OS X. Implement this function and I shall worship thee!

**Comment by baumgarr** [comment]
There is a file called shortcuts.txt that allows yout to customize shortcuts for NixNote. It is explained in the user manual, but either put it in ~/.nixnote/ or /usr/share/nixnote2. There is an option in that called Edit_Insert_Todo. You should be able to add Ctrl+Shift+T and it will allow you to add a checkbox via the keyboard after a restart of NixNote.
