### ISSUE TITLE
The 'font color' and 'Highlight' dropdown button unresponsive

### ISSUE THREAD

**Issue by quanzhuo** [baumgarr/nixnote2#345]
## Distribution
Ubuntu 16.04.2 LTS

## NixNote Verson
2.0

## Description
These two button  can not be pulled down for a full color list.

**Comment by baumgarr** [comment]
Try clicking & holding it. Just clicking it will apply the last color to the highlighted text.

**Comment by baumgarr** [comment]
No response. Closing.
