### ISSUE TITLE
Nixnote2 fails to start

### ISSUE THREAD

**Issue by SebastianMosiej** [baumgarr/nixnote2#346]
Suddenly (perhaps some system update) nixnote stopped starting.

> mosiej@khlavan:~$  nixnote2 start --syncAndExit
DEBUG 2017-07-02 23:25:32.820 ( gui/shortcutkeys.cpp @ 244 ) Unable to open file for reading or file does not exist.
terminate called after throwing an instance of 'qevercloud::EverCloudException'
>   what():  qevercloud::Optional: nonexistent value access
> Abort

Debian, 64b
> Linux khlavan 4.5.0-2-amd64 #1 SMP Debian 4.5.4-1 (2016-05-16) x86_64 GNU/Linux

**Comment by artmg** [comment]
Hi, this looks similar to issue #234 where a sync error makes Nixnote fail to start.

The recommendations in that issue were:
* disable automatic sync on startup (to allow the program to launch)
* identify the note causing the sync issue - probably due to bad formatting (e.g. pasting from HTML pages without using Paste as Unformatted Text) 

Please check the other issue to see if that helps, and let us know - thanks

**Comment by SebastianMosiej** [comment]
Application isn't starting GUI. 
How can I disable automatic sync from command line?

**Comment by artmg** [comment]
Options may me modified without starting the app by editing `~./nixnote/nixnote-1.conf`

Try setting 
```
[Sync]
syncAutomatically=false
syncOnShutdown=false
syncOnStartup=false
```

Hopefully this will allow the app to start successfully, then you can deal with any issues on notes that failed to sync

**Comment by SebastianMosiej** [comment]
I've modified configuration and executed app - still the same behaviour.

Is there some settings which would increase verbosity? In config file I found that messageLevel=2.
What else can I change to get more descriptive logs?

**Comment by baumgarr** [comment]
Change the messageLevel=2 to messageLevel=1. See if that helps. If that doesn't, try changing it to messageLevel=0

**Comment by baumgarr** [comment]
One other thing...

Look for a line lastViewed=.  Make a note of that number, and change it to -1. See if that corrects the startup issue. If it does, then that particular note has a problem. Go into the Edit/Preferences and under Debug you need to enable the option to view LIDs. Then restart NixNote & look for that particular number. That note has some type of issue. Knowing that and setting the messageLevel to 0  may help narrow down where it is failing.

**Comment by SebastianMosiej** [comment]
I've remove folder ~/.nixnote/db-1 and downloaded notes again. It took lots of time (some api limitations).
However - now everything starts properly and without warnings.
I would guess that some note could be corrupted....
