### ISSUE TITLE
No icon on Nixnote2 from daily PPA

### ISSUE THREAD

**Issue by mhalano** [baumgarr/nixnote2#348]
I'm using NixNote2 from daily PPA and I noticed there's no icon for Nixnote2. I found the directory /usr/share/pixmaps (where icons go) empty.

**Comment by artmg** [comment]
Hi, could you please confirm: 
* Help / About - nixnote daily build version
* which Ubuntu flavour / version are you using?
* do you mean the menu shortcut you use to launch nixnote2 has no icon, or the application tab on your desktop panel that shows the running app, or the 'system tray' notification area in the panel.
Then I will check the package, thanks

**Comment by artmg** [comment]
Has anyone else noticed this icon issue?

Trying to diagnose this I found @hosiet made a [commit to 'Install icon into /usr/share/pixmaps '](https://github.com/baumgarr/nixnote2/commit/a26e73fa0206347e9cbe43432a743fa26e7151de). That was to remove the hardcoded path from the icon, and the `pixmap` install section in `NixNote2.pro` was supposed to copy the icon into the pixmap folder. 

Unfortunately the package from the PPA has an empty pixmap folder. I'm wondering if there are some package or install scripts like install.sh that need to be updated like [copy_files.sh was by baumgarr](https://github.com/baumgarr/nixnote2/commit/d742f59650c2214f422be4f090df95f2b191b0be)?

Or should the copy command in the pixmap install section have a more explicit path than `cp images/windowIcon.png images/nixnote2.png`?

**Comment by mhalano** [comment]
Help / About - nixnote daily build version
nixnote2-daily+20170704

    which Ubuntu flavour / version are you using?
Ubuntu 17.04.

    do you mean the menu shortcut you use to launch nixnote2 has no icon, or the application tab on your desktop panel that shows the running app, or the 'system tray' notification area in the panel.
The menu shortcut has no icon and also the icon on the dash (lateral bar) has no icon. On system tray the icon shows (a notepad I guess)

Best regards.

**Comment by jasperpeeters** [comment]
I also noticed this icon issue: no icon in the on the bar or in the menu.
I also use the daily ppa version.
System: 16.04.1-Ubuntu

**Comment by mkeilwaldbrunn** [comment]
Same for me with 16.04 and 17.04.
icon is missing in daily ppa

**Comment by artmg** [comment]
Fixed in downstream packaging repo and rebuilt into PPA. Please update to latest version (`sudo apt-get update && sudo apt-get install nixnote2`) then refresh your panel start menu (or log off and on again) - you should see the icon now.
