### ISSUE TITLE
break unicode when sync

### ISSUE THREAD

**Issue by hong-duc** [baumgarr/nixnote2#349]
This is my note on Evernote web

![image](https://user-images.githubusercontent.com/12032550/28025366-67c0fc92-65bd-11e7-9d81-0d5b465cc2d5.png)

And this is what nixnote show

![image](https://user-images.githubusercontent.com/12032550/28025409-8f62f052-65bd-11e7-9070-022934ce2670.png)

I have install font gotham and change the default font of the editor to gotham too but nothing work.
I use linux mint 18
Please help !!

**Comment by baumgarr** [comment]
Go into Edit/Preferences. On the last tab there is an option to enforce UTF-8 encoding. Make sure it is selected.

**Comment by hong-duc** [comment]
Ah so that is where you hide it, thank you, it work well :smile:
