### ISSUE TITLE
Fedora 26 

### ISSUE THREAD

**Issue by oldmansaur** [baumgarr/nixnote2#350]
Trying to install nixnote2 on Fedora 26.

I am getting this error message. 
 `nothing provides libhunspell-1.4.so.0()(64bit) needed by nixnote2-2.0_beta10-3.ndias.fc26.x86_64`

When I try `dnf whatprovides "libhunspell*"`, I get 

> hunspell-1.5.4-2.fc26.x86_64 : A spell checker and morphological analyzer library
> Repo        : @System
>
> hunspell-1.5.4-2.fc26.i686 : A spell checker and morphological analyzer library
> Repo        : fedora

> hunspell-1.5.4-2.fc26.x86_64 : A spell checker and morphological analyzer library
> Repo        : fedora

Edit: Downloading from [SourceForge](https://sourceforge.net/projects/nevernote/?source=directory) and then installing it works just fine.

**Comment by zkanda** [comment]
I'm getting this error too, using RPM from SourceForge works just fine.

**Comment by baumgarr** [comment]
I would recommend using a newer build of NixNote or building it from source. The newer builds separate out hunspell into a plugin so it isn't needed for the actual base NixNote. 

If you want to build it from the source, the instructions are in the manual.

**Comment by zkanda** [comment]
@baumgarr where can we get the newer builds?

**Comment by jhoward321** [comment]
@zkanda I built the latest version and created a copr repository for it so you can install it through dnf. https://copr.fedorainfracloud.org/coprs/jhoward321/nixnote2/

**Comment by wildskyf** [comment]
Thanks to @jhoward321 !

```
sudo dnf copr enable jhoward321/nixnote2 
sudo dnf install nixnote2 -y
```

**Comment by ellenos** [comment]
thank you @jhoward321 and @wildskyf   !!

**Comment by baumgarr** [comment]
I also have a newer build uploaded to SourceForge. You can try that too. Sorry for the slow response.

Thanks!
