### ISSUE TITLE
Feature Request: Checklist Enhancement

### ISSUE THREAD

**Issue by CaptainPackers** [baumgarr/nixnote2#351]
When creating a checklist, the UI doesn't handle the new line the same way it does ordered or unordered lists. It doesn't automatically add a checkbox to the new line. 

I've always enjoyed this feature in evernote, and nixnote does this with ordered and unordered lists. Can you make it behave the same way with checklists?

Thanks. Great product. Really enjoying it. I especially find shortcuts to saved searches very helpful.

I've implemented The Secret Weapon GTD methodology on my Ubuntu system. Thanks to your app I'm not stuck using the Evernote web interface or some other hack like RDP to a windows system.

**Comment by baumgarr** [comment]
Unfortunately there is no easy way to do this. The bullet & other lists are handled by WebKit. The To-dos are inserts of input checkboxes. I don't know Javascript well enough to determine if a cursor is on the same line as a checkbox. Without this, there is no way to automatically insert a checkbox on an enter.

sorry.
