### ISSUE TITLE
New 'exits' feature breaks older PPA builds

### ISSUE THREAD

**Issue by artmg** [baumgarr/nixnote2#352]
Hi, following the release of the new 'exits' feature, I have modified the PPA build to [include the qml dependency](https://github.com/artmg/nixnote2-packaging/commit/a76e160bf3ce41e9802089a95e7b865cf7a4b1b8). 

The PPA build now appears to work for Ubuntu distribution series:
* Xenial 16.04
* Zesty 17.04
* Artful 17.10

However the builds are currently broken for:
* Vivid 15.04
* Trusty 14.04

FYI Launchpad no longer offers the option to build for the version that just went end of life:
* Yakkety 16.10

I suspect the builds fail because the new feature relies on functionality not backported into the QML module for those versions. Vivid is already end of life but Trusty is a Long Term Support (LTS) version that is supposed to last until April 2019. Without a better understanding of the new 'exits' code and how it uses QML I am not sure if I can do much about this.

**Comment by artmg** [comment]
PS: If anyone is interested to see why it fails, check the [detailed build logs](https://code.launchpad.net/~nixnote/+archive/ubuntu/nixnote2-daily/+build/13139137/+files/buildlog_ubuntu-trusty-amd64.nixnote2_2.0-release-0+932+61+201707241107~ubuntu14.04.1_BUILDING.txt.gz)

Things start going wrong with 
```
html/enmlformatter.cpp:250:31: warning: missing initializer for member ‘_TidyBuffer::bp’ [-Wmissing-field-initializers] In member function ‘QByteArray EnmlFormatter::rebuildNoteEnml()’
``` 
and continue with 
```
cmdtools/cmdlinetool.cpp:763:5: warning: unused parameter ‘config’ [-Wunused-parameter]
```
before falling apart with 
```
In file included from exits/exitpoint.cpp:21:0: exits/exitpoint.h:83:18: error: field ‘tags’ has incomplete type
```

**Comment by baumgarr** [comment]
Just curious if this is still failing. The warnings are no big deal, but should be removed. Odd that I didn't get the same error about the incomplete type of StringList until I did a Qt4 build. After that it failed. I think I have that fixed too.

**Comment by artmg** [comment]
What's more worrying is that the Xenial build is now failing too, leaving only 17.04 Zesty (and 17.10 alpha Artful) builds coming through. Perhaps I need to do a diff between the build logs for that work vs those that fail, to find what changes have broken the older versions. It's always tough to balance new features vs support for older versions.

**Comment by baumgarr** [comment]
It may be due to the version of gcc. Look for something in the logs saying "unique_ptr" or "auto_ptr".

**Comment by baumgarr** [comment]
I made a change to check for the version of C++ that the compiler can handle. Let me know if that makes a difference.

**Comment by artmg** [comment]
Thanks, @baumgarr your latest changes have made Xenial builds work again. So that means we have the **working** builds for a) the **current**, b) **latest LTS**, and c) **up-and-coming** Ubuntu versions. I think this is reasonable for now, unless we have people on the _previous LTS version_ clamouring for updates.

**Comment by baumgarr** [comment]
Thanks!
