### ISSUE TITLE
shortcut for inserting todo

### ISSUE THREAD

**Issue by bedohave** [baumgarr/nixnote2#358]
Can we add a shortcut for inserting a todo into a note? I use them frequently and a shortcut would be helpful.

**Comment by baumgarr** [comment]
You can setup a shortcut for this. Please read the user manual or look in the shortcuts_howto.txt for more details.

**Comment by bedohave** [comment]
Thanks and sorry. I hate being the 'RTFM' guy.

**Comment by baumgarr** [comment]
No problem. Been there many times myself.

**Comment by bedohave** [comment]
:-)

I tried adding this to my shortcuts.txt in ~/nixnote

Format_Todo <tabs to next column> Ctrl+/ <more tabs> //Add Todo


And restarting. No luck What am I doing wrong?

**Comment by bedohave** [comment]
Never mind. I found the proper wording in the full shortcuts.txt. cheers!

**Comment by baumgarr** [comment]
Usually when that happens the window manager isn't passing the keystroke to NixNote.

The easiest way to test it is to find a different shortcut that works, then remove that shortcut & reassign it to the one you want.

**Comment by kapad** [comment]
@bedohave what is the proper wording that you found from the shortcuts.txt file?
