### ISSUE TITLE
Can't set font color

### ISSUE THREAD

**Issue by bedohave** [baumgarr/nixnote2#360]
In all notes, I cannot set the font color for either selected text or for text I'm about to type.
When I click on the font color icon in the toolbar, nothing happens; no dropdown to select color; no text getting recolored. 

Distro: Ubuntu Budgie 17.04
Windowing: Gnome
Installed via built-n pkg mgr/store "Software"

Happens with all notes.

tail of debug:

DEBUG 2017-08-08 12:38:19.205 ( html/enmlformatter.cpp @ 236 ) Starting tidy true 
DEBUG 2017-08-08 12:38:19.206 ( html/enmlformatter.cpp @ 241 ) Stopping tidy false Return Code: QProcess::ProcessState(NotRunning) 
DEBUG 2017-08-08 12:38:19.206 ( html/enmlformatter.cpp @ 253 ) "line 3 column 137 - Warning: isn't allowed in 
elements" 
DEBUG 2017-08-08 12:38:19.206 ( html/enmlformatter.cpp @ 253 ) "line 3 column 35 - Info: 
previously mentioned" 
DEBUG 2017-08-08 12:38:19.206 ( html/enmlformatter.cpp @ 253 ) "line 3 column 144 - Warning: discarding unexpected 
" 
DEBUG 2017-08-08 12:38:19.206 ( html/enmlformatter.cpp @ 253 ) "line 3 column 940 - Warning: trimming empty " 
DEBUG 2017-08-08 12:38:19.206 ( html/enmlformatter.cpp @ 253 ) "line 3 column 327 - Warning: element removed from HTML5" 
DEBUG 2017-08-08 12:38:19.206 ( html/enmlformatter.cpp @ 253 ) "" 
DEBUG 2017-08-08 12:38:19.209 ( html/enmlformatter.cpp @ 805 ) 

DEBUG 2017-08-08 12:38:19.212 ( gui/nbrowserwindow.cpp @ 781 ) Valid Resource LIDS: 
DEBUG 2017-08-08 12:38:19.212 ( gui/nbrowserwindow.cpp @ 787 ) Old Resource LIDS: 
DEBUG 2017-08-08 12:38:19.212 ( gui/nbrowserwindow.cpp @ 800 ) Updating note content 
DEBUG 2017-08-08 12:38:19.267 ( utilities/noteindexer.cpp @ 51 ) Indexing note: "this" 
DEBUG 2017-08-08 12:38:19.380 ( gui/nbrowserwindow.cpp @ 806 ) Beginning thumbnail 
DEBUG 2017-08-08 12:38:19.430 ( gui/nbrowserwindow.cpp @ 808 ) Thumbnail compleded 
DEBUG 2017-08-08 12:38:19.430 ( gui/nbrowserwindow.cpp @ 812 ) Updating cache 
DEBUG 2017-08-08 12:38:19.430 ( gui/nbrowserwindow.cpp @ 819 ) Leaving saveNoteContent() 
DEBUG 2017-08-08 12:43:56.946 ( gui/nbrowserwindow.cpp @ 383 ) Setting note contents to 3831 
DEBUG 2017-08-08 12:43:56.946 ( gui/nbrowserwindow.cpp @ 395 ) this.lid: 3900 3831 
DEBUG 2017-08-08 12:43:56.946 ( gui/nbrowserwindow.cpp @ 403 ) editor is dirty 
DEBUG 2017-08-08 12:43:56.946 ( gui/nbrowserwindow.cpp @ 414 ) Getting note 
DEBUG 2017-08-08 12:43:56.951 ( gui/nbrowserwindow.cpp @ 429 ) Checking if note is in cache 
DEBUG 2017-08-08 12:43:56.951 ( gui/nbrowserwindow.cpp @ 445 ) Note not in cache 
DEBUG 2017-08-08 12:43:56.951 ( gui/nbrowserwindow.cpp @ 451 ) rebuilding note HTML 
DEBUG 2017-08-08 12:43:56.959 ( gui/nbrowserwindow.cpp @ 454 ) criteria search string set 
DEBUG 2017-08-08 12:43:56.959 ( gui/nbrowserwindow.cpp @ 459 ) adding to cache 
DEBUG 2017-08-08 12:43:56.959 ( gui/nbrowserwindow.cpp @ 468 ) Setting up note title 
DEBUG 2017-08-08 12:43:56.963 ( gui/nbrowserwindow.cpp @ 473 ) Setting editor contents 
DEBUG 2017-08-08 12:43:56.965 ( gui/nbrowserwindow.cpp @ 481 ) Setting attributes 
DEBUG 2017-08-08 12:43:56.965 ( gui/nbrowserwindow.cpp @ 516 ) Setting tags 
DEBUG 2017-08-08 12:43:56.986 ( gui/nbrowserwindow.cpp @ 535 ) Setting notebook 
DEBUG 2017-08-08 12:43:56.986 ( gui/nbrowserwindow.cpp @ 538 ) Setting URL 
DEBUG 2017-08-08 12:43:56.986 ( gui/nbrowserwindow.cpp @ 541 ) Setting note attributes 
DEBUG 2017-08-08 12:43:56.986 ( gui/nbrowserwindow.cpp @ 550 ) Calling set source 
DEBUG 2017-08-08 12:43:56.986 ( gui/nbrowserwindow.cpp @ 560 ) Checking thumbanail 
DEBUG 2017-08-08 12:43:56.986 ( gui/nbrowserwindow.cpp @ 570 ) Exiting setContent 
DEBUG 2017-08-08 12:43:58.228 ( gui/nwebview.cpp @ 366 ) DOUBLE CLICK!!! 
DEBUG 2017-08-08 12:43:59.171 ( gui/nwebview.cpp @ 366 ) DOUBLE CLICK!!! 
DEBUG 2017-08-08 12:44:00.483 ( sql/notetable.cpp @ 1091 ) QSqlError("", "", "") 
DEBUG 2017-08-08 12:44:00.509 ( utilities/noteindexer.cpp @ 51 ) Indexing note: "WRKS CTO KAs" 
DEBUG 2017-08-08 12:44:39.060 ( gui/nwebview.cpp @ 366 ) DOUBLE CLICK!!! 
DEBUG 2017-08-08 12:48:03.427 ( gui/nwebview.cpp @ 366 ) DOUBLE CLICK!!!

**Comment by baumgarr** [comment]
If you click & hold it down, it should bring up the color chooser. If you just click it, it will use the last selected color.

**Comment by bedohave** [comment]
Again RTFM. Ugh. Thanks

**Comment by baumgarr** [comment]
You're not the first person on this one. I agree it is confusing, but it allows colors to be applied more quickly.
