### ISSUE TITLE
Feature Request - Refresh View Operation

### ISSUE THREAD

**Issue by CaptainPackers** [baumgarr/nixnote2#361]
When I make changes to a note, like changing tags of folders, the changes are not reflected in the note list window or in the shortcuts if I happen to be viewing one of them. Is it possible to add a refresh view operation, accessible through a menu pick, a toolbar button, or keyboard shortcut? Right now the only option is to change views and change back. A toolbar button would be the bomb.

**Comment by baumgarr** [comment]
Some of that is implemented in the latest source and it is done automatically. If it is still an issue after the next release let me know or reopen this issue.
