### ISSUE TITLE
issue with German "Umlaute" - ä, ö, ü, ß

### ISSUE THREAD

**Issue by csab1915** [baumgarr/nixnote2#370]
Hi, when I import my German notes, the "Umlaute" ä, ö, ü, ß are not correctly displayed. How can I change the language/ISO?

**Comment by baumgarr** [comment]
It should work automatically, but you can try going into Edit/Preferences and clicking on the last tab (either Debugging or Advanced depending on the version). Then click "Force UTF8 Encoding".  Then restart NixNote.

**Comment by csab1915** [comment]
It worked with Force UTF8 - thanks a lot!
