### ISSUE TITLE
Editor text is too small on High DPI QHD display

### ISSUE THREAD

**Issue by uknth** [baumgarr/nixnote2#371]
![276 PPI Display](https://user-images.githubusercontent.com/6479031/30524591-7e684c38-9c14-11e7-82c4-f054500e32e4.png)

Display Resolution - 3200 x 1800
PPI - 276
Screen Size - 13.3"
Device - Dell XPS 13 - 9360

**Comment by uknth** [comment]
Was able to fix it using a simple export. 
```
export QT_AUTO_SCREEN_SCALE_FACTOR=1
```

**Comment by GoCyberEd** [comment]
I modified the exec line in the .desktop file
`Exec=env QT_AUTO_SCREEN_SCALE_FACTOR=1 exnixnote2`

I also tried scale factor 2. Neither had any affect. Do you have any advice? The GUI scaling is fine except for the editor which is very, very small. 

I'm using Elementary OS, if it helps.

**Comment by uknth** [comment]
Try running nixnote from command line 
```
$ export QT_AUTO_SCREEN_SCALE_FACTOR=2
$ nixnote2
```
If this works, create a shell script and put it in place of `/usr/bin/nixnote2`

**Comment by GoCyberEd** [comment]
Thanks for the reply. No luck though. :(
![screenshot from 2018-01-20 01 27 53](https://user-images.githubusercontent.com/4015651/35180620-fe33994e-fd81-11e7-9a5f-0c1739e51f37.png)

"Starting hands" and the link at the very top is the default text size

Edit: This error appears in the console -- potentially relevant?
 `(nixnote2:2495): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap"`

**Comment by neilwarrack** [comment]
I also experience small font in editor disorder. I am unable to fix it using the 'export QT_AUTO_SCREEN_SCALE_FACTOR' approach. 
Computer info:
I have ubuntu16.04 on a thinkpad carbon x1
xdpyinfo  | grep 'dimensions:'

dimensions:    2560x1440 pixels (677x381 millimeters)

**Comment by robert7** [comment]
QT_AUTO_SCREEN_SCALE_FACTOR seem to have no effect (I need to check why)
but you can set the default font size for the note editor to what ever size you want
doesn't that work for you?

![screen_20181013_04](https://user-images.githubusercontent.com/1135218/46906684-bd277300-cf07-11e8-900b-7f74682516fe.png)

**Comment by neilwarrack** [comment]
Problem solved! 
I had tried what you suggested before and I could not understand why there was no option to change the font size for the GUI & the editor from 'system default' to anything else. To resolve this problem and to change these size settings you must first change the font itself (from system default to something else) THEN the option to change the font size become available.
Thanks for you help!

**Comment by robert7** [comment]
OK. Glad to hear.
You may also want to try the new app version. See https://github.com/baumgarr/nixnote2/wiki
