### ISSUE TITLE
Quick access toolbar missing icons

### ISSUE THREAD

**Issue by brainhaver** [baumgarr/nixnote2#380]
I have Nixnote running on Windows 10, and it finally works well; except for this small problem: I was looking for the highlighter—by the way, does it have a hotkey? no key combination seems to work for me—anyway, I eventually figured out I had to remove a few of the tool icons to get the remaining ones to show up. (The missing tools were not located in the extended arrow pane.)

I should mention that this might have something to do with my poor monitor resolution:1368*768 (I've never tried Nixnote on a higher resolution screen, so this screen might be the culprit?)

**Comment by baumgarr** [comment]
Unfortunately there isn't much I can do about that. The Qt toolbar only has so much room. Some will overflow to a button on the far right, but others won't. The only way around it is to hide some buttons.

I don't see that there was a shortcut setup to this action. Most of the ones that are missing I had issues with or they caused other problems.

Sorry.

**Comment by brainhaver** [comment]
Ah, I understand---thank you for the response.

**Comment by vstepaniuk** [comment]
Sorry, could you please explain why some will overflow to a button on the far right, but others won't??

**Comment by vstepaniuk** [comment]
Because only these are missing in the overflow menu:
- Bold
- Italic
- Underline
- Insert Date & Time
- Font face
- Font size
- Font color
- Highlight

**Comment by baumgarr** [comment]
Unfortunately there isn't much I can do about this. It is controlled by Qt.  Typically, the ones that are drop d own options (like font, size, & highlighting) don't appear.

Sorry.
