### ISSUE TITLE
Nixnote2 Maturity?

### ISSUE THREAD

**Issue by stephenjlewis** [baumgarr/Nixnote2#39]
Hey, sorry if this isn't the right avenue to ask this, but would you consider your rewrite mature enough for daily use?

**Comment by fastcat** [comment]
Given it deadlocks every time I try to edit a note (#32), I would say not

**Comment by stephenjlewis** [comment]
Okay, thanks, I'll stick to NixNote for now then :)

**Comment by fastcat** [comment]
The jeffkowalski/Nixnote2 fork (as of jeffkowalski/Nixnote2@4ed73bb) seems to have fixed the deadlock for me, you may want to give it a try.
