### ISSUE TITLE
How to create new note of webpage ?

### ISSUE THREAD

**Issue by mckellyln** [baumgarr/Nixnote2#401]
Hi,
Thank you for Nixnote2.
How can I create a new Nixnote of a webpage, similar to how the Evernote webclipper does ?
thx,
-mark

**Comment by aproposnix** [comment]
Why not just use the webclipper for Evernote? Or, is your use case that you are not syncing at all (with EN servers)?  AFAIK, the only thing you can do for web clipping is to use the EN clipper.

**Comment by mckellyln** [comment]
ok, sure.  Just wondered if it was possible.  
Thx.
