### ISSUE TITLE
Error syncing after emptying trash through evernote web

### ISSUE THREAD

**Issue by bobbruno** [baumgarr/Nixnote2#41]
I noticed NixNote 2 stopped syncing with a crash right after I cleared over 200 notes through Evernote Web. Here's the log from running NixNote2 at a terminal window:

DEBUG 2015-02-13 15:10:31.492 ( global.cpp @ 79 ) Shared memory key:  "1b73cc55-9a2f-441b-877a-ca1d0131cd21" 
 INFO 2015-02-13 15:10:31.506 ( main.cpp @ 135 ) Built with Qt 4.8.4 running on 4.8.6 
DEBUG 2015-02-13 15:10:31.528 ( nixnote.cpp @ 108 ) Looking for transaltions:  "/usr/share/nixnote2/translations/nixnote2_pt_BR.qm" 
DEBUG 2015-02-13 15:10:31.532 ( sql/databaseconnection.cpp @ 32 ) SQL drivers available:  ("QSQLITE", "QMYSQL3", "QMYSQL") 
TRACE 2015-02-13 15:10:31.532 ( sql/databaseconnection.cpp @ 33 ) Adding database SQLITE 
TRACE 2015-02-13 15:10:31.533 ( sql/databaseconnection.cpp @ 35 ) Setting DB name 
TRACE 2015-02-13 15:10:31.533 ( sql/databaseconnection.cpp @ 37 ) Opening database 
TRACE 2015-02-13 15:10:31.533 ( sql/databaseconnection.cpp @ 45 ) Preparing tables 
TRACE 2015-02-13 15:10:31.534 ( sql/databaseconnection.cpp @ 54 ) Creating filter table 
TRACE 2015-02-13 15:10:31.561 ( sql/databaseconnection.cpp @ 57 ) Adding to filter table 
TRACE 2015-02-13 15:10:31.598 ( sql/databaseconnection.cpp @ 59 ) Addition complete 
TRACE 2015-02-13 15:10:31.598 ( nixnote.cpp @ 131 ) Setting up global settings 
TRACE 2015-02-13 15:10:31.598 ( nixnote.cpp @ 135 ) Setting up counter thread 
TRACE 2015-02-13 15:10:31.598 ( nixnote.cpp @ 139 ) Setting up sync thread 
TRACE 2015-02-13 15:10:31.598 ( nixnote.cpp @ 143 ) Setting up GUI 
TRACE 2015-02-13 15:10:31.652 ( nixnote.cpp @ 262 ) Setting up tool bar 
TRACE 2015-02-13 15:10:31.652 ( nixnote.cpp @ 327 ) Adding main splitter 
TRACE 2015-02-13 15:10:31.653 ( nixnote.cpp @ 689 ) Starting NixNote.setupNoteList() 
TRACE 2015-02-13 15:10:31.653 ( gui/ntableview.cpp @ 50 ) Entering NTableView constructor 
TRACE 2015-02-13 15:10:31.654 ( gui/ntableview.cpp @ 59 ) Setting up edit triggers 
TRACE 2015-02-13 15:10:31.654 ( gui/ntableview.cpp @ 63 ) Setting up fort metrics 
TRACE 2015-02-13 15:10:31.654 ( gui/ntableview.cpp @ 66 ) Initializing proxy 
TRACE 2015-02-13 15:10:31.664 ( gui/ntableview.cpp @ 82 ) Setting up table deligates 
TRACE 2015-02-13 15:10:31.664 ( gui/ntableview.cpp @ 106 ) Setting up column headers 
TRACE 2015-02-13 15:10:31.664 ( gui/ntableview.cpp @ 297 ) Exiting NTableView constructor 
TRACE 2015-02-13 15:10:31.668 ( nixnote.cpp @ 723 ) Leaving NixNote.setupNoteList() 
TRACE 2015-02-13 15:10:31.668 ( nixnote.cpp @ 810 ) Starting NixNote.setupFavoritesdNotebookTree() 
TRACE 2015-02-13 15:10:31.670 ( nixnote.cpp @ 827 ) Exiting NixNote.setupFavoritesTree() 
TRACE 2015-02-13 15:10:31.670 ( nixnote.cpp @ 836 ) Starting NixNote.setupSynchronizedNotebookTree() 
TRACE 2015-02-13 15:10:31.686 ( nixnote.cpp @ 845 ) Exiting NixNote.setupSynchronizedNotebookTree() 
TRACE 2015-02-13 15:10:31.686 ( nixnote.cpp @ 754 ) Starting NixNote.setupTagTree() 
TRACE 2015-02-13 15:10:31.776 ( nixnote.cpp @ 769 ) Exiting NixNote.setupTagTree() 
TRACE 2015-02-13 15:10:31.776 ( nixnote.cpp @ 736 ) Starting NixNote.setupSearchTree() 
TRACE 2015-02-13 15:10:31.777 ( nixnote.cpp @ 746 ) Exiting NixNote.setupSearchTree() 
TRACE 2015-02-13 15:10:31.777 ( nixnote.cpp @ 778 ) Starting NixNote.setupAttributeTree() 
TRACE 2015-02-13 15:10:31.778 ( nixnote.cpp @ 785 ) Exiting NixNote.setupAttributeTree() 
TRACE 2015-02-13 15:10:31.779 ( nixnote.cpp @ 793 ) Starting NixNote.setupTrashTree() 
TRACE 2015-02-13 15:10:31.779 ( nixnote.cpp @ 800 ) Exiting NixNote.setupTrashTree() 
TRACE 2015-02-13 15:10:31.779 ( nixnote.cpp @ 854 ) Starting NixNote.setupTabWindow() 
TRACE 2015-02-13 15:10:31.916 ( nixnote.cpp @ 891 ) Exiting NixNote.setupTabWindow() 
TRACE 2015-02-13 15:10:31.916 ( nixnote.cpp @ 354 ) Setting up left panel 
TRACE 2015-02-13 15:10:31.925 ( nixnote.cpp @ 367 ) Resetting left side widgets 
TRACE 2015-02-13 15:10:31.925 ( nixnote.cpp @ 375 ) Restoring window state 
TRACE 2015-02-13 15:10:31.927 ( sql/notetable.cpp @ 819 ) Fetching Resources?  false  With binary?  false 
TRACE 2015-02-13 15:10:31.932 ( sql/notetable.cpp @ 825 ) Fetched resources 
TRACE 2015-02-13 15:10:31.933 ( sql/notetable.cpp @ 819 ) Fetching Resources?  false  With binary?  false 
TRACE 2015-02-13 15:10:31.936 ( sql/notetable.cpp @ 825 ) Fetched resources 
TRACE 2015-02-13 15:10:31.936 ( html/noteformatter.cpp @ 105 ) Rebuilding HTML 
TRACE 2015-02-13 15:10:31.939 ( html/noteformatter.cpp @ 115 ) Before preHTMLFormat 
TRACE 2015-02-13 15:10:31.940 ( html/noteformatter.cpp @ 123 ) About to set content 
TRACE 2015-02-13 15:10:32.056 ( html/noteformatter.cpp @ 127 ) Starting to modify tags 
TRACE 2015-02-13 15:10:32.056 ( html/noteformatter.cpp @ 191 ) Searching for all en-media tags; 
TRACE 2015-02-13 15:10:32.056 ( html/noteformatter.cpp @ 193 ) Search complete:  0 
TRACE 2015-02-13 15:10:32.057 ( html/noteformatter.cpp @ 129 ) Done modifying tags 
TRACE 2015-02-13 15:10:32.057 ( html/noteformatter.cpp @ 149 ) Done rebuiling HTML 
TRACE 2015-02-13 15:10:32.060 ( sql/notetable.cpp @ 819 ) Fetching Resources?  false  With binary?  false 
TRACE 2015-02-13 15:10:32.063 ( sql/notetable.cpp @ 825 ) Fetched resources 
TRACE 2015-02-13 15:10:32.187 ( sql/notetable.cpp @ 819 ) Fetching Resources?  false  With binary?  false 
TRACE 2015-02-13 15:10:32.190 ( sql/notetable.cpp @ 825 ) Fetched resources 
DEBUG 2015-02-13 15:10:32.191 ( nixnote.cpp @ 457 ) ":windowIcon0.png" 
TRACE 2015-02-13 15:10:32.201 ( nixnote.cpp @ 500 ) Setting up timers 
TRACE 2015-02-13 15:10:32.201 ( nixnote.cpp @ 506 ) Setting up more connections for tab windows & threads 
DEBUG 2015-02-13 15:10:32.203 ( nixnote.cpp @ 1291 ) starting NixNote.updateSelectionCriteria() 
DEBUG 2015-02-13 15:10:32.203 ( filters/filterengine.cpp @ 30 ) Purging filters 
DEBUG 2015-02-13 15:10:32.224 ( filters/filterengine.cpp @ 32 ) Resetting filter table 
DEBUG 2015-02-13 15:10:32.243 ( filters/filterengine.cpp @ 36 ) Reset complete 
DEBUG 2015-02-13 15:10:32.243 ( filters/filterengine.cpp @ 46 ) Filtering favorite 
DEBUG 2015-02-13 15:10:32.243 ( filters/filterengine.cpp @ 48 ) Filtering notebooks 
DEBUG 2015-02-13 15:10:32.273 ( filters/filterengine.cpp @ 50 ) Filtering tags 
DEBUG 2015-02-13 15:10:32.273 ( filters/filterengine.cpp @ 52 ) Filtering trash 
DEBUG 2015-02-13 15:10:32.275 ( filters/filterengine.cpp @ 54 ) Filtering search string 
DEBUG 2015-02-13 15:10:32.276 ( filters/filterengine.cpp @ 56 ) Filtering attributes 
DEBUG 2015-02-13 15:10:32.276 ( filters/filterengine.cpp @ 58 ) Filtering complete 
DEBUG 2015-02-13 15:10:32.276 ( nixnote.cpp @ 1296 ) Refreshing data 
TRACE 2015-02-13 15:10:32.276 ( gui/ntableview.cpp @ 406 ) Getting valid lids in filter 
DEBUG 2015-02-13 15:10:32.276 ( gui/ntableview.cpp @ 413 ) Valid LIDs retrieved.  Refreshing selection 
TRACE 2015-02-13 15:10:32.278 ( gui/ntableview.cpp @ 441 ) Highlighting selected rows after refresh 
TRACE 2015-02-13 15:10:32.278 ( gui/ntableview.cpp @ 454 ) Highlighting complete 
TRACE 2015-02-13 15:10:32.278 ( gui/ntableview.cpp @ 457 ) Selecting one item if nothing else is selected 
DEBUG 2015-02-13 15:10:32.278 ( gui/ntableview.cpp @ 651 )  Selecting row  0 lid:  3157 
TRACE 2015-02-13 15:10:32.278 ( gui/ntableview.cpp @ 464 ) refleshSelection() complete 
TRACE 2015-02-13 15:10:32.279 ( sql/notetable.cpp @ 819 ) Fetching Resources?  false  With binary?  false 
TRACE 2015-02-13 15:10:32.287 ( sql/notetable.cpp @ 825 ) Fetched resources 
TRACE 2015-02-13 15:10:32.288 ( sql/notetable.cpp @ 819 ) Fetching Resources?  false  With binary?  false 
TRACE 2015-02-13 15:10:32.291 ( sql/notetable.cpp @ 825 ) Fetched resources 
DEBUG 2015-02-13 15:10:32.291 ( threads/counterrunner.cpp @ 37 ) Starting CounterRunner 
DEBUG 2015-02-13 15:10:32.291 ( sql/databaseconnection.cpp @ 32 ) SQL drivers available:  ("QSQLITE", "QMYSQL3", "QMYSQL") 
TRACE 2015-02-13 15:10:32.291 ( sql/databaseconnection.cpp @ 33 ) Adding database SQLITE 
TRACE 2015-02-13 15:10:32.292 ( sql/databaseconnection.cpp @ 35 ) Setting DB name 
TRACE 2015-02-13 15:10:32.292 ( sql/databaseconnection.cpp @ 37 ) Opening database 
TRACE 2015-02-13 15:10:32.292 ( sql/databaseconnection.cpp @ 45 ) Preparing tables 
TRACE 2015-02-13 15:10:32.292 ( sql/databaseconnection.cpp @ 54 ) Creating filter table 
TRACE 2015-02-13 15:10:32.328 ( sql/databaseconnection.cpp @ 57 ) Adding to filter table 
TRACE 2015-02-13 15:10:32.356 ( sql/databaseconnection.cpp @ 59 ) Addition complete 
DEBUG 2015-02-13 15:10:32.356 ( threads/counterrunner.cpp @ 39 ) CounterRunner exiting. 
TRACE 2015-02-13 15:10:32.382 ( sql/notetable.cpp @ 819 ) Fetching Resources?  false  With binary?  false 
TRACE 2015-02-13 15:10:32.387 ( sql/notetable.cpp @ 825 ) Fetched resources 
TRACE 2015-02-13 15:10:32.388 ( sql/notetable.cpp @ 819 ) Fetching Resources?  false  With binary?  false 
TRACE 2015-02-13 15:10:32.391 ( sql/notetable.cpp @ 825 ) Fetched resources 
TRACE 2015-02-13 15:10:32.391 ( nixnote.cpp @ 148 ) Connecting signals 
DEBUG 2015-02-13 15:10:32.707 ( utilities/encrypt.cpp @ 84 ) Return Code:  0 
DEBUG 2015-02-13 15:10:33.021 ( utilities/encrypt.cpp @ 84 ) Return Code:  0 
DEBUG 2015-02-13 15:10:33.027 ( nixnote.cpp @ 213 ) Exiting NixNote constructor 
DEBUG 2015-02-13 15:10:33.046 ( threads/indexrunner.cpp @ 53 ) Starting IndexRunner 
DEBUG 2015-02-13 15:10:33.046 ( threads/syncrunner.cpp @ 50 ) Starting SyncRunner.synchronize() 
DEBUG 2015-02-13 15:10:33.046 ( sql/databaseconnection.cpp @ 32 ) SQL drivers available:  ("QSQLITE", "QMYSQL3", "QMYSQL") 
DEBUG 2015-02-13 15:10:33.047 ( sql/databaseconnection.cpp @ 32 ) SQL drivers available:  ("QSQLITE", "QMYSQL3", "QMYSQL") 
TRACE 2015-02-13 15:10:33.047 ( sql/databaseconnection.cpp @ 33 ) Adding database SQLITE 
TRACE 2015-02-13 15:10:33.047 ( sql/databaseconnection.cpp @ 33 ) Adding database SQLITE 
TRACE 2015-02-13 15:10:33.047 ( sql/databaseconnection.cpp @ 35 ) Setting DB name 
TRACE 2015-02-13 15:10:33.047 ( sql/databaseconnection.cpp @ 35 ) Setting DB name 
TRACE 2015-02-13 15:10:33.047 ( sql/databaseconnection.cpp @ 37 ) Opening database 
TRACE 2015-02-13 15:10:33.047 ( sql/databaseconnection.cpp @ 37 ) Opening database 
TRACE 2015-02-13 15:10:33.047 ( sql/databaseconnection.cpp @ 45 ) Preparing tables 
TRACE 2015-02-13 15:10:33.047 ( sql/databaseconnection.cpp @ 45 ) Preparing tables 
TRACE 2015-02-13 15:10:33.050 ( sql/databaseconnection.cpp @ 54 ) Creating filter table 
TRACE 2015-02-13 15:10:33.050 ( sql/databaseconnection.cpp @ 54 ) Creating filter table 
TRACE 2015-02-13 15:10:33.073 ( sql/databaseconnection.cpp @ 57 ) Adding to filter table 
TRACE 2015-02-13 15:10:33.095 ( sql/databaseconnection.cpp @ 59 ) Addition complete 
DEBUG 2015-02-13 15:10:33.095 ( threads/indexrunner.cpp @ 62 ) Indexrunner initialized. 
TRACE 2015-02-13 15:10:33.124 ( sql/databaseconnection.cpp @ 57 ) Adding to filter table 
TRACE 2015-02-13 15:10:33.152 ( sql/databaseconnection.cpp @ 59 ) Addition complete 
DEBUG 2015-02-13 15:10:33.153 ( communication/communicationmanager.cpp @ 112 ) Inside CommunicationManager::initNoteStore() 
DEBUG 2015-02-13 15:10:33.153 ( communication/communicationmanager.cpp @ 143 ) Inside CommunicationManager::getUserInfo 
DEBUG 2015-02-13 15:10:35.097 ( communication/communicationmanager.cpp @ 120 ) "https://www.evernote.com/edam/note/s384" 
TRACE 2015-02-13 15:10:35.097 ( threads/syncrunner.cpp @ 90 ) Sync thread: 140340721796864 
DEBUG 2015-02-13 15:10:35.097 ( communication/communicationmanager.cpp @ 143 ) Inside CommunicationManager::getUserInfo 
DEBUG 2015-02-13 15:10:36.079 ( threads/syncrunner.cpp @ 126 ) --->>>  Current Chunk High Sequence Number:  8371 
DEBUG 2015-02-13 15:10:36.079 ( threads/syncrunner.cpp @ 127 ) --->>>  Last User High Sequence Number:  8129 
 INFO 2015-02-13 15:10:36.079 ( nixnote.cpp @ 1564 ) "Beginning Sync" 
DEBUG 2015-02-13 15:10:36.079 ( threads/syncrunner.cpp @ 130 ) Remote changes found 
DEBUG 2015-02-13 15:10:36.079 ( threads/syncrunner.cpp @ 131 ) Downloading changes 
TRACE 2015-02-13 15:10:36.079 ( threads/syncrunner.cpp @ 188 ) Entering SyncRunner::SyncRemoteToLocal() 
 INFO 2015-02-13 15:10:36.079 ( nixnote.cpp @ 1564 ) "Downloading changes" 
DEBUG 2015-02-13 15:10:36.466 ( communication/communicationmanager.cpp @ 983 ) All notes retrieved.  Getting resources 
DEBUG 2015-02-13 15:10:36.467 ( communication/communicationmanager.cpp @ 996 ) Getting ink notes 
DEBUG 2015-02-13 15:10:36.467 ( threads/syncrunner.cpp @ 225 ) -(Pass 1)->>>>  Old USN: 8129  New USN: 8371 
 INFO 2015-02-13 15:10:36.467 ( nixnote.cpp @ 1564 ) "Download 0% complete for notebooks, tags, & searches." 
 INFO 2015-02-13 15:10:36.467 ( nixnote.cpp @ 1564 ) "Download complete for notebooks, tags, & searches.  Downloading notes." 
DEBUG 2015-02-13 15:10:37.072 ( communication/communicationmanager.cpp @ 983 ) All notes retrieved.  Getting resources 
DEBUG 2015-02-13 15:10:37.072 ( communication/communicationmanager.cpp @ 996 ) Getting ink notes 
DEBUG 2015-02-13 15:10:37.072 ( threads/syncrunner.cpp @ 254 ) -(Pass 2) ->>>>  Old USN: 8129  New USN: 8179 
TRACE 2015-02-13 15:10:37.072 ( threads/syncrunner.cpp @ 358 ) Entering SyncRunner::syncRemoteExpungedNotes 
 INFO 2015-02-13 15:10:37.072 ( nixnote.cpp @ 1564 ) "Download 0% complete." 
TRACE 2015-02-13 15:10:37.076 ( sql/notetable.cpp @ 819 ) Fetching Resources?  true  With binary?  false 
TRACE 2015-02-13 15:10:37.083 ( sql/notetable.cpp @ 825 ) Fetched resources 
TRACE 2015-02-13 15:10:37.084 ( sql/notetable.cpp @ 819 ) Fetching Resources?  true  With binary?  false 
TRACE 2015-02-13 15:10:37.087 ( sql/notetable.cpp @ 825 ) Fetched resources 
TRACE 2015-02-13 15:10:37.088 ( sql/notetable.cpp @ 819 ) Fetching Resources?  true  With binary?  false 
TRACE 2015-02-13 15:10:37.091 ( sql/notetable.cpp @ 825 ) Fetched resources 
TRACE 2015-02-13 15:10:37.092 ( sql/notetable.cpp @ 819 ) Fetching Resources?  true  With binary?  false 
TRACE 2015-02-13 15:10:37.095 ( sql/notetable.cpp @ 825 ) Fetched resources 
TRACE 2015-02-13 15:10:37.096 ( sql/notetable.cpp @ 819 ) Fetching Resources?  true  With binary?  false 
TRACE 2015-02-13 15:10:37.098 ( sql/notetable.cpp @ 825 ) Fetched resources 
TRACE 2015-02-13 15:10:37.099 ( sql/notetable.cpp @ 819 ) Fetching Resources?  true  With binary?  false 
TRACE 2015-02-13 15:10:37.102 ( sql/notetable.cpp @ 825 ) Fetched resources 
TRACE 2015-02-13 15:10:37.103 ( sql/notetable.cpp @ 819 ) Fetching Resources?  true  With binary?  false 
TRACE 2015-02-13 15:10:37.106 ( sql/notetable.cpp @ 825 ) Fetched resources 
TRACE 2015-02-13 15:10:37.107 ( sql/notetable.cpp @ 819 ) Fetching Resources?  true  With binary?  false 
TRACE 2015-02-13 15:10:37.110 ( sql/notetable.cpp @ 825 ) Fetched resources 
TRACE 2015-02-13 15:10:37.111 ( sql/notetable.cpp @ 819 ) Fetching Resources?  true  With binary?  false 
TRACE 2015-02-13 15:10:37.115 ( sql/notetable.cpp @ 825 ) Fetched resources 
TRACE 2015-02-13 15:10:37.116 ( sql/notetable.cpp @ 819 ) Fetching Resources?  true  With binary?  false 
TRACE 2015-02-13 15:10:37.120 ( sql/notetable.cpp @ 825 ) Fetched resources 
TRACE 2015-02-13 15:10:37.121 ( sql/notetable.cpp @ 819 ) Fetching Resources?  true  With binary?  false 
TRACE 2015-02-13 15:10:37.125 ( sql/notetable.cpp @ 825 ) Fetched resources 
TRACE 2015-02-13 15:10:37.126 ( sql/notetable.cpp @ 819 ) Fetching Resources?  true  With binary?  false 
TRACE 2015-02-13 15:10:37.129 ( sql/notetable.cpp @ 825 ) Fetched resources 
TRACE 2015-02-13 15:10:37.130 ( sql/notetable.cpp @ 819 ) Fetching Resources?  true  With binary?  false 
TRACE 2015-02-13 15:10:37.133 ( sql/notetable.cpp @ 825 ) Fetched resources 
TRACE 2015-02-13 15:10:37.134 ( sql/notetable.cpp @ 819 ) Fetching Resources?  true  With binary?  false 
TRACE 2015-02-13 15:10:37.137 ( sql/notetable.cpp @ 825 ) Fetched resources 
TRACE 2015-02-13 15:10:37.138 ( sql/notetable.cpp @ 819 ) Fetching Resources?  true  With binary?  false 
TRACE 2015-02-13 15:10:37.141 ( sql/notetable.cpp @ 825 ) Fetched resources 
TRACE 2015-02-13 15:10:37.142 ( sql/notetable.cpp @ 819 ) Fetching Resources?  true  With binary?  false 
TRACE 2015-02-13 15:10:37.145 ( sql/notetable.cpp @ 825 ) Fetched resources 
TRACE 2015-02-13 15:10:37.146 ( sql/notetable.cpp @ 819 ) Fetching Resources?  true  With binary?  false 
TRACE 2015-02-13 15:10:37.149 ( sql/notetable.cpp @ 825 ) Fetched resources 
TRACE 2015-02-13 15:10:37.150 ( sql/notetable.cpp @ 819 ) Fetching Resources?  true  With binary?  false 
TRACE 2015-02-13 15:10:37.153 ( sql/notetable.cpp @ 825 ) Fetched resources 
TRACE 2015-02-13 15:10:37.153 ( sql/notetable.cpp @ 819 ) Fetching Resources?  true  With binary?  false 
TRACE 2015-02-13 15:10:37.155 ( sql/notetable.cpp @ 825 ) Fetched resources 
TRACE 2015-02-13 15:10:37.200 ( sql/notetable.cpp @ 819 ) Fetching Resources?  true  With binary?  false 
TRACE 2015-02-13 15:10:37.205 ( sql/notetable.cpp @ 825 ) Fetched resources 
TRACE 2015-02-13 15:10:37.254 ( sql/notetable.cpp @ 819 ) Fetching Resources?  true  With binary?  false 
TRACE 2015-02-13 15:10:37.259 ( sql/notetable.cpp @ 825 ) Fetched resources 
Error: signal 11:
nixnote2(_Z13fault_handleri+0x18)[0x47f8c8]
/lib/x86_64-linux-gnu/libc.so.6(+0x36d40)[0x7fa40ad42d40]
nixnote2(_ZN9NoteTable7expungeEi+0x3de)[0x52fd7e]
nixnote2(_ZN9NoteTable7expungeE7QString+0x41)[0x5301b1]
nixnote2(_ZN10SyncRunner23syncRemoteExpungedNotesE5QListI7QStringE+0x82)[0x4c67c2]
nixnote2(_ZN10SyncRunner16processSyncChunkERN10qevercloud9SyncChunkEi+0x9e2)[0x4cb782]
nixnote2(_ZN10SyncRunner17syncRemoteToLocalEi+0x4c6)[0x4cbff6]
nixnote2(_ZN10SyncRunner12evernoteSyncEv+0x2fe)[0x4cd72e]
nixnote2(_ZN10SyncRunner11synchronizeEv+0x21e)[0x4ce06e]
nixnote2[0x6f3335]
/usr/lib/x86_64-linux-gnu/libQtCore.so.4(_ZN7QObject5eventEP6QEvent+0x24e)[0x7fa40ba87c1e]
/usr/lib/x86_64-linux-gnu/libQtGui.so.4(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x8c)[0x7fa40c2e8e2c]
/usr/lib/x86_64-linux-gnu/libQtGui.so.4(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x270)[0x7fa40c2ef4a0]
nixnote2(_ZN11Application6notifyEP7QObjectP6QEvent+0x15)[0x61e3a5]
/usr/lib/x86_64-linux-gnu/libQtCore.so.4(_ZN16QCoreApplication14notifyInternalEP7QObjectP6QEvent+0x6d)[0x7fa40ba6f4dd]
/usr/lib/x86_64-linux-gnu/libQtCore.so.4(_ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData+0x1ed)[0x7fa40ba72b3d]
/usr/lib/x86_64-linux-gnu/libQtCore.so.4(+0x1aaf83)[0x7fa40ba9cf83]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x254)[0x7fa4088cce04]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x49048)[0x7fa4088cd048]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x2c)[0x7fa4088cd0ec]
/usr/lib/x86_64-linux-gnu/libQtCore.so.4(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x8e)[0x7fa40ba9c7be]
/usr/lib/x86_64-linux-gnu/libQtCore.so.4(_ZN10QEventLoop13processEventsE6QFlagsINS_17ProcessEventsFlagEE+0x2f)[0x7fa40ba6e0af]
/usr/lib/x86_64-linux-gnu/libQtCore.so.4(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0x175)[0x7fa40ba6e3a5]
/usr/lib/x86_64-linux-gnu/libQtCore.so.4(_ZN7QThread4execEv+0xbf)[0x7fa40b96ac5f]
/usr/lib/x86_64-linux-gnu/libQtCore.so.4(+0x7b32f)[0x7fa40b96d32f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8182)[0x7fa40a68d182]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7fa40ae0700d]
Error: signal 11:
nixnote2(_Z13fault_handleri+0x18)[0x47f8c8]
/lib/x86_64-linux-gnu/libc.so.6(+0x36d40)[0x7fa40ad42d40]
/usr/lib/x86_64-linux-gnu/libQtCore.so.4(_ZNK18QThreadStorageData3getEv+0x22)[0x7fa40b96b642]
/usr/lib/x86_64-linux-gnu/libQtGui.so.4(+0x3decd6)[0x7fa40c4fdcd6]
/usr/lib/x86_64-linux-gnu/libQtGui.so.4(_ZNK12QFontPrivate15engineForScriptEi+0x72)[0x7fa40c4fddb2]
/usr/lib/x86_64-linux-gnu/libQtGui.so.4(_ZNK13QFontMetricsF7leadingEv+0xe)[0x7fa40c512c2e]
/usr/lib/x86_64-linux-gnu/libQtGui.so.4(+0x312b1d)[0x7fa40c431b1d]
/usr/lib/x86_64-linux-gnu/libQtGui.so.4(+0x313681)[0x7fa40c432681]
/usr/lib/x86_64-linux-gnu/libQtGui.so.4(_ZNK12QFontMetrics12boundingRectERK5QRectiRK7QStringiPi+0xf3)[0x7fa40c512523]
/usr/lib/x86_64-linux-gnu/libQtGui.so.4(_ZNK12QFontMetrics4sizeEiRK7QStringiPi+0x

**Comment by baumgarr** [comment]
Try beta 4 and see if it helps.  There were some changes in the sync code that may help.

**Comment by bobbruno** [comment]
I downloaded it, and it seems to work fine now. Thanks.

**Comment by baumgarr** [comment]
Cool.  Thanks.
