### ISSUE TITLE
Intermitent input focus loss when sync starts while editing note

### ISSUE THREAD

**Issue by fastcat** [baumgarr/Nixnote2#42]
Intermittently (but frequently) if I'm typing and a scheduled sync runs, the input focus seems to be lost.  The cursor keeps blinking but typing does nothing.

Watching the trace logs when this happens, I see that it redoes the note selection criteria in the view, and I'm wondering if that is effectively re-selecting and thus re-loading the note editor?

**Comment by baumgarr** [comment]
I have an idea of what may be happening.  Under some circumstances I need to reload the note after a sync.  If this happens the focus may be lost.  I put another check in that may help.  Go ahead & do a pull and see if the problem remains.

**Comment by fastcat** [comment]
Definitely better :)

**Comment by baumgarr** [comment]
Cool.  That was an easier fix than I anticipated.
