### ISSUE TITLE
I Cannot authorize Initial Sync

### ISSUE THREAD

**Issue by pascencio** [baumgarr/Nixnote2#421]
Hi,

I have installed Nixnote2 on Manjaro Linux. I trying to sync a business account, these account was created using Google account.

![image](https://user-images.githubusercontent.com/9783678/37929037-30a97e7c-3115-11e8-8db8-628783319a5a.png)

![image](https://user-images.githubusercontent.com/9783678/37929059-3efbdf42-3115-11e8-86ac-17f80948e9e0.png)

Thanks in advance!

**Comment by bartkooijman** [comment]
I think this is the same as #420 . This hopefully ups the prio.

**Comment by bartkooijman** [comment]
All of a sudden it works for me again. This time I tried from a different location/network.

**Comment by pascencio** [comment]
thanks @bartkooijman that works!
