### ISSUE TITLE
Nonexistent value access exception during sync

### ISSUE THREAD

**Issue by d1vanov** [baumgarr/Nixnote2#43]
Hi,

One rainy day in Saint-Petersburg I encountered one more QEvercloud's nonexistent value access exception during the sync and I was able to track it down:

sql/notetable.cpp, starting from line 669:
```c++
        // We search the table to get the name in the correct case.
        // We lowercased them above to sort properly without regards
        // to case.  Now, for the note list we need the correct case
        for (int i=0; i<sortedNames.size(); i++) {
            if (i>0)
                tagName = tagName+", ";
            Tag currentTag;
            qint32 tagLid = tagTable.findByName(sortedNames[i], account);
            tagTable.get(currentTag, tagLid);
            tagName = tagName + currentTag.name;    // <-- here the exception is thrown
        }
```
I found that in my case the exception was thrown because currentTag.name was not set. Moreover, it seems currentTag was simply not found in tagTable because its guid, parentGuid and updateSequenceNum were not set just as well. I don't know for sure whether such case is "valid" logically so I don't offer a quick workaround of checking whether currentTag.name.isSet() as a pull request.

**Comment by baumgarr** [comment]
Thanks.  I'll put in a quick check to check the isSet().  I don't think it should logically happen so it isn't addressing the root cause, but at least it won't cause an exception.

Thanks agian!
