### ISSUE TITLE
Sync error: "Unable to update note.  Invalid note structure : :EDAMUserException: ENML_VALIDATION parameter=Attribute \"type\" is required and must be specified for element type \"en-media\"."

### ISSUE THREAD

**Issue by vstepaniuk** [baumgarr/Nixnote2#437]
After WebClipping the Wikipedia article the sync with no changes to the note in NixNote 2.0 (Ubuntu 17.10 x64) works fine. But when I change the font size, I cannot sync this note anymore, and get the following error log:
```
INFO 2018-05-19 16:17:55.329 ( nixnote.cpp @ 1880 ) "Beginning Sync" 
ERROR 2018-05-19 16:17:56.899 ( communication/communicationmanager.cpp @ 557 ) EDAMUserException: 11 
ERROR 2018-05-19 16:17:56.899 ( threads/syncrunner.cpp @ 1149 ) "Error uploading note:Foxit Reader - Wikipedia" 
 INFO 2018-05-19 16:17:56.900 ( nixnote.cpp @ 1880 ) "Unable to update note.  Invalid note structure : :EDAMUserException: ENML_VALIDATION parameter=Attribute \"type\" is required and must be specified for element type \"en-media\"." 
 INFO 2018-05-19 16:17:56.901 ( nixnote.cpp @ 1880 ) "Unable to update note.  Invalid note structure : :EDAMUserException: ENML_VALIDATION parameter=Attribute \"type\" is required and must be specified for element type \"en-media\"."
```

**Comment by robert7** [comment]
I did complete refactoring of the HTML cleanup in [v2.1 - I suggest - try the new version](https://github.com/robert7/nixnote2/releases), it should work now.

**Comment by vstepaniuk** [comment]
Yes, now it is working! Thanks!

**Comment by vstepaniuk** [comment]
Now, how can I clean my Ubuntu 18.04 from everything related to NixNote AppImage? ))

**Comment by robert7** [comment]
Just delete the one file.. the v2.1 AppImage consist just of the one file you downloaded..
But why you want to clean it? (should be at least a bit better then the previous version..)

**Comment by vstepaniuk** [comment]
No, it's a good one! I am just getting away from Evernote in general... Thank you!
