### ISSUE TITLE
Corrupt note only in Nixnote

### ISSUE THREAD

**Issue by leighss** [baumgarr/Nixnote2#468]
Version: 201812070904~2.1.1~ubuntu18.04.1

1. Thanks - great work!

2. I have a note that is only in Nixnote (i.e. not in Evernote) that does not delete
The title in the list is in bold
It has three tags and is in Notebook but also appears at the top of all list (any Notebook or Tag)
It is also in Trash
I also cant change title notebook or tags etc (greyed out in upper pane and cant drag & drop)
How can I get rid of this note please?

**Comment by robert7** [comment]
hi,
..looks weird. It could be that for some reason a "read-only protection" for this particular note was activated. This happens, it some internal inconsistency for specific note is detected. It is meant as protection - if Nixnote can't safely update the note, it marks it as "read only".

Normally this should not happen very often (so far I've seen ~1 case). It the note is already synced, then you can edit the note in web client, then sync back to Nixnote and the problem should go away. But it your case it seems, the note is someway corrupted, but it has not yet been synced. So you can't use the workaround with web client.

"Brute force" solution would be - stop nixnote - to backup away the data directory (menu Help/Data and log location info - to find out where it is) and sync all from scratch.

Later I can check, if I can adjust the logic, that Delete is always enabled.

**Comment by leighss** [comment]
Thanks Robert.

I was experimenting unpinned the note and it disappeared :)
(actually I pinned and then unpinned but I am pretty sure it was already pinned)

Maybe the previous deleting of this note had actually worked (I did get asked for delete confirmation) but a 'ghost' was still there because it was pinned?

I didn't really know what 'pinned' meant so I had another fresh look and saw in the [Legacy Documentation](https://github.com/robert7/nixnote2/wiki/Legacy-Documentation#using-nixnote) the following,

_"Notes can be “pinned”. A pinned note will always appear in the note list regardless of any other selection criteria. If a notebook is closed, however, a pinned note will not be visible. If you have the tray icon enabled, pinned notes are also quickly available via a menu option."_

which explained why that note was at the top of all lists?

All good, thanks for help

**Comment by robert7** [comment]
yes. exactly. pinning means the note is always on top. I personally don't use the feature. it could have sense if you work on the note for let say few days, then it could have sense to let it "pinned".. but it depends on workflow.

it could be the note was on the top even, if it was in "trash".

there is alternative feature to this: there is special tag "important" - if you mark note with "important" tag, and it is found in the search, it always appears on the top of the search. but I also use this only seldom.
