### ISSUE TITLE
Changing Note List columns not saved.

### ISSUE THREAD

**Issue by Twoflower2** [baumgarr/Nixnote2#471]
Changing Note List columns not saved and change back to I presume the default after NixNote is restarted.

Changing here means not choosing which columns to display, but the actual order which is left column of choice then then one next to that of choice and so on and so on.

Please auto save the column manual column changes so they are still used in the next time NixNote starts up.

Thanks.

**Comment by robert7** [comment]
@Twoflower2 
actually this should work
some screenshoots
![screen_20190211_06](https://user-images.githubusercontent.com/1135218/52567121-d08e1080-2e0b-11e9-92c8-4603ddd2cf8e.png)
![screen_20190211_08](https://user-images.githubusercontent.com/1135218/52567129-d4219780-2e0b-11e9-99c1-7a23e0a39e96.png)


the order is stored in config file e.g.
![screen_20190211_07](https://user-images.githubusercontent.com/1135218/52566995-7c832c00-2e0b-11e9-9537-3c05f15292d6.png)

I did the tests with the 2.1 version, but as far I know this should also work with the 2.0 version
you may want to try the newer version: https://github.com/robert7/nixnote2/releases

**Comment by Twoflower2** [comment]
Thanks @robert7 

openSUSE still have the old 2.0 version, but I asked the lad building it to build 2.1.

BTW I see you have forked NixNote2 which looks maintained better than this one. Can the readme of this one be edited/updated to say to rather use your fork because the builders for the distros is not aware of your maintained fork?

**Comment by robert7** [comment]
unfortunately I can't update the original readme as the original maintainer is not available and I have no access :(

**Comment by Twoflower2** [comment]
Ok thanks for your work with your fork - https://github.com/robert7/nixnote2. I'd really like to try it out because I used Evernote on Windows and found NixNote2, well, not on the same level, but I have to use it on Linux.

**Comment by robert7** [comment]
@Twoflower2 until open suse version is updated, you could use the AppImage version which works on ~all distributions. Just download the "[AppImage](https://github.com/robert7/nixnote2/releases)" file, mark as executable and run. It should work out of the box, no dependencies. The version 2.1 is compatible with 2.0 data, so you can use them interchangeably.

Yes NixNote is simpler then official Evernote client, but should be OK for daily work. The mine version has some minor improvements, like simple relevance sort.

**Comment by Twoflower2** [comment]
@robert7 Two lads making openSUSE packages have already made packages now after I asked them to switch to your fork, thanks.

https://software.opensuse.org/package/nixnote2
