### ISSUE TITLE
Resize Table Columns

### ISSUE THREAD

**Issue by ghost** [baumgarr/Nixnote2#473]
I just started using Nixnote2 on Linux Mint.  I had exported some OneNote notebooks to Evernote and was able to successfully import them into NixNote2.
These notes use tables quite a lot.

I was able to add new rows by using the tab key. 

But am not able to resize the columns.  If I hover over the vertical column divider the cursor doesn't change to a "double bar" that I could then move.

Thanks!

**Comment by robert7** [comment]
Hi,
this is currently not implemented and doesn't seem to be easily possible.

**Comment by ghost** [comment]
OK Robert. Thanks for the response.
