### ISSUE TITLE
extense note titles display

### ISSUE THREAD

**Issue by raul-xag** [baumgarr/Nixnote2#477]
First, thanks to the developers for building a Nixnote version for Arch-based distros.

This Nixnote2 version is the "nixnote2-2.0.2-0.x86_64.rpm"
There's an issue with long note titles.
I'm using Manjaro Linux XFCE.

![DeepinScreenshot_select-area_20190402214401](https://user-images.githubusercontent.com/49216144/55445192-7b12ec00-5590-11e9-8084-31e5a90fa071.png)

I know I can drag the title column to the right and see the full title in one single line. I'm only reporting the bug.

Thanks in advance.

**Comment by robert7** [comment]
This repository is only for 2.0.x and is currently not maintained (as the maintainer is not reachable).
The current version is 2.1.3 see https://github.com/robert7/nixnote2/releases
And you can change the width of the column freely just by dragging it.
This should also work for 2.0.x

Not sure what is your problem... what is the bug?

![screen_20190417_07](https://user-images.githubusercontent.com/1135218/56277937-925fe680-6105-11e9-96e8-ba9bb7374ea7.png)
