### ISSUE TITLE
Sync on Fedora 28-KDE Plasma BAD_DATA_FORMAT parameter

### ISSUE THREAD

**Issue by gseaborn** [baumgarr/Nixnote2#479]
Am running nixnote2 ver. 2.1.2  on Fedora 28 and everytime I sync I get the following error:

Error in sync: EDAMUserException[BAD_DATA_FORMAT]: EDAMUserException: BAD_DATA_FORMAT parameter=authenticationToken

I am running nixnote2 ver. 2.1.2 on my Laptop with Fedora 29, and am not getting the sync error.

Thanks,
Gregory

**Comment by robert7** [comment]
Hi,
pls all issues for the version 2.1+ should be reported in my fork repository https://github.com/robert7/nixnote2. As this repository is only for 2.0.x and ist currently not maintained (as the maintainer is not reachable).

Anyway... the "BAD_DATA_FORMAT parameter=authenticationToken" suggest a problem with auth token - maybe some config file mismatch.

you could try to run with different config+data directory, to see if it makes difference.
see: https://github.com/robert7/nixnote2/wiki/Relocation-of-config-and-data-directory

e.g. nixnote2 --configDir=/any/directory/you-want
this will create new fresh profile in "/any/directory/you-want" .. you will need to login again & do a fresh sync

to see where the config/data files are now - see "Help/Data and log location info"

**Comment by gseaborn** [comment]
Thanks Robert.  Tried your suggestion, and still didn't work properly.  I uninstalled ver 2.1 and the previous packagekit beta version, cleaned the system, and reinstalled ver 2.1 from the nunodias repo.  It's syncing, without, an error; am just waiting for all my notes to show up again.  Will close this issue, and do my best to remember to post issues in the proper spot.  Thanks again.
