### ISSUE TITLE
Sync stops after syncing 200 notes

### ISSUE THREAD

**Issue by panditarevolution** [baumgarr/Nixnote2#48]
I installed nixnote 2 beta 3 on debian 8. At first it seemed to work though it doesn't sync anymore after 200 notes. I also noticed that the last note synced was from 31/12/14... not sure which of these numbers is a coincidence...

There are no visisble error messages and the sync icon keeps looking like nixnote would try to sync.

Based on the terminal output it does try to get notes, though I previously left it running for an hour and more and no more notes are being synced.

Here's the terminal output:

```
Gtk-Message: Failed to load module "canberra-gtk-module"
...
 INFO 2015-05-15 07:06:46.010 ( main.cpp @ 139 ) Built with Qt 4.8.6 running on 4.8.6 
 INFO 2015-05-15 07:06:49.147 ( nixnote.cpp @ 1554 ) "Beginning Sync" 
 INFO 2015-05-15 07:06:49.148 ( nixnote.cpp @ 1554 ) "Downloading changes" 
 INFO 2015-05-15 07:06:49.965 ( nixnote.cpp @ 1554 ) "Download 0% complete for notebooks, tags, & searches." 
 INFO 2015-05-15 07:06:57.227 ( nixnote.cpp @ 1554 ) "Download 96% complete for notebooks, tags, & searches." 
 INFO 2015-05-15 07:06:57.228 ( nixnote.cpp @ 1554 ) "Download complete for notebooks, tags, & searches.  Downloading notes." 
INFO 2015-05-15 07:10:21.765 ( nixnote.cpp @ 1554 ) "Download 0% complete." 
```

**Comment by baumgarr** [comment]
About the only thing I could think would cause this is if you exceeded the API limit, but it should give you an error message about that.

Could you try going into Edit/Preferences & setting the level of messages to "Debug".  That should give some more information.

**Comment by baumgarr** [comment]
No response.  Closing.
