### ISSUE TITLE
Unable to modify language settings

### ISSUE THREAD

**Issue by 0x7a7a** [baumgarr/Nixnote2#480]
I found that I can't switch languages. After rebooting, it doesn't work. I switched Chinese, and I tried other languages as well.
  By the way, how to set the language node in the configuration file, I want to try to modify it directly in the configuration file to see if it can take effect.

**Comment by 0x7a7a** [comment]
nixnote2 version:2.1.0
system: arch linux

**Comment by robert7** [comment]
Pls. provide more info...
The locale only switches after app restart.. See screenshoots how I switched from "System default" to "Czech"... and where its in config.

![screen_20190429_04](https://user-images.githubusercontent.com/1135218/56918633-cf8d8680-6abe-11e9-9243-ecf603fec565.png)
![screen_20190429_05](https://user-images.githubusercontent.com/1135218/56918638-d5836780-6abe-11e9-88af-7de61e4ec07a.png)
![screen_20190429_06](https://user-images.githubusercontent.com/1135218/56918643-d9af8500-6abe-11e9-8abf-6e2b1c6d5268.png)
![screen_20190429_07](https://user-images.githubusercontent.com/1135218/56918647-dcaa7580-6abe-11e9-9d29-b8b442c6073d.png)

**Comment by 0x7a7a** [comment]
Robert, thank you for your reply
I tried to modify the settings again according to your instructions.
I found that it can only be set to English or Czech, these two can be effective (after restarting the application)
Other languages have been shown in the configuration file, but the nixnote is still in English.
I doubt if there is a lack of language files?

Here is the log of loglevel=1
Recorded the process from opening the app to switching to Chinease and then exiting
[nixnote.log](https://github.com/baumgarr/nixnote2/files/3145050/nixnote.log)

**Comment by robert7** [comment]
your logfile says you are trying to load "en_US" which was not found, so it reverted to default..
![screen_20190507_25](https://user-images.githubusercontent.com/1135218/57310025-5f4bba00-70e9-11e9-95e0-d6dcd8e71385.png)

you can try following
1, install newest version (you are using 2.1.0 where 2.1.3 is current -. see https://github.com/robert7/nixnote2/releases )
2, then look what translations you have actually installed
3, the you can manually set "translations" in config file to one of installed translations
4, then check in log file the lines starting with "Looking for translations"

![screen_20190507_23](https://user-images.githubusercontent.com/1135218/57310194-aafe6380-70e9-11e9-9b93-7e74fd92869e.png)

![screen_20190507_24](https://user-images.githubusercontent.com/1135218/57310209-ae91ea80-70e9-11e9-8f0f-34560ebe7ef1.png)

as you see I activated german translation


and now chinese
![screen_20190507_26](https://user-images.githubusercontent.com/1135218/57310320-dd0fc580-70e9-11e9-856d-a129be3aaab2.png)

**Comment by robert7** [comment]
>I doubt if there is a lack of language files?

in one of the older versions, there was problem with missing translations
this has been corrected long ago
maybe 2.1.0 was affected.. so try 2.1.3 :)

**Comment by 0x7a7a** [comment]
Thank you for your help, my version is too backward.
Because the archive of arch is only 2.1.0
Finally, I used the latest version of appimage without this problem.
thank you very much
