### ISSUE TITLE
Nixnote keeps on crashing on fedora 29

### ISSUE THREAD

**Issue by vinliao** [baumgarr/Nixnote2#481]
I've been experimenting with nixnote for a few days. I love what it's offering and would like to use the app more often but it keeps crashing. It usually crashes when I change tabs. It doesn't happen all the time but it's annoying because when I alt+tab I want to jot down words immediately and find out that it crashes.

**Comment by robert7** [comment]
Hi,
you don't write, which version are you using..
The current version is 2.1.3 - for 2.1+ see https://github.com/robert7/nixnote2
This repository is currently not maintained (as the maintainer is not reachable).
If the 2.1 crashes, then pls attach log file with DEBUG level (see HowTo in wiki).
