### ISSUE TITLE
Import and Export

### ISSUE THREAD

**Issue by tedleyem** [baumgarr/Nixnote2#483]
I have two different acccounts for nixnote (evernote accounts) and would like to merge the two. The work email account has notebooks with notes in it that span over a year (well over 300+ notes). is there a way to export all these notes and import them into an "imported" notebook into my personal nixnote account? I currently have it set up so I can switch from one to another but I would like to have them all in one place at the moment. Exporting notes only exports the current viewed note (which looks to be the case for all export options). 
Can someone assist?

**Comment by robert7** [comment]
Hi
This repository is currently not maintained (as the maintainer is not reachable).
The current version is 2.1.3 - for 2.1+ see https://github.com/robert7/nixnote2

Following screenshoot is from v.2.1.3
![screen_20190510_02](https://user-images.githubusercontent.com/1135218/57539854-ad5ff800-734b-11e9-9125-c1b59bdf9d69.png)

but the export/import of all notes worked also in 2.0 as far I know (i thik the menu option was called "backup")

**Comment by tedleyem** [comment]
Thank you ill download that version and close this issue.
