### ISSUE TITLE
install.sh not working

### ISSUE THREAD

**Issue by stlorenz** [baumgarr/Nixnote2#49]
sudo make install calls "install.sh"

this tries to execute the following commands:
````
cp $package_dir/usr/share/applications/nixnote2.desktop /usr/share/applications/nixnote2.desktop
mkdir /usr/share/nixnote2
cp -r $package_dir/usr/share/nixnote2/* /usr/share/nixnote2/
cp $package_dir/usr/bin/nixnote2 /usr/bin/nixnote2
````

but the source dirs do not exist, I will submit a pull request with the updated paths rusing the ones given in the wiki

**Comment by baumgarr** [comment]
Building it for distribution is more complex than that.  There are a series of scripts in the package_scripts directory that build the deb, rpm, & tar files as well as do a bunch of other things.  Those scripts build a series of directories and copy the install.sh script into it for final distribution.  You can then use the tar file and run the install.sh for final installation.

**Comment by stlorenz** [comment]
okay, thats true. But "sudo make install" should word as expected, or am i wrong?

**Comment by baumgarr** [comment]
No, that won't work.  I think Qt puts that directive in the makefile, but I
never did.

**Comment by stlorenz** [comment]
Thanks, good to know. 

I have no clue how this could be fixed but theres one issue when building it myself on Fedora.

lhunspell is called lhunspell-1.3 in the Fedora World and i have always to fix the makefile manually. is it possible to put a "if-statement" in there?

**Comment by stlorenz** [comment]
Closed, issse seems to be not that relevant
