### ISSUE TITLE
Official website

### ISSUE THREAD

**Issue by b1llow** [baumgarr/Nixnote2#492]
![image](https://user-images.githubusercontent.com/24983369/66211805-52aaac80-e6ef-11e9-9229-740a2ca5f4a3.png)

The official website looks like above, can we update it?

**Comment by b1llow** [comment]
maybe it dead.

**Comment by robert7** [comment]
not sure which official page you mean? did you mean: http://nixnote.org/
unfortunately this can't be updated as the maintainer is not reachable..

but anyway.. current "project page" is the new wiki.. 
https://github.com/robert7/nixnote2/wiki
