### ISSUE TITLE
Lost files after presing "sync", any way to recover back to few hours or two days back.

### ISSUE THREAD

**Issue by rejji** [baumgarr/Nixnote2#509]
I lost my local files on NixNote2 after pressing "sync" on NixNote2 on Ubuntu. Can it be restored to morning time or last day, it is important. NixNote2 was not synched up with Evernote for some time, the way it looks. I observed there are sqlite3 db maintained at /home/rbakshi/.nixnote/db-1. I have copied that to a different place (after synch) in case it can give some cached data back.

**Comment by rejji** [comment]
Version is: nixnote2-daily+20180516

**Comment by robert7** [comment]
The database is SQLite - you can look inside using :) SQLite... e.q. using some visual browser like https://sqlitebrowser.org/ 
there are few SQL tables inside

But if the data are lost after sync... then it's weird… I don't know why it should be lost after sync…

If the data is already deleted, then you will not see it event using SQL
so no idea...

**Comment by rejji** [comment]
There was a local data on NixNote2. This was not snched up with remote Evernote servers. When I clicked "sync" on NixNote2, local data got rolled back to what was there on Evernote.

**Comment by robert7** [comment]
No idea, this should not happen.
Check whenever a new notebook called "conflicts" (or something like that) was created and if yes, what's inside. In case you edited the same notes in cloud (on Evernote server e.g. using web client) and on local (in Nixnote), conflict would happen. But even in this case, the data would not be overwritten.

**Comment by rejji** [comment]
Fantastic! This resolved the problem. Many thanks @robert7 .
