### ISSUE TITLE
Remember window position after restarting

### ISSUE THREAD

**Issue by workfriend** [baumgarr/Nixnote2#516]
First of all, thanks for making a nice implementation of an evernote client for linux. I really am not a fan with the direction that the official evernote client is going, and I really enjoy nixnote2.

One problem I have is with nixnote2 when the window first opens. It seems to forget the last-used window size.

I'm on Zorin OS 16.2 Pro which is using Gnome and uses Ubuntu 20.04 LTS as its base.

Is there a setting I'm missing, or any debug logs I can get you?

Thanks!

**Comment by boo-yee** [comment]
Nixnote stores the window size and position in the file $HOME/.config/nixnote2/nixnote.conf every time when they are changed. For now, you could check if this file's content is changed if you resize or move the window.

**Comment by workfriend** [comment]
Hi @boo-yee,

Thank you for responding! In my case, I am seeing that $HOME/.config/nixnote/nixnote-2.conf is getting updated.

And you're right. I don't know why I'm not having this problem anymore, but it seems like something fixed it... I'll have to try restarting and seeing if the desired behavior (i.e., window size and position being saved) persists.

Would you happen to know which properties inside of the nixnote conf files I could tune to "fix" or "lock" a specific window size?

If not, I'll submit a feature request.

Thanks!

**Comment by workfriend** [comment]
That is the strangest thing. I restarted and it started working again. No idea what those gremlins were, but looks like this fixed itself somehow.

**Comment by boo-yee** [comment]
> Hi @boo-yee,
> 
> Thank you for responding! In my case, I am seeing that $HOME/.config/nixnote/nixnote-2.conf is getting updated.
> 
> And you're right. I don't know why I'm not having this problem anymore, but it seems like something fixed it... I'll have to try restarting and seeing if the desired behavior (i.e., window size and position being saved) persists.
> 
> Would you happen to know which properties inside of the nixnote conf files I could tune to "fix" or "lock" a specific window size?
> 
> If not, I'll submit a feature request.
> 
> Thanks!

Hi, @beesyrupfactory

It's WindowState, isMaximized, and WindowGeometry. You could fix it by locking the config file temporarily.

I happened to add an option containing this(on my develop branch, not created PR yet). It allows the user to save or not save the UI changes, including the window size, window position and the widget layout. My code is under test now, and I'll create a PR as soon as it is finished. If this option can fulfill your requirement, you could wait for the next release.

As baumgarr, this project's owner, has stopped pushing code for years, I'll create the PR on this repo:
https://github.com/robert7/nixnote2, which is an active fork of nixnote.

**Comment by boo-yee** [comment]
> That is the strangest thing. I restarted and it started working again. No idea what those gremlins were, but looks like this fixed itself somehow.

If it is reproduced later, you could still notice $HOME/.config/nixnote/nixnote-2.conf, if its updated time is not updated, it means that nixnote has exited unexpectedly, it might be segment fault, etc.

**Comment by boo-yee** [comment]
> That is the strangest thing. I restarted and it started working again. No idea what those gremlins were, but looks like this fixed itself somehow.

I just found that if I resize or move the window by dragging the mouse, the window size and position can be remembered, but if I maximize the window by clicking the maximize button on the top, they will not be done. I am not sure if it is the truth of this issue.

**Comment by workfriend** [comment]
Sorry for the late response! Thanks @boo-yee. It looks like it's working again.
