### ISSUE TITLE
Copy / paste to external program not pasting formatting / bullet points

### ISSUE THREAD

**Issue by koenlek** [baumgarr/Nixnote2#52]
Just worked out my minutes in NixNote2 beta3. When I copy paste the contents to an email to share it with my colleagues, all the formatting is missing. Most notably, the bullet points that I always have used extensively.

Would be a nice feature to add, after you get it a bit more stable... It just crashed, turns out I lost the note completely now...

**Comment by baumgarr** [comment]
I don't think there is much I can do with the formatting.  When you click "Copy" it just calls QWebPage's Copy routine to copy the selected text.

**Comment by turbochad** [comment]
I've always gotten strange things doing cut and paste from Nixnote to open
office, like a grey box anywhere there is a double space to start.  Just
learned to paste unformatted

**Comment by baumgarr** [comment]
As far as I can determine, there is no way for me to fix this.  Sorry.
