### ISSUE TITLE
EDAMNotFoundException

### ISSUE THREAD

**Issue by wackywendell** [baumgarr/Nixnote2#53]
I opened Evernote, changed a note's Notebook and edited it, and then hit Sync - and I got `EDAMNotFoundException`. Here's an extract from the Message Log:

```
 INFO 2015-06-17 14:48:05.090 ( nixnote.cpp @ 1554 ) "Beginning Sync" 
 INFO 2015-06-17 14:48:05.801 ( nixnote.cpp @ 1554 ) "Downloading notes for shared notebook X." 
 INFO 2015-06-17 14:48:06.257 ( nixnote.cpp @ 1554 ) "Downloading notes for shared notebook Y." 
ERROR 2015-06-17 14:48:06.567 ( communication/communicationmanager.cpp @ 497 ) EDAMNotFoundException 
ERROR 2015-06-17 14:48:06.568 ( communication/communicationmanager.cpp @ 1064 ) EDAMNotFoundException: 

 INFO 2015-06-17 14:48:06.569 ( nixnote.cpp @ 1554 ) "EDAMNotFoundException: Note not found" 
 INFO 2015-06-17 14:48:07.022 ( nixnote.cpp @ 1554 ) "Downloading 100% complete for tags in shared notebook Z." 
 INFO 2015-06-17 14:48:07.022 ( nixnote.cpp @ 1554 ) "Downloading notes for shared notebook Z." 
 INFO 2015-06-17 14:48:07.042 ( nixnote.cpp @ 1554 ) "EDAMNotFoundException: Note not found" 
```

Let me know if there's any more info I can give you.

**Comment by artmg** [comment]
I notice this issue looks similar to http://sourceforge.net/p/nevernote/support-requests/34/

I had a similar EDAMNotFoundException error, with NixNote 2.0 Beta 3, although it did not involve shared notebooks.
```
 INFO 2015-09-05 17:27:41.401 ( nixnote.cpp @ 1554 ) "Beginning Sync" 
 INFO 2015-09-05 17:27:41.404 ( nixnote.cpp @ 1554 ) "Downloading changes" 
 INFO 2015-09-05 17:27:41.719 ( nixnote.cpp @ 1554 ) "Download 0% complete for notebooks, tags, & searches." 
 INFO 2015-09-05 17:27:41.722 ( nixnote.cpp @ 1554 ) "Download complete for notebooks, tags, & searches.  Downloading notes." 
 INFO 2015-09-05 17:27:42.589 ( nixnote.cpp @ 1554 ) "Download 0% complete." 
 INFO 2015-09-05 17:27:43.426 ( nixnote.cpp @ 1554 ) "Download complete." 
ERROR 2015-09-05 17:27:44.153 ( communication/communicationmanager.cpp @ 433 ) EDAMNotFoundException 
ERROR 2015-09-05 17:27:44.157 ( communication/communicationmanager.cpp @ 1064 ) EDAMNotFoundException: 

 INFO 2015-09-05 17:27:44.222 ( nixnote.cpp @ 1554 ) "EDAMNotFoundException: Note not found" 
 INFO 2015-09-05 17:27:44.225 ( nixnote.cpp @ 1554 ) "EDAMNotFoundException: Note not found" 
```
Looking in the top _Notebooks_ node I could see there was only one Note with the _Sync_ flag set. In my case it was a Conflict note, in a newly created conflict folder called Conflict.  

**Workaround:**
* Editing the unsynced, conflicting note showing in the Conflict folder 
  * renamed the _Note Title_ to add the word _CONFLICT_ (for my own reference)
  * changed the Note's _Notebook_ from Conflict to some other (regular) notebook 
* Now it was empty, I **Deleted** the _Conflict_ notebook
* retrying the sync now worked with no error

No guarantee this will work in your circumstances, but it's _something_ you could try

**Comment by baumgarr** [comment]
I think I found some of the issues with note conflicts.  If this is still an issue after the next release please reopen this issue.
