### ISSUE TITLE
Dockerfile to set up the compilation environment

### ISSUE THREAD

**Issue by uvatbc** [baumgarr/Nixnote2#54]
I have a dockerfile that will eliminate the manual requirement of setting up the dev environment for Nixnote2.

Here it is:
##
FROM ubuntu:15.04
RUN apt-get update ; apt-get install --assume-yes binutils build-essential bash-completion libqt4-dev make g++ libpoppler-qt4-dev libboost-dev libopencv-dev libhunspell-dev
##

With a container based on this image, compilation was a breeze and the resulting binary works perfectly.
An additional benefit of the dockerfile is the self-declaration of the build requirements.

**Comment by uvatbc** [comment]
Small correction: there's no need for the "g++ make" in the RUN command. The build-essentials takes care of it.

**Comment by baumgarr** [comment]
Thanks.  I think I added it properly.  Let me know if I messed it up.  I'm not familiar with how dockerfiles work, but I think I just include that file.
