### ISSUE TITLE
read-only mode

### ISSUE THREAD

**Issue by edgimar** [baumgarr/Nixnote2#55]
It would be great if nixnote provided a read-only button / menu-option that could be toggled on or off.  When enabled, this would prevent any editing of notes while viewing them.  If this were implemented, it might also be nice to be able to set what the default start-state should be.

**Comment by baumgarr** [comment]
Ok.  It should be in the next release.  There is a menu option under Tools to disable/enable editing, an option under Preferences to disable or enable on startup by default, and a command line option --disableEditing that should start it up disabled.  You can also assign it to a shortcut.  Let me know if you have issues.
