### ISSUE TITLE
g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed

### ISSUE THREAD

**Issue by fnkr** [baumgarr/nixnote2#56]
I have ~30 Notebooks and 4 of them wont open in Nixnote. If I click on one of them Nixnots stops working (gui freeze). Nixnote 2.0-beta3.

```
(nixnote2:22464): GLib-GObject-CRITICAL **: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed

(nixnote2:22464): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
```

Here is a full log with debug level trace: https://gist.github.com/fnkr/707a8448199796734485

**Comment by fnkr** [comment]
Workaround: disable "Display PDFs inline" (Edit>Preferences)

**Comment by baumgarr** [comment]
I'd try beta 4 to see if it helps.  There were some PDF issues that were fixed.

**Comment by baumgarr** [comment]
No response.  Closing.
