### ISSUE TITLE
Substring search stopped working?

### ISSUE THREAD

**Issue by fivef** [baumgarr/Nixnote2#61]
I loved NixNote for being able to find substrings of words. When I have the word "trajectory" in a note and search for "ctory" the note was still found. Now it seems that (like in the official evernote client and e.g. gmail) words are only matched from the beginning of the word on. (I have to search for e.g. "traj" to find the note with "trajectory". Where there any changes concerning this in the last few versions? Did you remove this function for performance sake? Is there a way to allow the user to reenable it? Or did this "substring search" never exist and I just remember it wrongly?

**Comment by baumgarr** [comment]
In the old NixNote there was an option to control this behavior for performance reasons, but in the newer one it should do substring searching automatically.  Try putting a * on the end to see if it helps.  It should be doing this automatically when you search.

**Comment by fivef** [comment]
I just tried it with Beta 4 with and without * before the word and after. It didn't work in any case.

**Comment by baumgarr** [comment]
I've tried on a couple of different distros and can't reproduce this.  One other thing to try is to use a % instead of a *.  I doubt it will make a difference but it is something to try.

Are you searching the contents of the note or a title or some other element?  Is it a complex search string or just a simple search?

**Comment by fivef** [comment]
I use Ubuntu 14.04 NixNote2 Beta 4, default Settings.
% doesn't help either.
 
To reproduce:
1. Create a note with title "substring" and content "substring"
2. Search for "string" or "*string" or "*string*" or "%string" or "%string%" all doesn't find the note.

**Comment by baumgarr** [comment]
I was just saarching for "sub" and it worked.  

NixNote uses SQLite's FTS search engine to do text searches.  This is just to increase the speed.  Unfortunately it doesn't support the search you described above.

To get around the issue I added some search logic for the next beta.  You'll need to use a "*" (i.e. *string) to do what you want, but it will work.  It will also be slower if you do this, but it should work.

**Comment by fivef** [comment]
Searching for *string works in beta 7. Very nice!
