### ISSUE TITLE
Nixnote2 crashes after opening and sitting at the initial screen for a few seconds

### ISSUE THREAD

**Issue by ChrisMagnuson** [baumgarr/nixnote2#62]
I have over 13000 notes in my personal evernote, with 12000 in a single notebook, as well as another 1100 notes in Evernote for Business notebooks. I also have 3926 personal tags and I don't see any easy place to get a count for the # of business tags in the iOS app.

Lots of large notes, many images, PDFs, documents, etc with my evernote database on windows being roughly 10 GB.

I use arch linux as my primary desktop at home and when I saw a preview image of the new nixnote2 I was very impressed and wanted to give it a try.

I have installed it from the Arch User Repository using the [nixnote-beta](https://aur.archlinux.org/packages/nixnote-beta/) package.

I was able to start nixnote and it had profiles configured from a previous time that I had tried nixnote against my evernote sandbox account.

I created a new profile and it began synching. It worked on synching for a day and a half and then crashed. When it first starts I can see that it says it has 9000+ notes but now it will open and without me touching anything or clicking synch it will crash.

![screenshot from 2015-09-16 11-52-07](https://cloud.githubusercontent.com/assets/2277702/9910201/f243e352-5c69-11e5-8535-211d3983482a.png)

I have opened it from a terminal window and here is the output it provided:

```
[cmagnuson@node1 ~]$ sudo pacman -Q nixnote-beta
nixnote-beta 2.0-8
[cmagnuson@node1 ~]$ nixnote2
DEBUG 2015-09-16 11:38:09.746 ( global.cpp @ 84 ) Shared memory key:  "1b73cc55-9a2f-441b-877a-ca1d0131cd24" 
 INFO 2015-09-16 11:38:09.779 ( main.cpp @ 139 ) Built with Qt 4.8.6 running on 4.8.7 
"Error: Failed to parse XRef entry [276]." 
"Error: Failed to parse XRef entry [1]." 
"Error: Failed to parse XRef entry [1]." 
"Error: Object (1 0) is not a pageDict" 
"Error: Failed parsing page 2 using hint tables" 
"Error: Failed to parse XRef entry [275]." 
"Error: Top-level pages object is wrong type (null)" 
Error: signal 11:
nixnote2(_Z13fault_handleri+0x18)[0x4839e8]
/usr/lib/libc.so.6(+0x33680)[0x7f659f007680]
/usr/lib/libpoppler-qt4.so.4(_ZNK7Poppler4Page4textERK6QRectFNS0_10TextLayoutE+0x61)[0x7f65a3b618d1]
/usr/lib/libpoppler-qt4.so.4(_ZNK7Poppler4Page4textERK6QRectF+0x1f)[0x7f65a3b61a3f]
nixnote2(_ZN11IndexRunner8indexPdfEiRN10qevercloud8ResourceE+0x473)[0x5b43d3]
nixnote2(_ZN11IndexRunner5indexEv+0x10fe)[0x5b8d0e]
nixnote2[0x71e0cb]
/usr/lib/libQtCore.so.4(_ZN7QObject5eventEP6QEvent+0x1d1)[0x7f659fdc43d1]
/usr/lib/libQtGui.so.4(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x8c)[0x7f65a066c39c]
/usr/lib/libQtGui.so.4(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x2b6)[0x7f65a06731f6]
nixnote2(_ZN11Application6notifyEP7QObjectP6QEvent+0x15)[0x641bd5]
/usr/lib/libQtCore.so.4(_ZN16QCoreApplication14notifyInternalEP7QObjectP6QEvent+0x8d)[0x7f659fdaa55d]
/usr/lib/libQtCore.so.4(_ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData+0x376)[0x7f659fdad9e6]
/usr/lib/libQtCore.so.4(+0x1cc703)[0x7f659fdda703]
/usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x24d)[0x7f659c6329fd]
/usr/lib/libglib-2.0.so.0(+0x49ce0)[0x7f659c632ce0]
/usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x2c)[0x7f659c632d8c]
/usr/lib/libQtCore.so.4(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x86)[0x7f659fdda876]
/usr/lib/libQtCore.so.4(_ZN10QEventLoop13processEventsE6QFlagsINS_17ProcessEventsFlagEE+0x41)[0x7f659fda8dd1]
/usr/lib/libQtCore.so.4(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0x1b5)[0x7f659fda9145]
/usr/lib/libQtCore.so.4(_ZN7QThread4execEv+0x139)[0x7f659fc97849]
/usr/lib/libQtCore.so.4(+0x8c13c)[0x7f659fc9a13c]
/usr/lib/libpthread.so.0(+0x74a4)[0x7f659eba84a4]
/usr/lib/libc.so.6(clone+0x6d)[0x7f659f0bd13d]
[cmagnuson@node1 ~]$ 
```

Let me know if there is anything I can try on my side to help establish what is causing this.

**Comment by baumgarr** [comment]
Sorry for the slow response.  Things have been a bit busy on my end with other things.

The messages say that this is beta 2, so the first thing I'd try is to upgrade to Beta 3.  I didn't create the arch package, so I can't update it but there is a tar.gz in SourceForge that has an install program.

There were also some bug fixes since beta 3, but they are not packaged iet.  I'm hoping to have beta 4 out soon, but it depends on free time.  I planned on having it out about 2 months ago but like keeps getting in the way.  :-)

**Comment by ChrisMagnuson** [comment]
I opened Nixnote2 and in the few seconds before it crashes went to Help > About and it says that it is 2.0-beta3:

![screenshot from 2015-09-24 12-17-26](https://cloud.githubusercontent.com/assets/2277702/10079265/068211c4-62b7-11e5-8d4f-3c7a411d6fad.png)

Is there a newer version or do I have the latest one?

**Comment by baumgarr** [comment]
Please try beta 4 and see if it corrects your issue.  Some of the indexing was changed.  In your case, I'd also delete the ~/.nixnote directory and start from scratch to make sure everything is indexed properly.

**Comment by ChrisMagnuson** [comment]
Relaunching nixnote2 after the upgrade to beta 4 still crashed a few seconds after opening.

I have now deleted ~/.nixnote and will see if it works with a clean start.

**Comment by ChrisMagnuson** [comment]
I have upgraded to the latest version of nixnote2 beta 4 (nixnote-beta 2.0_beta4-2) and now the application doesn't start.

If I start it from a terminal I get the following error:
`nixnote2: /usr/lib/libcurl.so.4: version 'CURL_OPENSSL_3' not found (required by nixnote2)`

Here is the output of ldd as well as ouput showing the libcurl that I have installed:

`````
cmagnuson@node1 ~/g/e/logstash> ldd /bin/nixnote2 | grep curl
/bin/nixnote2: /usr/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /bin/nixnote2)
	libcurl.so.4 => /usr/lib/libcurl.so.4 (0x00007f615331f000)
cmagnuson@node1 ~/g/e/logstash> ls /usr/lib/libcurl.so.4
/usr/lib/libcurl.so.4@
cmagnuson@node1 ~/g/e/logstash> ls /usr/lib/libcurl.so.4 -la
lrwxrwxrwx 1 root root 16 Oct  7 12:42 /usr/lib/libcurl.so.4 -> libcurl.so.4.4.0*
cmagnuson@node1 ~/g/e/logstash> pacman -Q curl
curl 7.45.0-1
`````

Based on the [files in the curl package](https://www.archlinux.org/packages/core/x86_64/curl/files/) that is where my version of libcurl.so.4 is coming from.

Any suggestion on what else I can try?

**Comment by baumgarr** [comment]
I'm not familiar with ArchLinux, but when I did a search hon the error message it seems to be common to other things using libcurl on Arch.

The couple of things I saw were to install an older libcurl or to make sure that libcurl is linked with ssl.

https://yabb.jriver.com/interact/index.php?topic=84334.0

**Comment by ChrisMagnuson** [comment]
Looks like the comments on the [AUR nixnote-beta](https://aur.archlinux.org/packages/nixnote-beta#comment-519754) package has other people reporting having the same issue and talking about work arounds.

Another arch user bumped into this as well and [posted](https://bbs.archlinux.org/viewtopic.php?id=205111) in the arch user forums.

Any possibility of having the version of lib curl used by nixnote2-beta updated to a newer version or having the version it needs included?

It would also be really nice to have this library in particularl on a recent version given the vulnerabilities that have been found over the last couple of years with SSL and specifically the OpenSSL library, like [Heartbleed](http://heartbleed.com/).

Thanks,

Chris

**Comment by baumgarr** [comment]
Try beta 5 and see if it fixes the problem.  I probably forgot to upgrade my distro to the latest patches prior to releasing beta 4.

**Comment by naraesk** [comment]
It is still the same CURL_OPENSSL_3 error with beta 5.

**Comment by baumgarr** [comment]
Well crud.  That is the newest version that is available to me.

There are not a whole lot of options open.  You can try doing what is referenced in this thread.  https://aur.archlinux.org/packages/nixnote-beta#comment-519754

About the only other thing I can suggest is to download & compile it yourself.  Unfortunately I'm in a catch-22. I can't upgrade & maintain compatibility with other people.  I'm forced to use the oldest supported version.

Sorry.

**Comment by baumgarr** [comment]
Tell you what,  If I get time this week and if you are willing to answer dumb Arch questions I'll try to install & build under Arch.  It will give me a chance to update the build instructions in the doc for another distro.

**Comment by naraesk** [comment]
Btw, why is the curl version such a big issue? I mean other software seems to have no problem wtih it. They work with ubuntu and they work with arch without problems, what is special about nixnote? I know that there are some topics about it in the arch user forums but they are about proprietary software; it doesn't seem like many applications are affected.

Anyway, if I can help you somehow, let me know.

**Comment by baumgarr** [comment]
Beats me.  I don't do anything special except to link against it to be able to download stuff from Evernote.  I'm building on Ubuntu so I don't know why Arch hates it so much.

**Comment by naraesk** [comment]
Yeah, found a solution. =)

 There is a "libcurl-compat" package for arch: https://aur.archlinux.org/packages/libcurl-compat/
Install it and then run:
 $ LD_PRELOAD=libcurl.so.3 nixnote2

**Comment by baumgarr** [comment]
Cool.  I'll update some of the doc to include this.  Thanks for the help!

**Comment by ChrisMagnuson** [comment]
When using the work around listed by naraesk I am getting a different error that I believe might not be related but I will post it here so that you can let me know if I should start a new issue on this error or not:

````
cmagnuson@node1 ~> env LD_PRELOAD=libcurl.so.3 nixnote2
nixnote2: /usr/lib/libcurl.so.3: no version information available (required by nixnote2)
 INFO 2015-12-09 20:17:09.082 ( main.cpp @ 157 ) Built on  Nov 22 2015  at  14:18:19 
 INFO 2015-12-09 20:17:09.082 ( main.cpp @ 158 ) Built with Qt 4.8.6 running on 4.8.7 
 INFO 2015-12-09 20:18:23.110 ( nixnote.cpp @ 1758 ) "Beginning Sync" 
 INFO 2015-12-09 20:18:23.111 ( nixnote.cpp @ 1758 ) "Downloading changes" 
 INFO 2015-12-09 20:18:23.552 ( nixnote.cpp @ 1758 ) "Download 0% complete for notebooks, tags, & searches." 
 INFO 2015-12-09 20:18:31.187 ( nixnote.cpp @ 1758 ) "Download 6% complete for notebooks, tags, & searches." 
 INFO 2015-12-09 20:18:39.311 ( nixnote.cpp @ 1758 ) "Download 9% complete for notebooks, tags, & searches." 
 INFO 2015-12-09 20:18:46.890 ( nixnote.cpp @ 1758 ) "Download 13% complete for notebooks, tags, & searches." 
 INFO 2015-12-09 20:18:54.335 ( nixnote.cpp @ 1758 ) "Download 18% complete for notebooks, tags, & searches." 
 INFO 2015-12-09 20:19:01.752 ( nixnote.cpp @ 1758 ) "Download 21% complete for notebooks, tags, & searches." 
 INFO 2015-12-09 20:19:09.282 ( nixnote.cpp @ 1758 ) "Download 26% complete for notebooks, tags, & searches." 
 INFO 2015-12-09 20:19:16.762 ( nixnote.cpp @ 1758 ) "Download 32% complete for notebooks, tags, & searches." 
 INFO 2015-12-09 20:19:24.251 ( nixnote.cpp @ 1758 ) "Download 37% complete for notebooks, tags, & searches." 
 INFO 2015-12-09 20:19:31.785 ( nixnote.cpp @ 1758 ) "Download 42% complete for notebooks, tags, & searches." 
 INFO 2015-12-09 20:19:39.255 ( nixnote.cpp @ 1758 ) "Download 50% complete for notebooks, tags, & searches." 
 INFO 2015-12-09 20:19:46.747 ( nixnote.cpp @ 1758 ) "Download 56% complete for notebooks, tags, & searches." 
 INFO 2015-12-09 20:19:54.418 ( nixnote.cpp @ 1758 ) "Download 63% complete for notebooks, tags, & searches." 
 INFO 2015-12-09 20:20:01.827 ( nixnote.cpp @ 1758 ) "Download 69% complete for notebooks, tags, & searches." 
 INFO 2015-12-09 20:20:09.419 ( nixnote.cpp @ 1758 ) "Download 81% complete for notebooks, tags, & searches." 
 INFO 2015-12-09 20:20:17.020 ( nixnote.cpp @ 1758 ) "Download 89% complete for notebooks, tags, & searches." 
 INFO 2015-12-09 20:20:24.393 ( nixnote.cpp @ 1758 ) "Download 99% complete for notebooks, tags, & searches." 
 INFO 2015-12-09 20:20:24.397 ( nixnote.cpp @ 1758 ) "Download complete for notebooks, tags, & searches.  Downloading notes." 
 INFO 2015-12-09 20:20:49.233 ( nixnote.cpp @ 1758 ) "Download 0% complete." 
"Error: Failed to parse XRef entry [276]." 
"Error: Failed to parse XRef entry [1]." 
"Error: Failed to parse XRef entry [1]." 
"Error: Object (1 0) is not a pageDict" 
"Error: Failed parsing page 2 using hint tables" 
"Error: Failed to parse XRef entry [275]." 
"Error: Top-level pages object is wrong type (null)" 
Error: signal 11:
nixnote2(_Z13fault_handleri+0x18)[0x49e528]
/usr/lib/libc.so.6(+0x33680)[0x7fba86b58680]
/usr/lib/libpoppler-qt4.so.4(_ZNK7Poppler4Page4textERK6QRectFNS0_10TextLayoutE+0x61)[0x7fba8b6b5af1]
/usr/lib/libpoppler-qt4.so.4(_ZNK7Poppler4Page4textERK6QRectF+0x1f)[0x7fba8b6b5c5f]
nixnote2(_ZN11NoteIndexer8indexPdfEi+0x62e)[0x76c22e]
nixnote2(_ZN11NoteIndexer13indexResourceEi+0xb38)[0x76db68]
nixnote2(_ZN13ResourceTable3addEiRN10qevercloud8ResourceEbi+0x89b)[0x54da3b]
nixnote2(_ZN9NoteTable3addEiRKN10qevercloud4NoteEbi+0x1310)[0x56abb0]
nixnote2(_ZN9NoteTable4syncEiRKN10qevercloud4NoteEi+0x100)[0x56f410]
nixnote2(_ZN10SyncRunner15syncRemoteNotesE5QListIN10qevercloud4NoteEEi+0x185)[0x4f9d95]
nixnote2(_ZN10SyncRunner16processSyncChunkERN10qevercloud9SyncChunkEi+0x740)[0x4fafa0]
nixnote2(_ZN10SyncRunner17syncRemoteToLocalEi+0x40b)[0x4fc79b]
nixnote2(_ZN10SyncRunner12evernoteSyncEv+0x2fe)[0x4fd0ee]
nixnote2(_ZN10SyncRunner11synchronizeEv+0x7e)[0x4fd86e]
nixnote2[0x790278]
/usr/lib/libQtCore.so.4(_ZN7QObject5eventEP6QEvent+0x1d1)[0x7fba879153e1]
/usr/lib/libQtGui.so.4(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x8c)[0x7fba881bd39c]
/usr/lib/libQtGui.so.4(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x2b6)[0x7fba881c41f6]
nixnote2(_ZN11Application6notifyEP7QObjectP6QEvent+0x15)[0x67c195]
/usr/lib/libQtCore.so.4(_ZN16QCoreApplication14notifyInternalEP7QObjectP6QEvent+0x8d)[0x7fba878fb56d]
/usr/lib/libQtCore.so.4(_ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData+0x376)[0x7fba878fe9f6]
/usr/lib/libQtCore.so.4(+0x1cc713)[0x7fba8792b713]
/usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x2a7)[0x7fba83871dc7]
/usr/lib/libglib-2.0.so.0(+0x4a020)[0x7fba83872020]
/usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x2c)[0x7fba838720cc]
/usr/lib/libQtCore.so.4(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x86)[0x7fba8792b886]
/usr/lib/libQtCore.so.4(_ZN10QEventLoop13processEventsE6QFlagsINS_17ProcessEventsFlagEE+0x41)[0x7fba878f9de1]
/usr/lib/libQtCore.so.4(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0x1b5)[0x7fba878fa155]
/usr/lib/libQtCore.so.4(_ZN7QThread4execEv+0x139)[0x7fba877e8849]
/usr/lib/libQtCore.so.4(+0x8c13c)[0x7fba877eb13c]
Error: signal 11:
nixnote2(_Z13fault_handleri+0x18)[0x49e528]
/usr/lib/libc.so.6(+0x33680)[0x7fba86b58680]
/usr/lib/libQtGui.so.4(_ZN4QPenC1Ev+0x34)[0x7fba88343c04]
/usr/lib/libQtGui.so.4(_ZN13QPainterStateC1Ev+0x64)[0x7fba8830c304]
/usr/lib/libQtGui.so.4(+0x3ce0f3)[0x7fba883890f3]
/usr/lib/libQtGui.so.4(+0x3d7d75)[0x7fba88392d75]
/usr/lib/libQtGui.so.4(_ZN8QPainter5beginEP12QPaintDevice+0x155)[0x7fba88312615]
/usr/lib/libQtGui.so.4(_ZN8QPainterC2EP12QPaintDevice+0x108)[0x7fba883130f8]
/usr/lib/libQtGui.so.4(_ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore+0x55c)[0x7fba8820e1cc]
/usr/lib/libQtGui.so.4(+0x4238f2)[0x7fba883de8f2]
/usr/lib/libQtGui.so.4(_ZN14QWidgetPrivate16syncBackingStoreEv+0xa0)[0x7fba88200f90]
/usr/lib/libQtGui.so.4(_ZN7QWidget5eventEP6QEvent+0x388)[0x7fba88213d08]
/usr/lib/libQtGui.so.4(_ZN11QMainWindow5eventEP6QEvent+0x113)[0x7fba885f42c3]
nixnote2(_ZN7NixNote5eventEP6QEvent+0x27)[0x4b8487]
/usr/lib/libQtGui.so.4(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x8c)[0x7fba881bd39c]
/usr/lib/libQtGui.so.4(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x2b6)[0x7fba881c41f6]
nixnote2(_ZN11Application6notifyEP7QObjectP6QEvent+0x15)[0x67c195]
/usr/lib/libQtCore.so.4(_ZN16QCoreApplication14notifyInternalEP7QObjectP6QEvent+0x8d)[0x7fba878fb56d]
/usr/lib/libQtCore.so.4(_ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData+0x376)[0x7fba878fe9f6]
/usr/lib/libQtCore.so.4(+0x1cc713)[0x7fba8792b713]
/usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x2a7)[0x7fba83871dc7]
/usr/lib/libglib-2.0.so.0(+0x4a020)[0x7fba83872020]
/usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x2c)[0x7fba838720cc]
/usr/lib/libQtCore.so.4(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x64)[0x7fba8792b864]
/usr/lib/libQtGui.so.4(+0x2ab3b6)[0x7fba882663b6]
/usr/lib/libQtCore.so.4(_ZN10QEventLoop13processEventsE6QFlagsINS_17ProcessEventsFlagEE+0x41)[0x7fba878f9de1]
/usr/lib/libQtCore.so.4(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0x1b5)[0x7fba878fa155]
/usr/lib/libQtCore.so.4(_ZN16QCoreApplication4execEv+0x99)[0x7fba878ffb09]
nixnote2(main+0xd1e)[0x4998ee]
/usr/lib/libc.so.6(__libc_start_main+0xf0)[0x7fba86b45610]
cmagnuson@node1 ~> 
````

This occurs each time I open nixnote2 and do a synch with a fresh nixnote environment with no prior data loaded.

**Comment by jeffbuhrt** [comment]
@ChrisMagnuson it looks like a specific 'bad' note. I would open it as a new ticket. 
To get more detail on the failure: Change the message level to trace under Preferences/Debug it will give a better indication of what is happening within NixNote and maybe you can figure out the specific note that causes the failure.

If you can isolate the problem note with the issue and are able/willing to share that note:
-make a new notebook and move the 'bad' note into it
-create a test Evernote account
-move .nixnote to .nixnote-old
-share the test notebook to the new account (via the web interface/phone/tablet/etc)
-repeat the problem with one 'bad' note in a single notebook using your new test account.
-I would then share the notebook with @baumgarr

**Comment by baumgarr** [comment]
This doesn't look like the same issue so, as Jeff mentioned, I'd appreciate another ticket to avoid confusion.

It looks like there is a PDF that Poppler is choking on (or I'm not calling Poppler correctly).  

This message is also new to  me
nixnote2: /usr/lib/libcurl.so.3: no version information available (required by nixnote2), but I don't think it is related.

**Comment by baumgarr** [comment]
I created a new beta that may help with this.  Before doing a sync, go into Edit/Preferences and look under the Search tab.  There is an option to index PDFs locally.  Try de-selecting this and see if it alters the behavior of the problem.  It won't index PDFs locally but from the looks of the trace it should bypass poppler.  If you still have an issue please open a new ticket.  Thanks.
