### ISSUE TITLE
Create Launchpad autobuild to publish NixNote2 to Ubuntu PPA

### ISSUE THREAD

**Issue by artmg** [baumgarr/nixnote2#65]
Inspired by [Maffblaster](https://github.com/Maffblaster)'s Issue https://github.com/baumgarr/Nixnote2/issues/63 I am creating this self-assigned enhancement request to cajole me into setting up an Import from GitHub to Launchpad so that NixNote2 can be auto-built into a PPA. The result will make it really simple, even for novice users, to install key milestone versions of NixNote2 into Ubuntu and it's derivative distributions.

* I intend to create this as a Team PPA, in the hope that others may consider collaborating. This way I hope to reduce the likelihood that the PPA will become stale if any individual suddenly gets too busy on other projects.
* This will be the first time I have published to a PPA. I am tracking what I learn (see https://github.com/artmg/lubuild/wiki/Application-Packaging), and I plan to write out the procedures, so that others who wish to help will find it simple to follow.
* My intention is to automate as much as possible, reducing the effort for collaborators, and I would hope to have a series of pushbutton tasks that can be executed everytime [baumgarr](https://github.com/baumgarr) cuts a milestone version of the codebase. If it is quick and easy, it is more likely to be done, and continue to be done, for as many versions of ubuntu as are likely to be in use.
* I am now at the point where I need to set up the launchpad import and get it to use the **[deb/control](https://github.com/baumgarr/Nixnote2/blob/master/package_scripts/deb/control)** in the source folders (keeping my fingers crossed that it gives launchpad's debian build farm everything it needs to know)

I welcome guidance from any fellow NixNote fans who may have experience of building to PPAs, as I put this together

**Comment by artmg** [comment]
Now that Beta 4 is out, I have now set up the following in Launchpad:

Team: https://launchpad.net/~nixnote
PPA: https://launchpad.net/~nixnote/+archive/ubuntu/nixnote2-daily
Source: https://code.launchpad.net/~nixnote/nixnote2/artemgy_head

If you want to be a member of the team helping set up and maintain the builds please ask to be added at

https://launchpad.net/~nixnote

Although the PPA does not yet contain fully working builds, I am tracking my actions as **Instructions to set up Launchpad import and build** at https://github.com/artmg/lubuild/wiki/Application-Packaging#instructions

**Comment by JPvRiel** [comment]
A PPA would be nice. I noticed the debian package from sourceforge has some dependency issues on the 15.10 release of ubuntu. I logged a ticket on sourceforge related to this: https://sourceforge.net/p/nevernote/bugs/217/

**Comment by artmg** [comment]
Many thanks @JPvRiel - I have raised this as [an Issue in the nixnote2-packaging repo](https://github.com/artmg/nixnote2-packaging/issues/1) that is where the PPA gets its debian control info. As soon as I have a working package in the PPA I will drop you a line in case you wish to test it.

**Comment by artmg** [comment]
Randy, JP, or any fans of NixNote...

I am keen to get this PPA working, so that users of all Ubuntu derivatives have easy access to the upcoming formal release of NixNote2, and subsequent updates. However I am stuck with Launchpad Builds failing, or containing no executable when they succeed, and I don't yet have sufficient experience to troubleshoot this myself.

Could you recommend anyone with experience of Launchpad Recipes and Debian Control files who could help me on this final, small, but so far fatal hurdle?

Any pointers welcome
Thanks
Artemgy

**Comment by baumgarr** [comment]
I was hoping someone would have replied by now, but I'm afraid I have zero knowledge of creating a PPA.  Sorry.

**Comment by JPvRiel** [comment]
@artmg apologies, I've also got no experience with setting up a PPA, but happy to test using the PPA.

**Comment by vitaly-zdanevich** [comment]
+1 for PPA

**Comment by artmg** [comment]
Thanks to working packaging control files pushed by @vitaleon the PPA at https://launchpad.net/~nixnote/+archive/ubuntu/nixnote2-daily is **now producing daily builds**. Although the recipe still calls the package beta 4 the code is taken DIRECTLY from @baumgarr 's head here. 

Please let me know any results or issues from your own tests on this PPA. If you discover **packaging or PPA issues** please raise them via https://github.com/artmg/nixnote2-packaging/issues (as opposed to in baumgarr's issue list here, which is just about the functionality of nixnote2 when you run it)

I appreciate your contributions :)

**Comment by JPvRiel** [comment]
@artmg thanks, switching to using your ppa instead of manual .deb install. That said, nice to see that the Nixnote2 Beta 7 .deb file from sourceforge installed on 15.10 without issues.
