### ISSUE TITLE
Unresponsive after leaving open for some time?

### ISSUE THREAD

**Issue by jarradh** [baumgarr/Nixnote2#66]
I'm running nixnote2 in i3 on arch, nixnote2 works great at first, i leave it open throughout the day but i notice if i leave it after sometime it becomes unresponsive. It doesn't appear to be related to switching workspaces, but I can't kill it either in i3. I have to end up using xkill. I ran via cli but no errors were outputting, sync was successful, only after using xkill i got a message saying resource was unresponsive.

**Comment by baumgarr** [comment]
Please try beta 4.  I reworked some of the indexing.  If your database isn't completely indexed, I'd recommend deleting the ~/.nixnote directory and starting over.  You can check if it is indexed via the Tools/Database Status message.

**Comment by baumgarr** [comment]
Closing.  This should be better in the latest beta.
