### ISSUE TITLE
Use git tag for version tracking

### ISSUE THREAD

**Issue by Maffblaster** [baumgarr/Nixnote2#69]
We should definitely start using git tag for version tracking, even for beta releases.

Also, tags make it better for GitHub to host releases: https://github.com/baumgarr/Nixnote2/releases

**Comment by baumgarr** [comment]
I didn't know there was such a thing. I'll look at it and see if I understand how it works. Thanks.

**Comment by baumgarr** [comment]
Done.  Let me know if I messed it up.

**Comment by Maffblaster** [comment]
@baumgarr Looks good to me! When you release you simply create new tags for each specified version associated to the "release" commit.

I'd like to see you go to a semantic version scheme (Major.Minor.Patch like the Linux kernel) when you release the official v2.0 build. That would make it really helpful for people to easily create download scripts. In my case it would make it easy for Portage to download the package directly from GitHub. As long as you say consistent that's what counts. :)
