### ISSUE TITLE
Nixnote2 doesn't delete empty tags

### ISSUE THREAD

**Issue by michaelcadilhac** [baumgarr/Nixnote2#70]
I'm trying to remove a tag that lingers with nothing attached.  I use right click*, then Delete, Sync, and restart the app, and boom, it's back.  The log file is pretty much uninteresting, but here's at least a video of that behavior:

   http://michael.cadilhac.name/public/bug.mp4

(You can also note a second bug in there : just after deletion of the tag, the Note list shows my two notes instead of showing only the one inside Perso, the selected notebook.)

*: Side note, the Notebook and Tags section of the right panel behave inconsistently in the way they treat right click focusing.  One focuses the element right clicked THEN opens the context menu, and the other just opens the context menu.

**Comment by michaelcadilhac** [comment]
*: For the side note, the behavior I expect is this one:
```patch
diff --git a/gui/nnotebookview.cpp b/gui/nnotebookview.cpp
index 0b2528a..fef7816 100644
--- a/gui/nnotebookview.cpp
+++ b/gui/nnotebookview.cpp
@@ -218,8 +218,11 @@ void NNotebookView::mousePressEvent(QMouseEvent *event)
 {
     QModelIndex item = indexAt(event->pos());
     bool selected = selectionModel()->isSelected(indexAt(event->pos()));
+
     QTreeView::mousePressEvent(event);
-    if (selected)
+
+    // Only deselect using left button; otherwise, select.
+    if (selected && (event->buttons() & Qt::LeftButton))
         selectionModel()->select(item, QItemSelectionModel::Deselect);
 
     for (int i=0; i<this->selectedItems() .size(); i++) {
diff --git a/gui/ntagview.cpp b/gui/ntagview.cpp
index eb82893..0420ae1 100644
--- a/gui/ntagview.cpp
+++ b/gui/ntagview.cpp
@@ -220,10 +220,11 @@ void NTagView::mousePressEvent(QMouseEvent *event)
 {
     QModelIndex item = indexAt(event->pos());
     bool selected = selectionModel()->isSelected(indexAt(event->pos()));
-    if (!(event->buttons() & Qt::LeftButton))
-            return;
+
     QTreeView::mousePressEvent(event);
-    if (selected)
+
+    // Only deselect using left button; otherwise, select.
+    if (selected && (event->buttons() & Qt::LeftButton))
         selectionModel()->select(item, QItemSelectionModel::Deselect);
 
     for (int i=0; i<this->selectedItems() .size(); i++) {
```

**Comment by baumgarr** [comment]
I think I have the tag deletion problem fixed & ready for the next release.  If it is still an issue after beta 5 let me know.  

I'll take a look at the selection logic above.  Thanks for the help!

**Comment by baumgarr** [comment]
Added the mouse logic.  Thanks!

**Comment by michaelcadilhac** [comment]
In `ntagview.cpp`, you did not delete:
```c++
if (!(event->buttons() & Qt::LeftButton))
            return;
```
Is it on purpose?
