### ISSUE TITLE
Can't change font size. Ubuntu 15.04

### ISSUE THREAD

**Issue by GriMel** [baumgarr/Nixnote2#79]
Just installed NixNote2 beta4 from sourceforge.
I can't change either font size - (font size box is missing) in note either default font size in Edit/Preferences - dropdown menu shows only "System default"

**Comment by baumgarr** [comment]
I'm unable to reproduce this.  What font packages do you have installed?  You may want to try ttc-mscorefonts-installer for better cross-platform because Evernote uses some of those fonts.

**Comment by GriMel** [comment]
ttf-mscorefonts-installer is already the newest version. OK, maybe I need to reinstall NixNote2.
Is it possible to reinstall NixNote2 without needing to sync all notes again?

**Comment by baumgarr** [comment]
Yes.  Just un-install the deb & re-install it.  Your local data isn't removed and is stored in ~/.nixnote.

I'm not sure that will correct the problem.  All I do is to query the window manager for all available fonts and display them.

**Comment by GriMel** [comment]
Just reinstalled - didn't help. It's what my typical note looks like in full screen
![snapshot](https://cloud.githubusercontent.com/assets/1565987/10605930/ee6b6a0a-7737-11e5-9b8a-e1ad685ceb68.png)

**Comment by GriMel** [comment]
I figured this out - I can change the font size only when I open the note in new window - is it correct behaviour for NixNote?

**Comment by baumgarr** [comment]
No, but you do need to select the text you want to change.  It doesn't currently allow you to change the font & just start typing.  From the screen print it looks like it is populating the font names.

**Comment by GriMel** [comment]
Open the same note in new Window.
![snapshot-2](https://cloud.githubusercontent.com/assets/1565987/10606738/8d3fb820-773d-11e5-84ff-a882b65f1c62.png)

**Comment by GriMel** [comment]
The same note in new window - just to show.
![snapshot-3](https://cloud.githubusercontent.com/assets/1565987/10606779/cbfd9de8-773d-11e5-9753-2f61c0cd9641.png)

**Comment by baumgarr** [comment]
Sorry.  I misread the problem as font & not font size.

The problem in the existing window is that there are too many buttons to fit across the screen.  See the little >> at the end?  That means there are more.  The font size (and sometimes other buttons) won't show when you click the >> because of a Qt limitation.  There isn't anything I can do about it.  If you need to see it, right click on the toolbar & turn off some of the buttons to free up space.

**Comment by GriMel** [comment]
I got this. Manually changed the width of preview and there they are! 
Maybe as a workaround you can use two toolbars  where the second will start from "Font type" box? Or it's overkill? :)

**Comment by baumgarr** [comment]
Cool.  Glad it works.  I'm hoping that Qt5 doesn't have this issue, but I'm not planning on going to Qt5 until I have a good release under the existing Qt 4.8.  It makes it easier to debug in beta if I keep as much constant as possible.
