### ISSUE TITLE
Weird behaviour of shortcuts

### ISSUE THREAD

**Issue by GriMel** [baumgarr/Nixnote2#80]
When I try to make text bold or underlined by Ctrl+B or Ctrl+U nothing is changed at first - the corresponding box (B or a) on toolbar is selected and styles are applied only after clicking Space.

On screenshot - just clicked Ctrl+B.
![snapshot-1](https://cloud.githubusercontent.com/assets/1565987/10631030/bf297e38-77e3-11e5-9391-ad078dd1f24c.png)

**Comment by baumgarr** [comment]
I think I have this fixed in the next release.  If it isn't please reopen this issue.  Thanks for the report!
