### ISSUE TITLE
Changing font and fontsize of note does not work

### ISSUE THREAD

**Issue by cmiramon** [baumgarr/Nixnote2#82]
I've installed nixnote 2.0-beta4 on Ubuntu 14.04LTS. 

It works much better and I had no problem synchronizing my evernote database. Thanks for the great work !

Changing the font and fontsize of words in a note is very unreliable. Maybe it is because I use also the evernote web application that offers  limited fonts (7 fonts) and font sizes. (8 sizes)

If I use in Nixnote 2 the same fonts and the same fonts size that the Web application, it works.

Would it be possible to limit the font options in Nixnote2 to the same subset than the Web application ?

**Comment by baumgarr** [comment]
My first reaction to this would be not to limit the fonts.  It limits people who are not using the web interface and it means if Evernote changes their font support I'll need to update mine.  It isn't something I'd like to do, but I'll give it some thought.

**Comment by cmiramon** [comment]
Thank you for your quick answer !

Well on my computer getting the list of fonts when I push the font combo is very slow (3 seconds) because I have a lot of fonts. I don't think a note application need a large amount of font choice but maybe other people have other opinions.

I see that when you create a note on the web application, the css has fonts fallback like here 
<span style="font-family: verdana, helvetica, sans-serif;">

but if you create a note on Nixnote2 you have <font face="input mono">

Maybe having a fallback mechanism to the fonts Evernote uses on the Web or in the Android app would improve compatibility between mediums.

**Comment by baumgarr** [comment]
I don't see either of the examples...

I'll give it some thought on how to handle it, but I'm not sure that it would help your response time issue.  I'd still need to query the entire list of fonts available and then compare them to a subset.  I can't just assume that a font is available or it would cause other problems.

**Comment by baumgarr** [comment]
I've added an option under Appearance that will only allow a subset of fonts.
