### ISSUE TITLE
Wrong account type?

### ISSUE THREAD

**Issue by romansemko** [baumgarr/Nixnote2#85]
I am not sure if this is a bug. My Evernote account is "Plus" - that's somewhere between "Free" and "Premium". However, Nixnote2 ist showing the account type in usage info as "Free".

**Comment by baumgarr** [comment]
Thanks.  I'll take a look at it.

**Comment by baumgarr** [comment]
Looking at the API, there isn't a distinction that I can use.  I did add a check for "VIP" (which may be what they are using for business), but that is about all I can find.

Thanks.
