### ISSUE TITLE
Richt click on the left panel items deselects the item

### ISSUE THREAD

**Issue by romansemko** [baumgarr/Nixnote2#86]
When an Item is selected in the left panel (notebook, tag, saved searches, etc) it can be unselected by either left or right click. Unselecting a previously selected item with left click makes sense, but not with the right one.

A case where it gets problematic is when you have an item selected and want to modify its properties from the menu by right-clicking it. The click oepns the menu, but automatically unselects the item, which renders the "Properties" menu item disabled.

A solution would be preventing the right click to unselect the items.

**Comment by romansemko** [comment]
The only way to access the "properties" for me right now is left-click to select an item and the right-click-and-hold while moving to the "properties" in the menu.

**Comment by baumgarr** [comment]
This should be fixed in the next release.
