### ISSUE TITLE
Add Tag on Enter

### ISSUE THREAD

**Issue by romansemko** [baumgarr/Nixnote2#87]
Not a Bug, but it would be a nice feature to have when adding tags. When you are writing a tag in a note or select one from the already existing tags, it would be nice if the tag would be added when "Enter" is pressed, so you don't have to click out with the mouse and click on the "+" to add another one.

Additional plus would be, if I could continuously write several tags without touching the mouse. Write tag -> enter -> a new tag slot is displayed -> write tag -> enter -> ...

**Comment by baumgarr** [comment]
You can add multiple tags in the current release by pressing the tab key to go to the next new tag slot.  

Regardless, what you are asking for is already slated for the next release.  You'll also be able to use a comma to jump to a new tag.

**Comment by romansemko** [comment]
Ah. Didn't check the next release info. Thanks for pointing out and for the tips. You guys are doing an awesome job!
