### ISSUE TITLE
Changing fontsize of note (again)

### ISSUE THREAD

**Issue by cmiramon** [baumgarr/Nixnote2#88]
Tested on nixnote2 master with the Webfonts option (thankyou, it seems to synchronize much better with the Windows client) and nixnote2 beta4

1) Create a new note with fontsize 12
2) Type "John" two CR "Doe"
3) Select John -> fontsize 14
4) Select John + two empty lines + Doe
5) -> fontsize 14. 

Changes are not applied.

 It works if John and Doe are on the same line. Changing the font across paragraphs works.

**Comment by baumgarr** [comment]
I have improved it a little so it works in more instances.  It doesn't always work, but it is as good as it is going to get.
