### ISSUE TITLE
Incorrect multiple tags selection

### ISSUE THREAD

**Issue by GriMel** [baumgarr/Nixnote2#89]
For example - I have a note with tags "Now" and "Programming"
On the left list of tags I select tag "Now(10)" and I see, that "Programming (66)" is changed to "Programming 5/66", so I get that there are 5 notes with "Now" and "Programming" tags.
But, when with Ctrl I select tag "Programming" it shows notes with either "Now" or "Programming" tags - all 10 notes with "Now" tag and all 66 notes with "Programming" tag.

**Comment by baumgarr** [comment]
I thought that was the way Evernote's client behaved.  I've altered it to match Evernote's client and it should be in the next release.

Thanks.
