### ISSUE TITLE
deb package: need openssl dependency

### ISSUE THREAD

**Issue by miurahr** [baumgarr/Nixnote2#9]
I found several issues through building deb package through standard way.
Here is a place to see source/binary packages and download debian control files.
https://launchpad.net/~miurahr/+archive/nixnote2/+packages

There is an issue for build and run time dependency for openssl.
it depends on  libssl-dev for build-dep and libssl1.0.0 for run time.

**Comment by baumgarr** [comment]
Closing the issue per @miurahr.
