### ISSUE TITLE
Nixnote build failed with opencv-3.0

### ISSUE THREAD

**Issue by zhtengw** [baumgarr/nixnote2#96]
Nixnote build failed with opencv-3.0 : 

/var/tmp/portage/app-misc/nixnote2-2.0_beta4/work/Nixnote2-2.0-beta4/dialog/webcamcapturedialog.cpp:46: undefined reference to `cv::VideoCapture::VideoCapture(int)'
collect2: error: ld returned 1 exit status
Makefile.Release:634: recipe for target 'nixnote2' failed

When I downgrade opencv to version 2.4, no errors any more.

**Comment by baumgarr** [comment]
According to SO, some libraries moved in OpenCV 3.  If you want to use them you'll need to modify the source & project a bit.

http://stackoverflow.com/questions/25876684/opencv-3-0-undefined-reference-error

**Comment by zhtengw** [comment]
Thank you!

Best regards
Aten
